import json

new_questions = [
# ── BASKETBALL continued ──
{"q":"Which player won the NBA Finals MVP award in 2023?","a":"Nikola Jokic","choices":["Nikola Jokic","Jamal Murray","Jimmy Butler","Bam Adebayo"],"sport":"basketball","difficulty":"medium"},
{"q":"What is a double-double in basketball?","a":"Reaching double digits in two statistical categories in a game","choices":["Reaching double digits in two statistical categories in a game","Scoring 20+ points twice in a game","Two players each scoring 10+ points","Making two three-pointers in one quarter"],"sport":"basketball","difficulty":"easy"},
{"q":"Which team drafted Giannis Antetokounmpo in the 2013 NBA Draft?","a":"Milwaukee Bucks","choices":["Milwaukee Bucks","Atlanta Hawks","Philadelphia 76ers","New York Knicks"],"sport":"basketball","difficulty":"medium"},
{"q":"Who was selected #2 overall in the 2003 NBA Draft?","a":"Carmelo Anthony","choices":["Carmelo Anthony","Chris Bosh","Dwyane Wade","Chris Kaman"],"sport":"basketball","difficulty":"medium"},
{"q":"Which NBA team is nicknamed the 'We Believe' squad of 2007?","a":"Golden State Warriors","choices":["Golden State Warriors","Dallas Mavericks","Denver Nuggets","Utah Jazz"],"sport":"basketball","difficulty":"hard"},
{"q":"How many fouls does it take to foul out of an NBA game?","a":"6","choices":["6","5","7","4"],"sport":"basketball","difficulty":"easy"},
{"q":"Who won the first three-point shootout at NBA All-Star Weekend?","a":"Larry Bird","choices":["Larry Bird","Isiah Thomas","Craig Hodges","Dale Ellis"],"sport":"basketball","difficulty":"hard"},
{"q":"Which player set the NBA record for most points in a season (4,029 in 1961-62)?","a":"Wilt Chamberlain","choices":["Wilt Chamberlain","Elgin Baylor","Jerry West","Oscar Robertson"],"sport":"basketball","difficulty":"hard"},
{"q":"What NBA team does Jayson Tatum play for?","a":"Boston Celtics","choices":["Boston Celtics","Brooklyn Nets","Philadelphia 76ers","Toronto Raptors"],"sport":"basketball","difficulty":"easy"},
{"q":"Who won the 2021 NBA championship?","a":"Milwaukee Bucks","choices":["Milwaukee Bucks","Phoenix Suns","Atlanta Hawks","Philadelphia 76ers"],"sport":"basketball","difficulty":"medium"},
{"q":"Which player averaged 50.4 points per game over one full NBA season?","a":"Wilt Chamberlain (1961-62)","choices":["Wilt Chamberlain (1961-62)","Michael Jordan","Kobe Bryant","LeBron James"],"sport":"basketball","difficulty":"hard"},
{"q":"What is the three-second rule in the NBA?","a":"An offensive player cannot stay in the paint for more than 3 consecutive seconds","choices":["An offensive player cannot stay in the paint for more than 3 consecutive seconds","A shot must be taken within 3 seconds of entering the frontcourt","A defender cannot stay in the lane for 3 seconds without guarding someone","You must dribble within 3 seconds of receiving a pass"],"sport":"basketball","difficulty":"medium"},
{"q":"Which team drafted Kevin Durant in the 2007 NBA Draft?","a":"Seattle SuperSonics","choices":["Seattle SuperSonics","Oklahoma City Thunder","Golden State Warriors","Portland Trail Blazers"],"sport":"basketball","difficulty":"medium"},
{"q":"Who was the first player in NBA history to average a triple-double for a full season in the modern era?","a":"Russell Westbrook (2016-17)","choices":["Russell Westbrook (2016-17)","Magic Johnson","Oscar Robertson","Jason Kidd"],"sport":"basketball","difficulty":"hard"},
{"q":"Which team did Charles Barkley win his only NBA MVP award with?","a":"Phoenix Suns","choices":["Phoenix Suns","Philadelphia 76ers","Houston Rockets","Golden State Warriors"],"sport":"basketball","difficulty":"medium"},
{"q":"Who holds the record for most three-pointers in a single NBA game?","a":"Klay Thompson (14)","choices":["Klay Thompson (14)","Stephen Curry (13)","Donyell Marshall (12)","Zach LaVine (11)"],"sport":"basketball","difficulty":"hard"},
{"q":"How wide is an NBA basketball court in feet?","a":"50 feet","choices":["50 feet","45 feet","55 feet","48 feet"],"sport":"basketball","difficulty":"hard"},
{"q":"Which player is known as 'The Answer'?","a":"Allen Iverson","choices":["Allen Iverson","Steve Francis","Gilbert Arenas","Baron Davis"],"sport":"basketball","difficulty":"medium"},
{"q":"Who was the first unanimous NBA MVP since the award began?","a":"Stephen Curry (2016)","choices":["Stephen Curry (2016)","Michael Jordan","Kareem Abdul-Jabbar","LeBron James"],"sport":"basketball","difficulty":"hard"},
{"q":"Which city do the Nets play in?","a":"Brooklyn","choices":["Brooklyn","Newark","New York City","Queens"],"sport":"basketball","difficulty":"easy"},
{"q":"Who won the NBA scoring title the most times?","a":"Michael Jordan (10 times)","choices":["Michael Jordan (10 times)","Wilt Chamberlain (7 times)","LeBron James (1 time)","Allen Iverson (4 times)"],"sport":"basketball","difficulty":"hard"},
{"q":"What year did the Charlotte Hornets rename themselves the Bobcats temporarily?","a":"2004","choices":["2004","2002","2006","2008"],"sport":"basketball","difficulty":"hard"},
{"q":"Who scored 69 points in an NBA game in 1990?","a":"Michael Jordan","choices":["Michael Jordan","David Robinson","Karl Malone","Clyde Drexler"],"sport":"basketball","difficulty":"hard"},
{"q":"Which player won four consecutive NBA titles with the Los Angeles Lakers from 2000-2003?","a":"Shaquille O'Neal","choices":["Shaquille O'Neal","Kobe Bryant","Derek Fisher","Robert Horry"],"sport":"basketball","difficulty":"medium"},
{"q":"Which NBA team plays at the Kaseya Center?","a":"Miami Heat","choices":["Miami Heat","Orlando Magic","Charlotte Hornets","Atlanta Hawks"],"sport":"basketball","difficulty":"medium"},
{"q":"Who holds the record for the most blocks in NBA playoff history?","a":"Hakeem Olajuwon","choices":["Hakeem Olajuwon","David Robinson","Tim Duncan","Patrick Ewing"],"sport":"basketball","difficulty":"hard"},
{"q":"What number did Allen Iverson wear for most of his career with the Philadelphia 76ers?","a":"3","choices":["3","1","11","21"],"sport":"basketball","difficulty":"medium"},
{"q":"Who was the MVP of the 1992 NBA All-Star Game?","a":"Magic Johnson","choices":["Magic Johnson","Michael Jordan","Clyde Drexler","Patrick Ewing"],"sport":"basketball","difficulty":"hard"},
{"q":"Which team drafted Paul Pierce in 1998?","a":"Boston Celtics","choices":["Boston Celtics","Los Angeles Clippers","Seattle SuperSonics","Miami Heat"],"sport":"basketball","difficulty":"medium"},
{"q":"What is the width of the NBA lane (paint) in feet?","a":"16 feet","choices":["16 feet","12 feet","18 feet","14 feet"],"sport":"basketball","difficulty":"hard"},

# ── FOOTBALL continued ──
{"q":"Which team won Super Bowl LIII with a 13-3 score?","a":"New England Patriots","choices":["New England Patriots","Los Angeles Rams","Kansas City Chiefs","Chicago Bears"],"sport":"football","difficulty":"medium"},
{"q":"What quarterback won the most Super Bowls?","a":"Tom Brady (7)","choices":["Tom Brady (7)","Joe Montana (4)","Terry Bradshaw (4)","Roger Staubach (2)"],"sport":"football","difficulty":"easy"},
{"q":"How many seconds are on the play clock in the NFL?","a":"40 seconds","choices":["40 seconds","30 seconds","45 seconds","35 seconds"],"sport":"football","difficulty":"medium"},
{"q":"Which player set the NFL record for most receiving yards in a single season?","a":"Calvin Johnson (1,964 in 2012)","choices":["Calvin Johnson (1,964 in 2012)","Jerry Rice (1,848)","Randy Moss (1,848)","Antonio Brown (1,834)"],"sport":"football","difficulty":"hard"},
{"q":"What city are the Cowboys from?","a":"Dallas","choices":["Dallas","Houston","Austin","San Antonio"],"sport":"football","difficulty":"easy"},
{"q":"Who holds the NFL record for most career receiving yards?","a":"Jerry Rice","choices":["Jerry Rice","Larry Fitzgerald","Tony Gonzalez","Randy Moss"],"sport":"football","difficulty":"medium"},
{"q":"Which team won the first two Super Bowls?","a":"Green Bay Packers","choices":["Green Bay Packers","Dallas Cowboys","Kansas City Chiefs","Minnesota Vikings"],"sport":"football","difficulty":"medium"},
{"q":"What college did Peyton Manning attend?","a":"Tennessee","choices":["Tennessee","Florida","Alabama","Ole Miss"],"sport":"football","difficulty":"medium"},
{"q":"Which NFL team plays home games at Lambeau Field?","a":"Green Bay Packers","choices":["Green Bay Packers","Chicago Bears","Minnesota Vikings","Detroit Lions"],"sport":"football","difficulty":"easy"},
{"q":"Who won the 2020 Super Bowl MVP?","a":"Patrick Mahomes","choices":["Patrick Mahomes","Travis Kelce","Damien Williams","Jimmy Garoppolo"],"sport":"football","difficulty":"medium"},
{"q":"How many points does a two-point conversion score?","a":"2","choices":["2","1","3","4"],"sport":"football","difficulty":"easy"},
{"q":"Which team has appeared in the most Super Bowls?","a":"New England Patriots","choices":["New England Patriots","Denver Broncos","Pittsburgh Steelers","Dallas Cowboys"],"sport":"football","difficulty":"medium"},
{"q":"What is the nickname for the NFL's rushing record held by Emmitt Smith?","a":"The Rushing Record","choices":["The Rushing Record","The Iron Record","The Ground Game Record","The Workhorse Record"],"sport":"football","difficulty":"easy"},
{"q":"Who won the 2019 Super Bowl MVP?","a":"Julian Edelman","choices":["Julian Edelman","Sony Michel","Tom Brady","Rob Gronkowski"],"sport":"football","difficulty":"medium"},
{"q":"Which NFL team plays in Charlotte, North Carolina?","a":"Carolina Panthers","choices":["Carolina Panthers","Atlanta Falcons","Tennessee Titans","Jacksonville Jaguars"],"sport":"football","difficulty":"easy"},
{"q":"Who holds the NFL record for most passing touchdowns in a single season?","a":"Peyton Manning (55 in 2013)","choices":["Peyton Manning (55 in 2013)","Tom Brady (50 in 2007)","Patrick Mahomes (50 in 2018)","Aaron Rodgers (48 in 2011)"],"sport":"football","difficulty":"hard"},
{"q":"Which team drafted Dak Prescott in 2016?","a":"Dallas Cowboys","choices":["Dallas Cowboys","Philadelphia Eagles","New York Giants","Washington Commanders"],"sport":"football","difficulty":"medium"},
{"q":"What is the neutral zone in football?","a":"The space between the two lines of scrimmage the width of the football","choices":["The space between the two lines of scrimmage the width of the football","The midfield area","The area between the hash marks","The space between the numbers on the field"],"sport":"football","difficulty":"medium"},
{"q":"Which receiver caught the most receiving yards in NFL playoff history?","a":"Jerry Rice","choices":["Jerry Rice","Larry Fitzgerald","Julian Edelman","Wes Welker"],"sport":"football","difficulty":"hard"},
{"q":"Who was the first pick in the 2004 NFL Draft?","a":"Eli Manning","choices":["Eli Manning","Philip Rivers","Ben Roethlisberger","Larry Fitzgerald"],"sport":"football","difficulty":"hard"},
{"q":"What team did Odell Beckham Jr. make the famous one-handed catch for?","a":"New York Giants","choices":["New York Giants","Cleveland Browns","Los Angeles Rams","Baltimore Ravens"],"sport":"football","difficulty":"medium"},
{"q":"Which player holds the record for most NFL playoff touchdown passes?","a":"Tom Brady","choices":["Tom Brady","Joe Montana","Peyton Manning","Aaron Rodgers"],"sport":"football","difficulty":"medium"},
{"q":"What is a touchback in football?","a":"When the kicked ball is downed in the end zone resulting in a 25-yard line start","choices":["When the kicked ball is downed in the end zone resulting in a 25-yard line start","A tackle made in the opponent's end zone","When a receiver catches the ball in the end zone and takes a knee","A safety awarded when the punter is tackled in his own end zone"],"sport":"football","difficulty":"medium"},
{"q":"Who coaches the Kansas City Chiefs?","a":"Andy Reid","choices":["Andy Reid","Bill Belichick","Sean McVay","Mike McCarthy"],"sport":"football","difficulty":"easy"},
{"q":"Which team won the 2022 Super Bowl?","a":"Los Angeles Rams","choices":["Los Angeles Rams","Cincinnati Bengals","San Francisco 49ers","Kansas City Chiefs"],"sport":"football","difficulty":"medium"},
{"q":"How many NFL teams are in the NFC?","a":"16","choices":["16","15","17","14"],"sport":"football","difficulty":"easy"},
{"q":"Which player set the all-time NFL record for career punting average?","a":"Shane Lechler","choices":["Shane Lechler","Ray Guy","Sammy Baugh","Jerrel Wilson"],"sport":"football","difficulty":"hard"},
{"q":"What year did the Cleveland Browns last win the NFL Championship?","a":"1964","choices":["1964","1955","1971","1948"],"sport":"football","difficulty":"hard"},
{"q":"Who was the first running back to rush for 2,000 yards in a single season?","a":"O.J. Simpson (1973)","choices":["O.J. Simpson (1973)","Earl Campbell","Barry Sanders","Walter Payton"],"sport":"football","difficulty":"hard"},
{"q":"Which team plays in MetLife Stadium alongside the Giants?","a":"New York Jets","choices":["New York Jets","New England Patriots","Philadelphia Eagles","Baltimore Ravens"],"sport":"football","difficulty":"easy"},

# ── HOCKEY continued ──
{"q":"Who won the Norris Trophy (best defenseman) a record 8 times?","a":"Nicklas Lidstrom","choices":["Nicklas Lidstrom","Bobby Orr","Doug Harvey","Scott Stevens"],"sport":"hockey","difficulty":"hard"},
{"q":"Which team has appeared in the most Stanley Cup Finals?","a":"Montreal Canadiens","choices":["Montreal Canadiens","Toronto Maple Leafs","Detroit Red Wings","Boston Bruins"],"sport":"hockey","difficulty":"hard"},
{"q":"How long is an NHL overtime period in the regular season?","a":"5 minutes","choices":["5 minutes","10 minutes","20 minutes","15 minutes"],"sport":"hockey","difficulty":"medium"},
{"q":"Who was known as 'Mr. Hockey'?","a":"Gordie Howe","choices":["Gordie Howe","Wayne Gretzky","Maurice Richard","Bobby Hull"],"sport":"hockey","difficulty":"medium"},
{"q":"Which team won the Stanley Cup in 2022?","a":"Colorado Avalanche","choices":["Colorado Avalanche","Tampa Bay Lightning","Edmonton Oilers","New York Rangers"],"sport":"hockey","difficulty":"medium"},
{"q":"What is a penalty shot in hockey?","a":"A one-on-one chance against the goalie awarded when a scoring opportunity is illegally broken up","choices":["A one-on-one chance against the goalie awarded when a scoring opportunity is illegally broken up","A free shot after a major penalty","A goal that counts double for the fouled team","A kick taken from the blue line"],"sport":"hockey","difficulty":"medium"},
{"q":"Who scored more points in a single NHL season, Wayne Gretzky or anyone else?","a":"Wayne Gretzky (215 points in 1985-86)","choices":["Wayne Gretzky (215 points in 1985-86)","Mario Lemieux","Mike Bossy","Brett Hull"],"sport":"hockey","difficulty":"hard"},
{"q":"Which city do the Maple Leafs play in?","a":"Toronto","choices":["Toronto","Ottawa","Vancouver","Calgary"],"sport":"hockey","difficulty":"easy"},
{"q":"What is the Masterton Trophy awarded for?","a":"Perseverance and dedication to hockey","choices":["Perseverance and dedication to hockey","Best first-year player","Most improved player","Best sportsmanship"],"sport":"hockey","difficulty":"hard"},
{"q":"Who holds the NHL record for most wins by a goaltender in one season?","a":"Martin Brodeur (48 wins)","choices":["Martin Brodeur (48 wins)","Bernie Parent","Ken Dryden","Patrick Roy"],"sport":"hockey","difficulty":"hard"},
{"q":"Which team did Evgeni Malkin join the NHL with in 2006?","a":"Pittsburgh Penguins","choices":["Pittsburgh Penguins","Detroit Red Wings","Ottawa Senators","Colorado Avalanche"],"sport":"hockey","difficulty":"medium"},
{"q":"What is the blue line in hockey used for?","a":"To determine offsides and divide the ice into zones","choices":["To determine offsides and divide the ice into zones","To mark the crease in front of the net","To show where the referee stands","To indicate where icing begins"],"sport":"hockey","difficulty":"medium"},
{"q":"Who was the first player to score 50 goals in 50 games?","a":"Maurice Richard","choices":["Maurice Richard","Mike Bossy","Wayne Gretzky","Gordie Howe"],"sport":"hockey","difficulty":"hard"},
{"q":"Which franchise relocated to become the Carolina Hurricanes?","a":"Hartford Whalers","choices":["Hartford Whalers","Quebec Nordiques","Minnesota North Stars","Winnipeg Jets (original)"],"sport":"hockey","difficulty":"medium"},
{"q":"In what year did the NHL introduce the shootout for regular season overtime ties?","a":"2005-06 season","choices":["2005-06 season","2000-01 season","2010-11 season","1995-96 season"],"sport":"hockey","difficulty":"hard"},
{"q":"Who holds the NHL record for most career penalty minutes?","a":"Tiger Williams","choices":["Tiger Williams","Dale Hunter","Tie Domi","Bob Probert"],"sport":"hockey","difficulty":"hard"},
{"q":"Which team won the Stanley Cup in 2023?","a":"Vegas Golden Knights","choices":["Vegas Golden Knights","Florida Panthers","Carolina Hurricanes","Dallas Stars"],"sport":"hockey","difficulty":"medium"},
{"q":"What number did Wayne Gretzky wear throughout his career?","a":"99","choices":["99","88","9","11"],"sport":"hockey","difficulty":"easy"},
{"q":"Which goaltender won the most Stanley Cup championships as a player?","a":"Ken Dryden (6)","choices":["Ken Dryden (6)","Jacques Plante","Patrick Roy","Martin Brodeur"],"sport":"hockey","difficulty":"hard"},
{"q":"How many minutes is a minor penalty in the NHL?","a":"2 minutes","choices":["2 minutes","3 minutes","5 minutes","1 minute"],"sport":"hockey","difficulty":"easy"},
{"q":"Which team is known as the Broad Street Bullies from the 1970s?","a":"Philadelphia Flyers","choices":["Philadelphia Flyers","Boston Bruins","New York Rangers","St. Louis Blues"],"sport":"hockey","difficulty":"medium"},
{"q":"Who won the Hart Trophy in 2023?","a":"Connor McDavid","choices":["Connor McDavid","Nathan MacKinnon","Auston Matthews","Leon Draisaitl"],"sport":"hockey","difficulty":"medium"},
{"q":"What city do the Canucks play in?","a":"Vancouver","choices":["Vancouver","Calgary","Edmonton","Victoria"],"sport":"hockey","difficulty":"easy"},
{"q":"Which player was known as 'The Golden Jet'?","a":"Bobby Hull","choices":["Bobby Hull","Bobby Orr","Gordie Howe","Phil Esposito"],"sport":"hockey","difficulty":"medium"},
{"q":"Who was the first defenseman in NHL history to score 100 points in a season?","a":"Bobby Orr","choices":["Bobby Orr","Paul Coffey","Denis Potvin","Ray Bourque"],"sport":"hockey","difficulty":"hard"},
{"q":"What NHL team plays at TD Garden?","a":"Boston Bruins","choices":["Boston Bruins","Montreal Canadiens","New York Rangers","Toronto Maple Leafs"],"sport":"hockey","difficulty":"easy"},
{"q":"How many skaters are in each team during a 4-on-4 overtime in the regular season?","a":"4 skaters plus goalie per team","choices":["4 skaters plus goalie per team","4 skaters no goalie","3 skaters plus goalie","5 skaters no goalie"],"sport":"hockey","difficulty":"medium"},
{"q":"Which team did Brendan Shanahan win two of his three Stanley Cups with?","a":"Detroit Red Wings","choices":["Detroit Red Wings","New Jersey Devils","Hartford Whalers","St. Louis Blues"],"sport":"hockey","difficulty":"hard"},
{"q":"Who won the Calder Trophy in 2019?","a":"Elias Pettersson","choices":["Elias Pettersson","Rasmus Dahlin","Quinn Hughes","Brady Tkachuk"],"sport":"hockey","difficulty":"hard"},
{"q":"What is a power play in hockey?","a":"When one team has more players on the ice due to a penalty","choices":["When one team has more players on the ice due to a penalty","A shot taken from the blue line","A stretch pass up the middle","The last 2 minutes of a period"],"sport":"hockey","difficulty":"easy"},

# ── BASEBALL continued ──
{"q":"Who won the 2024 World Series?","a":"Los Angeles Dodgers","choices":["Los Angeles Dodgers","New York Yankees","Cleveland Guardians","San Diego Padres"],"sport":"baseball","difficulty":"medium"},
{"q":"How many stitches are on a regulation MLB baseball?","a":"108","choices":["108","88","126","96"],"sport":"baseball","difficulty":"hard"},
{"q":"Which pitcher won the Cy Young Award in both the American and National Leagues?","a":"Gaylord Perry","choices":["Gaylord Perry","Pedro Martinez","Roger Clemens","Randy Johnson"],"sport":"baseball","difficulty":"hard"},
{"q":"What does ERA stand for in baseball?","a":"Earned Run Average","choices":["Earned Run Average","Extra Runs Allowed","Estimated Run Average","Error Rate Average"],"sport":"baseball","difficulty":"easy"},
{"q":"Who was the first player to hit 30 home runs and steal 30 bases in the same season?","a":"Ken Williams (1922)","choices":["Ken Williams (1922)","Willie Mays","Bobby Bonds","Eric Davis"],"sport":"baseball","difficulty":"hard"},
{"q":"Which team did Derek Jeter play his entire career with?","a":"New York Yankees","choices":["New York Yankees","Boston Red Sox","Miami Marlins","Los Angeles Dodgers"],"sport":"baseball","difficulty":"easy"},
{"q":"What year did the Houston Astros move from the National League to the American League?","a":"2013","choices":["2013","2011","2015","2010"],"sport":"baseball","difficulty":"hard"},
{"q":"Which position in baseball is often called the hot corner?","a":"Third base","choices":["Third base","First base","Shortstop","Catcher"],"sport":"baseball","difficulty":"medium"},
{"q":"Who won the 2021 World Series?","a":"Atlanta Braves","choices":["Atlanta Braves","Houston Astros","Los Angeles Dodgers","Boston Red Sox"],"sport":"baseball","difficulty":"medium"},
{"q":"What is the infield fly rule?","a":"An automatic out called on a fair fly ball that an infielder can catch with ordinary effort with runners on base","choices":["An automatic out called on a fair fly ball that an infielder can catch with ordinary effort with runners on base","Any fly ball hit to the infield is automatically an out","A rule preventing infielders from catching on purpose then dropping the ball","A popup hit over the pitcher's mound"],"sport":"baseball","difficulty":"medium"},
{"q":"Which pitcher has the most career wins in MLB history?","a":"Cy Young (511)","choices":["Cy Young (511)","Walter Johnson (417)","Christy Mathewson (373)","Grover Alexander (373)"],"sport":"baseball","difficulty":"medium"},
{"q":"How far is it from home plate to first base in MLB?","a":"90 feet","choices":["90 feet","80 feet","100 feet","85 feet"],"sport":"baseball","difficulty":"medium"},
{"q":"Who was the first AL player to win the Triple Crown in batting?","a":"Ty Cobb (1909)","choices":["Ty Cobb (1909)","Babe Ruth","Lou Gehrig","Ted Williams"],"sport":"baseball","difficulty":"hard"},
{"q":"What team plays at Camden Yards?","a":"Baltimore Orioles","choices":["Baltimore Orioles","Washington Nationals","Philadelphia Phillies","New York Mets"],"sport":"baseball","difficulty":"medium"},
{"q":"Who hit 61 home runs in 1961 to break Babe Ruth's single-season record?","a":"Roger Maris","choices":["Roger Maris","Mickey Mantle","Harmon Killebrew","Frank Robinson"],"sport":"baseball","difficulty":"medium"},
{"q":"What is the name of the award for the best pitcher in each league?","a":"Cy Young Award","choices":["Cy Young Award","Walter Johnson Award","Bob Gibson Award","Nolan Ryan Award"],"sport":"baseball","difficulty":"easy"},
{"q":"Which player was nicknamed 'The Big Unit'?","a":"Randy Johnson","choices":["Randy Johnson","Pedro Martinez","Roger Clemens","David Cone"],"sport":"baseball","difficulty":"easy"},
{"q":"How many balls in a row must a pitcher throw for a walk?","a":"4","choices":["4","3","5","6"],"sport":"baseball","difficulty":"easy"},
{"q":"Who won the 2020 World Series (played in a neutral site bubble)?","a":"Los Angeles Dodgers","choices":["Los Angeles Dodgers","Tampa Bay Rays","Houston Astros","Atlanta Braves"],"sport":"baseball","difficulty":"medium"},
{"q":"What is the maximum number of players a team can carry on the expanded MLB roster in September?","a":"28","choices":["28","40","30","25"],"sport":"baseball","difficulty":"hard"},

# ── SOCCER continued ──
{"q":"Who won the FIFA World Cup in 2018?","a":"France","choices":["France","Croatia","Belgium","England"],"sport":"soccer","difficulty":"easy"},
{"q":"Which player has scored the most goals in Champions League history?","a":"Cristiano Ronaldo","choices":["Cristiano Ronaldo","Lionel Messi","Raul","Robert Lewandowski"],"sport":"soccer","difficulty":"medium"},
{"q":"How long is added time typically displayed at the end of each half in soccer?","a":"It varies based on stoppages during the half","choices":["It varies based on stoppages during the half","Always 3 minutes","Always 5 minutes","Always 2 minutes"],"sport":"soccer","difficulty":"medium"},
{"q":"Which club has won the most Serie A titles?","a":"Juventus","choices":["Juventus","AC Milan","Inter Milan","Roma"],"sport":"soccer","difficulty":"medium"},
{"q":"What country did Zlatan Ibrahimovic play for internationally?","a":"Sweden","choices":["Sweden","Norway","Denmark","Bosnia"],"sport":"soccer","difficulty":"easy"},
{"q":"Who managed Manchester City to their treble in 2022-23?","a":"Pep Guardiola","choices":["Pep Guardiola","Jurgen Klopp","Jose Mourinho","Roberto Mancini"],"sport":"soccer","difficulty":"medium"},
{"q":"Which club did Neymar join from Barcelona in 2017?","a":"Paris Saint-Germain","choices":["Paris Saint-Germain","Juventus","Chelsea","Bayern Munich"],"sport":"soccer","difficulty":"easy"},
{"q":"In which year did Brazil last win the FIFA World Cup?","a":"2002","choices":["2002","1994","2010","2006"],"sport":"soccer","difficulty":"medium"},
{"q":"What award is given to the best young player at each World Cup?","a":"Best Young Player award","choices":["Best Young Player award","Golden Boot","Golden Ball","FIFA Fair Play Award"],"sport":"soccer","difficulty":"medium"},
{"q":"Which city is home to both the Nou Camp and Olimpic Lluis Companys stadium?","a":"Barcelona","choices":["Barcelona","Madrid","Valencia","Seville"],"sport":"soccer","difficulty":"medium"},
{"q":"Who won the 2022-23 Premier League title?","a":"Manchester City","choices":["Manchester City","Arsenal","Liverpool","Newcastle United"],"sport":"soccer","difficulty":"medium"},
{"q":"Which nation invented the word soccer?","a":"England","choices":["England","United States","Australia","Canada"],"sport":"soccer","difficulty":"hard"},
{"q":"Who scored the most goals in the 2018 FIFA World Cup?","a":"Harry Kane (6 goals)","choices":["Harry Kane (6 goals)","Kylian Mbappe (4)","Romelu Lukaku (4)","Antoine Griezmann (3)"],"sport":"soccer","difficulty":"medium"},
{"q":"What city do Atletico Madrid play in?","a":"Madrid","choices":["Madrid","Barcelona","Valencia","Seville"],"sport":"soccer","difficulty":"easy"},
{"q":"Which team won the 2022-23 Champions League?","a":"Manchester City","choices":["Manchester City","Inter Milan","Real Madrid","AC Milan"],"sport":"soccer","difficulty":"medium"},
{"q":"Who wore the number 10 jersey for Brazil at the 2022 World Cup?","a":"Neymar","choices":["Neymar","Vinicius Jr","Rodrygo","Richarlison"],"sport":"soccer","difficulty":"easy"},
{"q":"How many minutes does each half of a professional soccer match last?","a":"45 minutes","choices":["45 minutes","40 minutes","50 minutes","35 minutes"],"sport":"soccer","difficulty":"easy"},
{"q":"Which nation's national team is nicknamed 'Die Mannschaft'?","a":"Germany","choices":["Germany","Austria","Switzerland","Netherlands"],"sport":"soccer","difficulty":"medium"},
{"q":"Who managed Liverpool to the Champions League in 2019?","a":"Jurgen Klopp","choices":["Jurgen Klopp","Brendan Rodgers","Rafa Benitez","Steven Gerrard"],"sport":"soccer","difficulty":"medium"},
{"q":"What is the current name of the international team formerly called 'West Germany'?","a":"Germany","choices":["Germany","Central Europe","German Republic","European XI"],"sport":"soccer","difficulty":"easy"},
{"q":"Which player scored a famous 'Hand of God' goal at the 1986 World Cup?","a":"Diego Maradona","choices":["Diego Maradona","Lionel Messi","Carlos Valderrama","Socrates"],"sport":"soccer","difficulty":"medium"},
]

with open('questions.json') as f:
    existing = json.load(f)

existing_set = set(q['q'].strip().lower() for q in existing)
added = [q for q in new_questions if q['q'].strip().lower() not in existing_set]
existing.extend(added)

with open('questions.json', 'w') as f:
    json.dump(existing, f, indent=2)

print(f"Added {len(added)} questions. Total now: {len(existing)}")
