import json

new_questions = [
# ── BASKETBALL ──
{"q":"Which player was nicknamed 'Penny'?","a":"Anfernee Hardaway","choices":["Anfernee Hardaway","Dwyane Wade","Allen Iverson","Stephon Marbury"],"sport":"basketball","difficulty":"medium"},
{"q":"Who won the NBA championship in 2014?","a":"San Antonio Spurs","choices":["San Antonio Spurs","Miami Heat","Oklahoma City Thunder","Indiana Pacers"],"sport":"basketball","difficulty":"medium"},
{"q":"What does PER stand for in basketball analytics?","a":"Player Efficiency Rating","choices":["Player Efficiency Rating","Points Earned Ratio","Performance Evaluation Rating","Player Era Record"],"sport":"basketball","difficulty":"hard"},
{"q":"Which player was the first overall pick in the 1996 NBA Draft?","a":"Allen Iverson","choices":["Allen Iverson","Stephon Marbury","Marcus Camby","Antoine Walker"],"sport":"basketball","difficulty":"medium"},
{"q":"Who was the first player to win six NBA Finals MVP awards?","a":"Michael Jordan","choices":["Michael Jordan","LeBron James","Magic Johnson","Kareem Abdul-Jabbar"],"sport":"basketball","difficulty":"medium"},
{"q":"What team did Gary Payton and Karl Malone join in 2003 in a title attempt?","a":"Los Angeles Lakers","choices":["Los Angeles Lakers","San Antonio Spurs","Miami Heat","Dallas Mavericks"],"sport":"basketball","difficulty":"hard"},
{"q":"Which player was nicknamed 'Big Fundamental'?","a":"Tim Duncan","choices":["Tim Duncan","David Robinson","Hakeem Olajuwon","Kevin Garnett"],"sport":"basketball","difficulty":"medium"},
{"q":"How many teams make the NBA playoffs each year?","a":"16","choices":["16","20","14","12"],"sport":"basketball","difficulty":"easy"},
{"q":"Who won the NBA MVP award in 2022?","a":"Nikola Jokic","choices":["Nikola Jokic","Joel Embiid","Giannis Antetokounmpo","Devin Booker"],"sport":"basketball","difficulty":"medium"},
{"q":"Which player holds the record for most career offensive rebounds?","a":"Moses Malone","choices":["Moses Malone","Dennis Rodman","Dwight Howard","Charles Barkley"],"sport":"basketball","difficulty":"hard"},
{"q":"What position did Magic Johnson play?","a":"Point guard","choices":["Point guard","Shooting guard","Small forward","Power forward"],"sport":"basketball","difficulty":"easy"},
{"q":"Which team did Vince Carter play for when he performed his famous dunks in the 2000 Slam Dunk Contest?","a":"Toronto Raptors","choices":["Toronto Raptors","New Jersey Nets","Orlando Magic","Dallas Mavericks"],"sport":"basketball","difficulty":"medium"},
{"q":"How many regular season games does each NBA team play?","a":"82","choices":["82","80","84","78"],"sport":"basketball","difficulty":"easy"},
{"q":"Which player wore number 34 and was called 'The Round Mound of Rebound'?","a":"Charles Barkley","choices":["Charles Barkley","Karl Malone","Patrick Ewing","Shawn Kemp"],"sport":"basketball","difficulty":"medium"},
{"q":"Who won the 2022 NBA championship?","a":"Golden State Warriors","choices":["Golden State Warriors","Boston Celtics","Miami Heat","Dallas Mavericks"],"sport":"basketball","difficulty":"medium"},
{"q":"Which team drafted Kawhi Leonard in the 2011 NBA Draft?","a":"Indiana Pacers (traded to Spurs on draft night)","choices":["Indiana Pacers (traded to Spurs on draft night)","San Antonio Spurs","Los Angeles Clippers","Utah Jazz"],"sport":"basketball","difficulty":"hard"},
{"q":"What arena do the Houston Rockets play in?","a":"Toyota Center","choices":["Toyota Center","Gainbridge Fieldhouse","American Airlines Center","Ball Arena"],"sport":"basketball","difficulty":"medium"},
{"q":"Who was the first player drafted first overall to win the NBA MVP in his first season?","a":"Blake Griffin (ROY, not MVP)","choices":["No player has done this","Blake Griffin","Andrew Bogut","Kwame Brown"],"sport":"basketball","difficulty":"hard"},
{"q":"Which NBA player scored 8 points in 9 seconds to force overtime in a 2006 game?","a":"Reggie Miller","choices":["Reggie Miller","Allen Iverson","Tracy McGrady","Gilbert Arenas"],"sport":"basketball","difficulty":"hard"},
{"q":"What team drafted Klay Thompson in 2011?","a":"Golden State Warriors","choices":["Golden State Warriors","Sacramento Kings","Minnesota Timberwolves","Indiana Pacers"],"sport":"basketball","difficulty":"medium"},
{"q":"Which player is known as 'The Slim Reaper'?","a":"Kevin Durant","choices":["Kevin Durant","James Harden","Carmelo Anthony","Paul George"],"sport":"basketball","difficulty":"easy"},
{"q":"How many points did Kobe Bryant score in his final NBA game?","a":"60","choices":["60","55","50","65"],"sport":"basketball","difficulty":"medium"},
{"q":"Which team did Ray Allen win his second NBA championship with?","a":"Miami Heat","choices":["Miami Heat","Boston Celtics","Seattle SuperSonics","Milwaukee Bucks"],"sport":"basketball","difficulty":"medium"},
{"q":"What year did the Minnesota Timberwolves last win 60 games in a regular season?","a":"2003-04 (58 wins)","choices":["Never - they've never won 60","2003-04","1999-2000","2021-22"],"sport":"basketball","difficulty":"hard"},
{"q":"Which player won the NBA Sixth Man of the Year award most times?","a":"Jamal Crawford (3 times)","choices":["Jamal Crawford (3 times)","Kevin McHale","Manu Ginobili","Lou Williams"],"sport":"basketball","difficulty":"hard"},
{"q":"Who holds the record for most steals in NBA Finals history?","a":"LeBron James","choices":["LeBron James","Michael Jordan","Magic Johnson","Larry Bird"],"sport":"basketball","difficulty":"hard"},
{"q":"In which arena do the San Antonio Spurs play?","a":"Frost Bank Center","choices":["Frost Bank Center","AT&T Center","SAP Center","Toyota Center"],"sport":"basketball","difficulty":"medium"},
{"q":"What year was the NBA founded?","a":"1946","choices":["1946","1949","1950","1952"],"sport":"basketball","difficulty":"hard"},
{"q":"Which player was selected first overall in the 2011 NBA Draft?","a":"Kyrie Irving","choices":["Kyrie Irving","Derrick Williams","Jonas Valanciunas","Kemba Walker"],"sport":"basketball","difficulty":"medium"},
{"q":"Who won the NBA championship in 2024?","a":"Boston Celtics","choices":["Boston Celtics","Dallas Mavericks","Minnesota Timberwolves","Indiana Pacers"],"sport":"basketball","difficulty":"medium"},

# ── FOOTBALL ──
{"q":"Who won the Super Bowl MVP award in Super Bowl LVIII?","a":"Patrick Mahomes","choices":["Patrick Mahomes","Travis Kelce","Mecole Hardman","Brock Purdy"],"sport":"football","difficulty":"medium"},
{"q":"Which running back rushed for 2,105 yards in the 2012 NFL season?","a":"Adrian Peterson","choices":["Adrian Peterson","Marshawn Lynch","LeSean McCoy","Arian Foster"],"sport":"football","difficulty":"hard"},
{"q":"What city do the Ravens play in?","a":"Baltimore","choices":["Baltimore","Washington","Philadelphia","Cleveland"],"sport":"football","difficulty":"easy"},
{"q":"Who holds the NFL record for most touchdowns in a single game?","a":"Sid Luckman (7 TDs in 1943)","choices":["Sid Luckman (7 TDs in 1943)","Adrian Burk","George Blanda","Y.A. Tittle"],"sport":"football","difficulty":"hard"},
{"q":"Which team won Super Bowl LV?","a":"Tampa Bay Buccaneers","choices":["Tampa Bay Buccaneers","Kansas City Chiefs","San Francisco 49ers","Green Bay Packers"],"sport":"football","difficulty":"medium"},
{"q":"How many yards is a field goal from behind the 40-yard line considered a long field goal?","a":"50+ yards is typically considered long","choices":["50+ yards is typically considered long","40+ yards","55+ yards","45+ yards"],"sport":"football","difficulty":"medium"},
{"q":"Which player won the NFL MVP award four consecutive years from 2011-2014?","a":"Peyton Manning won in 2013; Aaron Rodgers in 2011","choices":["No player won 4 consecutive NFL MVPs","Tom Brady","Peyton Manning","Aaron Rodgers"],"sport":"football","difficulty":"hard"},
{"q":"What team drafted Lamar Jackson in the 2018 NFL Draft?","a":"Baltimore Ravens","choices":["Baltimore Ravens","Kansas City Chiefs","Cleveland Browns","Miami Dolphins"],"sport":"football","difficulty":"easy"},
{"q":"Which coach won Super Bowls with two different teams?","a":"Bill Walsh (49ers only — no one won with 2 teams in the modern era)","choices":["No one in the Super Bowl era","Mike Ditka","Don Shula","Barry Switzer"],"sport":"football","difficulty":"hard"},
{"q":"Who set the NFL record for most rushing touchdowns in a career?","a":"Emmitt Smith (164)","choices":["Emmitt Smith (164)","Marcus Allen","Walter Payton","LaDainian Tomlinson"],"sport":"football","difficulty":"hard"},
{"q":"What college did Aaron Rodgers attend?","a":"UC Berkeley (California)","choices":["UC Berkeley (California)","USC","Oregon","Stanford"],"sport":"football","difficulty":"medium"},
{"q":"Which player is nicknamed 'Beast Mode'?","a":"Marshawn Lynch","choices":["Marshawn Lynch","Adrian Peterson","Le'Veon Bell","Frank Gore"],"sport":"football","difficulty":"easy"},
{"q":"How many NFL teams are there in the AFC North?","a":"4","choices":["4","3","5","6"],"sport":"football","difficulty":"easy"},
{"q":"Who won the Heisman Trophy in 2019?","a":"Joe Burrow","choices":["Joe Burrow","Jalen Hurts","Chase Young","Justin Jefferson"],"sport":"football","difficulty":"medium"},
{"q":"Which team won the 2023 Super Bowl?","a":"Kansas City Chiefs","choices":["Kansas City Chiefs","Philadelphia Eagles","San Francisco 49ers","Dallas Cowboys"],"sport":"football","difficulty":"easy"},
{"q":"What is the nickname of the Pittsburgh Steelers defense from the 1970s?","a":"Steel Curtain","choices":["Steel Curtain","Iron Curtain","Purple People Eaters","Doomsday Defense"],"sport":"football","difficulty":"medium"},
{"q":"Which receiver caught the most touchdowns in a single NFL season?","a":"Randy Moss (23 in 2007)","choices":["Randy Moss (23 in 2007)","Jerry Rice (22 in 1987)","Cris Carter","Mark Clayton"],"sport":"football","difficulty":"hard"},
{"q":"Who was the first pick in the 2023 NFL Draft?","a":"Bryce Young","choices":["Bryce Young","C.J. Stroud","Will Anderson","Anthony Richardson"],"sport":"football","difficulty":"medium"},
{"q":"What city do the 49ers play in?","a":"Santa Clara (home stadium) but represent San Francisco","choices":["Santa Clara (home stadium) but represent San Francisco","San Jose","Oakland","Palo Alto"],"sport":"football","difficulty":"medium"},
{"q":"Who won the 2024 Super Bowl?","a":"Kansas City Chiefs","choices":["Kansas City Chiefs","San Francisco 49ers","Baltimore Ravens","Detroit Lions"],"sport":"football","difficulty":"easy"},
{"q":"Which player holds the NFL record for most career receiving touchdowns?","a":"Jerry Rice (197)","choices":["Jerry Rice (197)","Randy Moss","Terrell Owens","Tony Gonzalez"],"sport":"football","difficulty":"medium"},
{"q":"What is a red zone in football?","a":"The area between the 20-yard line and the opponent's end zone","choices":["The area between the 20-yard line and the opponent's end zone","The area between the 50 and 40-yard lines","Any part of the field in front of the defense","The area within 10 yards of the end zone"],"sport":"football","difficulty":"easy"},
{"q":"Which team drafted Russell Wilson in the 3rd round of the 2012 NFL Draft?","a":"Seattle Seahawks","choices":["Seattle Seahawks","San Francisco 49ers","Denver Broncos","Green Bay Packers"],"sport":"football","difficulty":"medium"},
{"q":"Who won the NFL MVP in 2023?","a":"Lamar Jackson","choices":["Lamar Jackson","Patrick Mahomes","CJ Stroud","Brock Purdy"],"sport":"football","difficulty":"medium"},
{"q":"How long in yards is each end zone in the NFL?","a":"10 yards","choices":["10 yards","5 yards","15 yards","20 yards"],"sport":"football","difficulty":"easy"},
{"q":"Which team won Super Bowl XLVII?","a":"Baltimore Ravens","choices":["Baltimore Ravens","San Francisco 49ers","New Orleans Saints","New England Patriots"],"sport":"football","difficulty":"medium"},
{"q":"Who was the first player to rush for 1,000 yards and receive for 1,000 yards in the same NFL season?","a":"Chuck Foreman (1975)","choices":["Chuck Foreman (1975)","Marshall Faulk","Roger Craig","Herschel Walker"],"sport":"football","difficulty":"hard"},
{"q":"What team drafted Joe Burrow first overall in 2020?","a":"Cincinnati Bengals","choices":["Cincinnati Bengals","Miami Dolphins","Washington Football Team","Los Angeles Chargers"],"sport":"football","difficulty":"easy"},
{"q":"Which defense holds the record for fewest points allowed in a 16-game NFL season?","a":"2000 Baltimore Ravens (165 points)","choices":["2000 Baltimore Ravens (165 points)","1985 Chicago Bears","2002 Tampa Bay Buccaneers","2013 Seattle Seahawks"],"sport":"football","difficulty":"hard"},
{"q":"What is a gunner in NFL special teams?","a":"A player on the kicking team who sprints downfield to tackle the returner","choices":["A player on the kicking team who sprints downfield to tackle the returner","The player who kicks the ball","A blocker on the return team","A long snapper"],"sport":"football","difficulty":"medium"},

# ── HOCKEY ──
{"q":"Which player scored the Stanley Cup-winning overtime goal in 2010 for the Chicago Blackhawks?","a":"Patrick Kane","choices":["Patrick Kane","Jonathan Toews","Duncan Keith","Marian Hossa"],"sport":"hockey","difficulty":"hard"},
{"q":"What city do the Penguins play in?","a":"Pittsburgh","choices":["Pittsburgh","Philadelphia","Baltimore","Cincinnati"],"sport":"hockey","difficulty":"easy"},
{"q":"Who won the Vezina Trophy in 2021?","a":"Marc-Andre Fleury","choices":["Marc-Andre Fleury","Andrei Vasilevskiy","Tuukka Rask","Carey Price"],"sport":"hockey","difficulty":"hard"},
{"q":"Which team won the Stanley Cup in 2024?","a":"Florida Panthers","choices":["Florida Panthers","Edmonton Oilers","New York Rangers","Carolina Hurricanes"],"sport":"hockey","difficulty":"medium"},
{"q":"How many total players including goalie can be on an NHL team's active roster?","a":"23","choices":["23","20","25","22"],"sport":"hockey","difficulty":"hard"},
{"q":"What is a slapshot in hockey?","a":"A shot where the player raises the stick and slaps it forcefully against the puck","choices":["A shot where the player raises the stick and slaps it forcefully against the puck","A shot taken from behind the net","A deflected shot","A one-timer off a pass"],"sport":"hockey","difficulty":"easy"},
{"q":"Who won the Art Ross Trophy (scoring leader) in 2023?","a":"Connor McDavid","choices":["Connor McDavid","Nathan MacKinnon","David Pastrnak","Tage Thompson"],"sport":"hockey","difficulty":"medium"},
{"q":"Which team did Martin Brodeur win all three of his Stanley Cups with?","a":"New Jersey Devils","choices":["New Jersey Devils","Colorado Avalanche","Pittsburgh Penguins","Dallas Stars"],"sport":"hockey","difficulty":"easy"},
{"q":"What is the name of the blue painted area in front of the goal called?","a":"The crease","choices":["The crease","The paint","The box","The zone"],"sport":"hockey","difficulty":"easy"},
{"q":"Which player held the title of NHL's youngest scoring champion?","a":"Wayne Gretzky (19 years old)","choices":["Wayne Gretzky (19 years old)","Sidney Crosby","Mario Lemieux","Eric Lindros"],"sport":"hockey","difficulty":"hard"},
{"q":"What team did Peter Forsberg primarily play for?","a":"Colorado Avalanche","choices":["Colorado Avalanche","Quebec Nordiques","Philadelphia Flyers","Nashville Predators"],"sport":"hockey","difficulty":"medium"},
{"q":"How many NHL teams are in the Western Conference?","a":"16","choices":["16","15","14","17"],"sport":"hockey","difficulty":"medium"},
{"q":"Who scored 50 goals in 50 games twice in his career?","a":"Mike Bossy","choices":["Mike Bossy","Wayne Gretzky","Brett Hull","Mario Lemieux"],"sport":"hockey","difficulty":"hard"},
{"q":"What is the name of the NHL award for the most gentlemanly player?","a":"Lady Byng Trophy","choices":["Lady Byng Trophy","Masterton Trophy","Selke Trophy","King Clancy Memorial Trophy"],"sport":"hockey","difficulty":"medium"},
{"q":"Which team did Jaromir Jagr win his two Stanley Cups with?","a":"Pittsburgh Penguins","choices":["Pittsburgh Penguins","New York Rangers","Washington Capitals","Florida Panthers"],"sport":"hockey","difficulty":"medium"},
{"q":"What year did the Hartford Whalers relocate to Carolina?","a":"1997","choices":["1997","1995","1999","2000"],"sport":"hockey","difficulty":"hard"},
{"q":"Who holds the record for most goals scored in one NHL season?","a":"Wayne Gretzky (92 goals in 1981-82)","choices":["Wayne Gretzky (92 goals in 1981-82)","Mario Lemieux","Brett Hull","Mike Bossy"],"sport":"hockey","difficulty":"hard"},
{"q":"Which city are the Flames from?","a":"Calgary","choices":["Calgary","Edmonton","Toronto","Vancouver"],"sport":"hockey","difficulty":"easy"},
{"q":"What is an empty net goal in hockey?","a":"A goal scored when the opposing team's goalie has been pulled from the net","choices":["A goal scored when the opposing team's goalie has been pulled from the net","A goal scored from outside the blue line","A goal from a deflection off the post","A penalty shot goal"],"sport":"hockey","difficulty":"easy"},
{"q":"Who won back-to-back Stanley Cups with the Pittsburgh Penguins in 2016 and 2017?","a":"Sidney Crosby","choices":["Sidney Crosby","Evgeni Malkin","Phil Kessel","Jake Guentzel"],"sport":"hockey","difficulty":"medium"},
{"q":"What is the Selke Trophy awarded for?","a":"Best defensive forward in the NHL","choices":["Best defensive forward in the NHL","Best penalty killer","Best sportsmanship","Most points by a center"],"sport":"hockey","difficulty":"medium"},
{"q":"Which city do the Wild play in?","a":"Saint Paul, Minnesota","choices":["Saint Paul, Minnesota","Minneapolis","Rochester","Duluth"],"sport":"hockey","difficulty":"medium"},
{"q":"Who wore number 99 in the NHL besides Wayne Gretzky?","a":"No player can wear 99 - it is retired league-wide","choices":["No player can wear 99 - it is retired league-wide","Mario Lemieux","Eric Lindros","Bobby Hull"],"sport":"hockey","difficulty":"medium"},
{"q":"Which player won four consecutive Norris Trophies from 2012 to 2015?","a":"P.K. Subban","choices":["P.K. Subban","Shea Weber","Drew Doughty","Erik Karlsson"],"sport":"hockey","difficulty":"hard"},
{"q":"What city do the Senators play in?","a":"Ottawa","choices":["Ottawa","Toronto","Montreal","Halifax"],"sport":"hockey","difficulty":"easy"},

# ── BASEBALL ──
{"q":"Which team won the 2019 World Series?","a":"Washington Nationals","choices":["Washington Nationals","Houston Astros","New York Yankees","St. Louis Cardinals"],"sport":"baseball","difficulty":"medium"},
{"q":"What does WHIP stand for in baseball?","a":"Walks and Hits per Inning Pitched","choices":["Walks and Hits per Inning Pitched","Wins, Hits, Innings, Pitches","Wild Hits In Play","Weighted Hits Including Pitches"],"sport":"baseball","difficulty":"medium"},
{"q":"Who was known as 'Hammerin Hank'?","a":"Hank Aaron","choices":["Hank Aaron","Harmon Killebrew","Hank Greenberg","Jim Wynn"],"sport":"baseball","difficulty":"easy"},
{"q":"Which position wears a distinctive chest protector and shin guards?","a":"Catcher","choices":["Catcher","Pitcher","First baseman","Umpire"],"sport":"baseball","difficulty":"easy"},
{"q":"Who won the NL MVP award in 2022?","a":"Paul Goldschmidt","choices":["Paul Goldschmidt","Freddie Freeman","Manny Machado","Yordan Alvarez"],"sport":"baseball","difficulty":"hard"},
{"q":"What year did the Houston Astros win their first World Series?","a":"2017","choices":["2017","2019","2005","2015"],"sport":"baseball","difficulty":"medium"},
{"q":"How many outfielders are typically in the field in baseball?","a":"3","choices":["3","2","4","5"],"sport":"baseball","difficulty":"easy"},
{"q":"Which pitcher won the Cy Young Award in 2020 in the shortened season?","a":"Trevin Biagini (AL: Shane Bieber, NL: Trevor Bauer)","choices":["Trevor Bauer (NL), Shane Bieber (AL)","Max Scherzer","Jacob deGrom","Gerrit Cole"],"sport":"baseball","difficulty":"hard"},
{"q":"What is the term for a base runner being put out when a fielder catches a fly ball and the runner fails to return to base in time?","a":"Tagged up rule (force out on fly ball tag-up failure)","choices":["Caught stealing","Tag up rule violation (runner is doubled off)","Infield fly","Balk"],"sport":"baseball","difficulty":"medium"},
{"q":"Who won the 2018 World Series?","a":"Boston Red Sox","choices":["Boston Red Sox","Los Angeles Dodgers","Houston Astros","Cleveland Indians"],"sport":"baseball","difficulty":"medium"},
{"q":"Which player holds the single-season record for strikeouts by a pitcher?","a":"Nolan Ryan (383 in 1973)","choices":["Nolan Ryan (383 in 1973)","Randy Johnson","Sandy Koufax","Sam McDowell"],"sport":"baseball","difficulty":"hard"},
{"q":"What city do the Cardinals play in?","a":"St. Louis","choices":["St. Louis","Louisville","Kansas City","Nashville"],"sport":"baseball","difficulty":"easy"},
{"q":"Who was the first pitcher to win the Cy Young Award unanimously?","a":"Mike McCormick (1967)","choices":["Mike McCormick (1967)","Tom Seaver","Bob Gibson","Sandy Koufax"],"sport":"baseball","difficulty":"hard"},
{"q":"Which team plays at Coors Field, known for its high-scoring games?","a":"Colorado Rockies","choices":["Colorado Rockies","Denver Broncos","Salt Lake Bees","Colorado Springs Sky Sox"],"sport":"baseball","difficulty":"medium"},
{"q":"What is an intentional walk in baseball?","a":"When the catcher signals for four balls to be thrown intentionally to avoid pitching to a batter","choices":["When the catcher signals for four balls to be thrown intentionally to avoid pitching to a batter","When the batter walks to first after being hit by a pitch","A walk during extra innings","A walk with the bases loaded"],"sport":"baseball","difficulty":"easy"},
{"q":"Who won the AL MVP award in 2021?","a":"Shohei Ohtani","choices":["Shohei Ohtani","Vladimir Guerrero Jr.","Marcus Semien","Jose Abreu"],"sport":"baseball","difficulty":"medium"},
{"q":"Which pitcher threw the most no-hitters in a career?","a":"Nolan Ryan (7)","choices":["Nolan Ryan (7)","Sandy Koufax (4)","Bob Feller (3)","Cy Young (3)"],"sport":"baseball","difficulty":"medium"},
{"q":"What year did the Boston Red Sox break their 86-year World Series drought?","a":"2004","choices":["2004","2007","2001","1999"],"sport":"baseball","difficulty":"medium"},
{"q":"Who hit the most home runs in a World Series?","a":"Reggie Jackson (5 in 1977)","choices":["Reggie Jackson (5 in 1977)","Babe Ruth","Mickey Mantle","Duke Snider"],"sport":"baseball","difficulty":"hard"},
{"q":"What is the term for when a pitcher hits the batter with a pitch?","a":"Hit by pitch (HBP)","choices":["Hit by pitch (HBP)","Wild pitch","Dead ball","Intentional bean"],"sport":"baseball","difficulty":"easy"},
{"q":"Which team plays home games at Oracle Park?","a":"San Francisco Giants","choices":["San Francisco Giants","Oakland Athletics","San Jose Giants","Sacramento Kings"],"sport":"baseball","difficulty":"medium"},
{"q":"Who won the 2024 NL MVP?","a":"Shohei Ohtani","choices":["Shohei Ohtani","Freddie Freeman","Mookie Betts","Fernando Tatis Jr."],"sport":"baseball","difficulty":"medium"},
{"q":"What is a squeeze play in baseball?","a":"A bunt attempt with a runner on third to score the runner on the pitch","choices":["A bunt attempt with a runner on third to score the runner on the pitch","A stolen base with two strikes","A slide into home plate","A pickoff attempt to first base"],"sport":"baseball","difficulty":"medium"},
{"q":"How many feet tall is an MLB outfield wall at most parks?","a":"Varies by stadium, but typically 8 to 37 feet","choices":["Varies by stadium, but typically 8 to 37 feet","Always 10 feet","Always 8 feet","Always 12 feet"],"sport":"baseball","difficulty":"hard"},
{"q":"Which player is nicknamed 'The Big Papi'?","a":"David Ortiz","choices":["David Ortiz","Big Hurt Frank Thomas","Prince Fielder","Pablo Sandoval"],"sport":"baseball","difficulty":"easy"},
]

with open('questions.json') as f:
    existing = json.load(f)

existing_set = set(q['q'].strip().lower() for q in existing)
added = [q for q in new_questions if q['q'].strip().lower() not in existing_set]
existing.extend(added)

with open('questions.json', 'w') as f:
    json.dump(existing, f, indent=2)

print(f"Added {len(added)} questions. Total now: {len(existing)}")
