import json, random

new_questions = [
# ── BASKETBALL ──
{"q":"Who holds the NBA record for most points in a single game?","a":"Wilt Chamberlain (100)","choices":["Wilt Chamberlain (100)","Kobe Bryant (81)","David Thompson (73)","Elgin Baylor (71)"],"sport":"basketball","difficulty":"easy"},
{"q":"Which team did Michael Jordan win all six of his NBA championships with?","a":"Chicago Bulls","choices":["Chicago Bulls","Washington Wizards","Detroit Pistons","Boston Celtics"],"sport":"basketball","difficulty":"easy"},
{"q":"Who was the first overall pick in the 2003 NBA Draft?","a":"LeBron James","choices":["LeBron James","Carmelo Anthony","Dwyane Wade","Chris Bosh"],"sport":"basketball","difficulty":"easy"},
{"q":"Which player is known as 'The Greek Freak'?","a":"Giannis Antetokounmpo","choices":["Giannis Antetokounmpo","Nikola Jokic","Luka Doncic","Rudy Gobert"],"sport":"basketball","difficulty":"easy"},
{"q":"How many points is a three-point field goal worth in the NBA?","a":"3","choices":["3","2","4","1"],"sport":"basketball","difficulty":"easy"},
{"q":"Which city do the Lakers play in?","a":"Los Angeles","choices":["Los Angeles","Las Vegas","Louisville","Long Beach"],"sport":"basketball","difficulty":"easy"},
{"q":"Who won the NBA Finals MVP in 2016?","a":"LeBron James","choices":["LeBron James","Kyrie Irving","Kevin Love","Stephen Curry"],"sport":"basketball","difficulty":"medium"},
{"q":"What year did the Golden State Warriors win their first NBA title of the Curry era?","a":"2015","choices":["2015","2016","2017","2014"],"sport":"basketball","difficulty":"medium"},
{"q":"Which player won the NBA MVP award in 2021?","a":"Nikola Jokic","choices":["Nikola Jokic","Joel Embiid","LeBron James","Giannis Antetokounmpo"],"sport":"basketball","difficulty":"medium"},
{"q":"How many NBA championships did Kobe Bryant win?","a":"5","choices":["5","4","6","3"],"sport":"basketball","difficulty":"easy"},
{"q":"Who is the NBA's all-time leading scorer as of 2023?","a":"LeBron James","choices":["LeBron James","Kareem Abdul-Jabbar","Karl Malone","Kobe Bryant"],"sport":"basketball","difficulty":"medium"},
{"q":"Which team drafted Stephen Curry in the 2009 NBA Draft?","a":"Golden State Warriors","choices":["Golden State Warriors","New York Knicks","Minnesota Timberwolves","Oklahoma City Thunder"],"sport":"basketball","difficulty":"medium"},
{"q":"What is the shot clock duration in the NBA?","a":"24 seconds","choices":["24 seconds","30 seconds","20 seconds","35 seconds"],"sport":"basketball","difficulty":"easy"},
{"q":"Which player won the NBA Defensive Player of the Year award four consecutive times from 2015 to 2018?","a":"Draymond Green","choices":["Draymond Green","Rudy Gobert","Kawhi Leonard","Marcus Smart"],"sport":"basketball","difficulty":"hard"},
{"q":"Who coached the San Antonio Spurs to five NBA championships?","a":"Gregg Popovich","choices":["Gregg Popovich","Phil Jackson","Pat Riley","Larry Brown"],"sport":"basketball","difficulty":"easy"},
{"q":"Which NBA team is nicknamed the 'Showtime' Lakers dynasty of the 1980s?","a":"Los Angeles Lakers","choices":["Los Angeles Lakers","Boston Celtics","Philadelphia 76ers","Chicago Bulls"],"sport":"basketball","difficulty":"easy"},
{"q":"Who won the NBA Finals in 2019?","a":"Toronto Raptors","choices":["Toronto Raptors","Golden State Warriors","Milwaukee Bucks","Cleveland Cavaliers"],"sport":"basketball","difficulty":"medium"},
{"q":"How tall is an NBA regulation basketball hoop from the floor?","a":"10 feet","choices":["10 feet","9 feet","11 feet","8 feet"],"sport":"basketball","difficulty":"easy"},
{"q":"Which player won three consecutive NBA Finals MVP awards with the Chicago Bulls in the 1990s?","a":"Michael Jordan","choices":["Michael Jordan","Scottie Pippen","Dennis Rodman","Horace Grant"],"sport":"basketball","difficulty":"medium"},
{"q":"What team did Kevin Durant join in 2016 that caused major controversy?","a":"Golden State Warriors","choices":["Golden State Warriors","Brooklyn Nets","Oklahoma City Thunder","Phoenix Suns"],"sport":"basketball","difficulty":"easy"},
{"q":"Who holds the NBA record for most career assists?","a":"John Stockton","choices":["John Stockton","Magic Johnson","Steve Nash","Chris Paul"],"sport":"basketball","difficulty":"medium"},
{"q":"Which arena did the Chicago Bulls play in during their six-championship run?","a":"United Center","choices":["United Center","Chicago Stadium","Wintrust Arena","Allstate Arena"],"sport":"basketball","difficulty":"medium"},
{"q":"In what year was the NBA three-point line introduced?","a":"1979","choices":["1979","1975","1983","1969"],"sport":"basketball","difficulty":"hard"},
{"q":"Who was the first player to win the NBA MVP and Defensive Player of the Year in the same season?","a":"Hakeem Olajuwon","choices":["Hakeem Olajuwon","David Robinson","Kevin Garnett","Ben Wallace"],"sport":"basketball","difficulty":"hard"},
{"q":"Which team has the most NBA championships in history?","a":"Boston Celtics","choices":["Boston Celtics","Los Angeles Lakers","Chicago Bulls","Golden State Warriors"],"sport":"basketball","difficulty":"medium"},
{"q":"What number did Michael Jordan wear for most of his career?","a":"23","choices":["23","45","33","12"],"sport":"basketball","difficulty":"easy"},
{"q":"Who was the first European-born player to win the NBA MVP award?","a":"Steve Nash","choices":["Steve Nash","Dirk Nowitzki","Giannis Antetokounmpo","Pau Gasol"],"sport":"basketball","difficulty":"hard"},
{"q":"Which player scored 81 points in a single NBA game in 2006?","a":"Kobe Bryant","choices":["Kobe Bryant","LeBron James","Allen Iverson","Vince Carter"],"sport":"basketball","difficulty":"easy"},
{"q":"What is the maximum number of players on an NBA roster?","a":"15","choices":["15","12","17","13"],"sport":"basketball","difficulty":"medium"},
{"q":"Who won back-to-back NBA Finals MVP awards in 2012 and 2013?","a":"LeBron James","choices":["LeBron James","Dwyane Wade","Chris Bosh","Ray Allen"],"sport":"basketball","difficulty":"medium"},
{"q":"Which team drafted Dirk Nowitzki in 1998?","a":"Dallas Mavericks","choices":["Dallas Mavericks","Milwaukee Bucks","San Antonio Spurs","Houston Rockets"],"sport":"basketball","difficulty":"hard"},
{"q":"How many players are on the court per team during an NBA game?","a":"5","choices":["5","6","4","7"],"sport":"basketball","difficulty":"easy"},
{"q":"Who won the NBA Rookie of the Year award in 2004?","a":"LeBron James","choices":["LeBron James","Carmelo Anthony","Dwyane Wade","Chris Bosh"],"sport":"basketball","difficulty":"medium"},
{"q":"Which player was known as 'The Admiral'?","a":"David Robinson","choices":["David Robinson","Patrick Ewing","Hakeem Olajuwon","Alonzo Mourning"],"sport":"basketball","difficulty":"medium"},
{"q":"What year did the Detroit Pistons win back-to-back NBA championships?","a":"2004","choices":["2004","2005","2003","2002"],"sport":"basketball","difficulty":"hard"},
{"q":"Who holds the NBA record for most career three-pointers made?","a":"Stephen Curry","choices":["Stephen Curry","Ray Allen","Reggie Miller","Klay Thompson"],"sport":"basketball","difficulty":"medium"},
{"q":"Which player was nicknamed 'The Mailman'?","a":"Karl Malone","choices":["Karl Malone","John Stockton","Charles Barkley","Patrick Ewing"],"sport":"basketball","difficulty":"easy"},
{"q":"What city do the Celtics play in?","a":"Boston","choices":["Boston","New York","Philadelphia","Chicago"],"sport":"basketball","difficulty":"easy"},
{"q":"Which NBA player was drafted first overall in 2012?","a":"Anthony Davis","choices":["Anthony Davis","Michael Kidd-Gilchrist","Bradley Beal","Damian Lillard"],"sport":"basketball","difficulty":"medium"},
{"q":"Who won the NBA championship in 2023?","a":"Denver Nuggets","choices":["Denver Nuggets","Miami Heat","Boston Celtics","Phoenix Suns"],"sport":"basketball","difficulty":"medium"},
{"q":"Which player is known as 'The Beard'?","a":"James Harden","choices":["James Harden","Kyrie Irving","Russell Westbrook","Paul George"],"sport":"basketball","difficulty":"easy"},
{"q":"What is the diameter of an NBA basketball hoop in inches?","a":"18 inches","choices":["18 inches","20 inches","16 inches","22 inches"],"sport":"basketball","difficulty":"hard"},
{"q":"Who was the first pick in the 1984 NBA Draft?","a":"Hakeem Olajuwon","choices":["Hakeem Olajuwon","Michael Jordan","Charles Barkley","John Stockton"],"sport":"basketball","difficulty":"hard"},
{"q":"How many overtimes were played in the longest NBA game in history?","a":"6","choices":["6","5","7","4"],"sport":"basketball","difficulty":"hard"},
{"q":"Which team did Shaquille O'Neal win his first three NBA titles with?","a":"Los Angeles Lakers","choices":["Los Angeles Lakers","Miami Heat","Orlando Magic","Boston Celtics"],"sport":"basketball","difficulty":"easy"},
{"q":"Who holds the NBA record for most rebounds in a single game?","a":"Wilt Chamberlain (55)","choices":["Wilt Chamberlain (55)","Bill Russell (51)","Nate Thurmond (42)","Jerry Lucas (40)"],"sport":"basketball","difficulty":"hard"},
{"q":"Which player won the first NBA Slam Dunk Contest in 1984?","a":"Larry Nance","choices":["Larry Nance","Dominique Wilkins","Julius Erving","Clyde Drexler"],"sport":"basketball","difficulty":"hard"},
{"q":"What year did LeBron James first win the NBA championship?","a":"2012","choices":["2012","2011","2013","2016"],"sport":"basketball","difficulty":"medium"},
{"q":"Who was the first player to average a triple-double for an entire NBA season?","a":"Oscar Robertson","choices":["Oscar Robertson","Magic Johnson","Russell Westbrook","Jason Kidd"],"sport":"basketball","difficulty":"hard"},
{"q":"Which player wore number 33 for the Boston Celtics and is considered one of the best ever?","a":"Larry Bird","choices":["Larry Bird","Paul Pierce","Kevin McHale","Dennis Johnson"],"sport":"basketball","difficulty":"medium"},
{"q":"What team drafted Kobe Bryant in 1996?","a":"Charlotte Hornets (traded to Lakers)","choices":["Charlotte Hornets (traded to Lakers)","Los Angeles Lakers","Seattle SuperSonics","New Jersey Nets"],"sport":"basketball","difficulty":"hard"},
{"q":"Who won the NBA MVP award in 2004 and 2005?","a":"Steve Nash","choices":["Steve Nash","LeBron James","Shaquille O'Neal","Dirk Nowitzki"],"sport":"basketball","difficulty":"medium"},
{"q":"In what city do the Spurs play?","a":"San Antonio","choices":["San Antonio","Houston","Dallas","Austin"],"sport":"basketball","difficulty":"easy"},
{"q":"Which player is known as 'Luka Magic'?","a":"Luka Doncic","choices":["Luka Doncic","Nikola Jokic","Bogdan Bogdanovic","Goran Dragic"],"sport":"basketball","difficulty":"easy"},
{"q":"Who was the NBA Finals MVP in 2011?","a":"Dirk Nowitzki","choices":["Dirk Nowitzki","LeBron James","Dwyane Wade","Jason Kidd"],"sport":"basketball","difficulty":"medium"},
{"q":"How many rings did Bill Russell win with the Boston Celtics?","a":"11","choices":["11","8","13","10"],"sport":"basketball","difficulty":"medium"},
{"q":"Which player was the first to win three straight NBA MVP awards?","a":"Bill Russell","choices":["Bill Russell","Wilt Chamberlain","Kareem Abdul-Jabbar","Moses Malone"],"sport":"basketball","difficulty":"hard"},
{"q":"What year did the Seattle SuperSonics relocate to Oklahoma City?","a":"2008","choices":["2008","2007","2009","2006"],"sport":"basketball","difficulty":"medium"},
{"q":"Who holds the record for most assists in a single NBA game?","a":"Scott Skiles (30)","choices":["Scott Skiles (30)","Magic Johnson (24)","John Stockton (28)","Kevin Porter (29)"],"sport":"basketball","difficulty":"hard"},
{"q":"Which team drafted Damian Lillard in 2012?","a":"Portland Trail Blazers","choices":["Portland Trail Blazers","Utah Jazz","Indiana Pacers","Sacramento Kings"],"sport":"basketball","difficulty":"medium"},
{"q":"Who was the coach of the 1992 US Olympic Dream Team?","a":"Chuck Daly","choices":["Chuck Daly","Larry Brown","Pat Riley","Don Nelson"],"sport":"basketball","difficulty":"hard"},
{"q":"Which player won the Most Improved Player award in 2019?","a":"Dario Saric","choices":["Dario Saric","De'Aaron Fox","Pascal Siakam","Montrezl Harrell"],"sport":"basketball","difficulty":"hard"},
{"q":"What is the length of the NBA court in feet?","a":"94 feet","choices":["94 feet","90 feet","100 feet","84 feet"],"sport":"basketball","difficulty":"medium"},
{"q":"Who was selected first overall in the 2006 NBA Draft?","a":"Andrea Bargnani","choices":["Andrea Bargnani","LaMarcus Aldridge","Brandon Roy","Rudy Gay"],"sport":"basketball","difficulty":"hard"},

# ── FOOTBALL ──
{"q":"How many points is a touchdown worth in the NFL?","a":"6","choices":["6","7","5","8"],"sport":"football","difficulty":"easy"},
{"q":"Which team has won the most Super Bowls?","a":"New England Patriots","choices":["New England Patriots","Pittsburgh Steelers","San Francisco 49ers","Dallas Cowboys"],"sport":"football","difficulty":"medium"},
{"q":"Who is the NFL's all-time leader in career passing yards?","a":"Tom Brady","choices":["Tom Brady","Peyton Manning","Drew Brees","Brett Favre"],"sport":"football","difficulty":"medium"},
{"q":"What city do the Green Bay Packers play in?","a":"Green Bay","choices":["Green Bay","Milwaukee","Madison","Appleton"],"sport":"football","difficulty":"easy"},
{"q":"Who won the Super Bowl MVP award in Super Bowl LI?","a":"Tom Brady","choices":["Tom Brady","James White","Julian Edelman","Rob Gronkowski"],"sport":"football","difficulty":"medium"},
{"q":"How many players are on the field per team during an NFL game?","a":"11","choices":["11","12","10","9"],"sport":"football","difficulty":"easy"},
{"q":"Which quarterback threw for the most touchdowns in a single NFL season?","a":"Peyton Manning (55 in 2013)","choices":["Peyton Manning (55 in 2013)","Tom Brady (50 in 2007)","Patrick Mahomes (50 in 2018)","Drew Brees (46 in 2011)"],"sport":"football","difficulty":"hard"},
{"q":"What is the name of the trophy awarded to the Super Bowl champion?","a":"Vince Lombardi Trophy","choices":["Vince Lombardi Trophy","George Halas Trophy","Lamar Hunt Trophy","Pete Rozelle Trophy"],"sport":"football","difficulty":"easy"},
{"q":"In what city is the Pro Football Hall of Fame located?","a":"Canton, Ohio","choices":["Canton, Ohio","Green Bay, Wisconsin","Dallas, Texas","Pittsburgh, Pennsylvania"],"sport":"football","difficulty":"medium"},
{"q":"Which player holds the NFL record for most career rushing yards?","a":"Emmitt Smith","choices":["Emmitt Smith","Barry Sanders","Walter Payton","Adrian Peterson"],"sport":"football","difficulty":"medium"},
{"q":"How long is an NFL football field from goal line to goal line in yards?","a":"100 yards","choices":["100 yards","110 yards","90 yards","120 yards"],"sport":"football","difficulty":"easy"},
{"q":"Who was the first quarterback to throw for 5,000 yards in an NFL season?","a":"Dan Marino","choices":["Dan Marino","Dan Fouts","Joe Montana","John Elway"],"sport":"football","difficulty":"hard"},
{"q":"Which team does Patrick Mahomes play for?","a":"Kansas City Chiefs","choices":["Kansas City Chiefs","Dallas Cowboys","Tampa Bay Buccaneers","San Francisco 49ers"],"sport":"football","difficulty":"easy"},
{"q":"How many yards do you need to gain for a first down in the NFL?","a":"10","choices":["10","15","5","8"],"sport":"football","difficulty":"easy"},
{"q":"Who coaches the New England Patriots?","a":"Jerod Mayo","choices":["Jerod Mayo","Bill Belichick","Mike Vrabel","Josh McDaniels"],"sport":"football","difficulty":"medium"},
{"q":"Which receiver caught the 'Immaculate Reception' in 1972?","a":"Franco Harris","choices":["Franco Harris","Lynn Swann","John Stallworth","Terry Bradshaw"],"sport":"football","difficulty":"hard"},
{"q":"Who won Super Bowl MVP in Super Bowl LVII?","a":"Patrick Mahomes","choices":["Patrick Mahomes","Travis Kelce","Jalen Hurts","A.J. Brown"],"sport":"football","difficulty":"medium"},
{"q":"How many points is a safety worth in the NFL?","a":"2","choices":["2","1","3","4"],"sport":"football","difficulty":"easy"},
{"q":"Which team did Jerry Rice win three Super Bowls with?","a":"San Francisco 49ers","choices":["San Francisco 49ers","Oakland Raiders","Dallas Cowboys","Miami Dolphins"],"sport":"football","difficulty":"medium"},
{"q":"Who holds the NFL record for most career touchdown catches?","a":"Jerry Rice","choices":["Jerry Rice","Randy Moss","Cris Carter","Larry Fitzgerald"],"sport":"football","difficulty":"medium"},
{"q":"What year was the first Super Bowl played?","a":"1967","choices":["1967","1965","1969","1971"],"sport":"football","difficulty":"medium"},
{"q":"Which team won Super Bowl XLVIII with a dominant defensive performance?","a":"Seattle Seahawks","choices":["Seattle Seahawks","Denver Broncos","San Francisco 49ers","Carolina Panthers"],"sport":"football","difficulty":"medium"},
{"q":"Who was selected first overall in the 2017 NFL Draft?","a":"Myles Garrett","choices":["Myles Garrett","Mitchell Trubisky","Patrick Mahomes","Deshaun Watson"],"sport":"football","difficulty":"hard"},
{"q":"How many downs does an offense have to gain 10 yards in the NFL?","a":"4","choices":["4","3","5","6"],"sport":"football","difficulty":"easy"},
{"q":"Which defensive player won Super Bowl MVP in Super Bowl XLIV?","a":"Tracy Porter (but Drew Brees won MVP)","choices":["Drew Brees","Tracy Porter","Reggie Bush","Pierre Thomas"],"sport":"football","difficulty":"hard"},
{"q":"What team did Peyton Manning win his second Super Bowl with?","a":"Denver Broncos","choices":["Denver Broncos","Indianapolis Colts","Tennessee Titans","New York Giants"],"sport":"football","difficulty":"medium"},
{"q":"How many points is a field goal worth in the NFL?","a":"3","choices":["3","2","4","1"],"sport":"football","difficulty":"easy"},
{"q":"Who holds the NFL record for most career sacks?","a":"Bruce Smith","choices":["Bruce Smith","Reggie White","Lawrence Taylor","Dwight Freeney"],"sport":"football","difficulty":"hard"},
{"q":"Which college did Joe Montana attend?","a":"Notre Dame","choices":["Notre Dame","Alabama","Ohio State","USC"],"sport":"football","difficulty":"medium"},
{"q":"What is the distance of an extra point kick from the goal post in the NFL (since 2015)?","a":"33 yards","choices":["33 yards","20 yards","25 yards","40 yards"],"sport":"football","difficulty":"hard"},
{"q":"Who won the Heisman Trophy in 2018?","a":"Kyler Murray","choices":["Kyler Murray","Tua Tagovailoa","Joe Burrow","Trevor Lawrence"],"sport":"football","difficulty":"medium"},
{"q":"Which team drafted Tom Brady in the 2000 NFL Draft?","a":"New England Patriots","choices":["New England Patriots","San Francisco 49ers","New York Giants","Cleveland Browns"],"sport":"football","difficulty":"medium"},
{"q":"What round was Tom Brady selected in the 2000 NFL Draft?","a":"6th round","choices":["6th round","4th round","7th round","5th round"],"sport":"football","difficulty":"hard"},
{"q":"Which player is nicknamed 'Megatron'?","a":"Calvin Johnson","choices":["Calvin Johnson","Dez Bryant","A.J. Green","Julio Jones"],"sport":"football","difficulty":"medium"},
{"q":"Who was the starting quarterback for the Philadelphia Eagles in their first Super Bowl win?","a":"Nick Foles","choices":["Nick Foles","Carson Wentz","Donovan McNabb","Michael Vick"],"sport":"football","difficulty":"medium"},
{"q":"How many teams are in the NFL?","a":"32","choices":["32","30","28","34"],"sport":"football","difficulty":"easy"},
{"q":"Which team moved from San Diego to Los Angeles in 2017?","a":"Los Angeles Chargers","choices":["Los Angeles Chargers","Los Angeles Rams","Las Vegas Raiders","Carolina Panthers"],"sport":"football","difficulty":"medium"},
{"q":"Who holds the NFL record for most career interceptions as a defensive player?","a":"Paul Krause","choices":["Paul Krause","Emlen Tunnell","Rod Woodson","Night Train Lane"],"sport":"football","difficulty":"hard"},
{"q":"What is the nickname of the San Francisco 49ers?","a":"The Niners","choices":["The Niners","The Bay","The Gold Rush","The Miners"],"sport":"football","difficulty":"easy"},
{"q":"Which coach has the most NFL wins in regular season history?","a":"Don Shula","choices":["Don Shula","Bill Belichick","George Halas","Tom Landry"],"sport":"football","difficulty":"hard"},
{"q":"What year did the Baltimore Ravens win their first Super Bowl?","a":"2001","choices":["2001","2000","2003","1999"],"sport":"football","difficulty":"medium"},
{"q":"Who quarterbacked the Dallas Cowboys to three Super Bowl wins in the 1990s?","a":"Troy Aikman","choices":["Troy Aikman","Steve Young","Mark Rypien","Jim Kelly"],"sport":"football","difficulty":"medium"},

# ── HOCKEY ──
{"q":"How many periods are in a regulation NHL game?","a":"3","choices":["3","2","4","5"],"sport":"hockey","difficulty":"easy"},
{"q":"Which team has won the most Stanley Cup championships?","a":"Montreal Canadiens","choices":["Montreal Canadiens","Toronto Maple Leafs","Detroit Red Wings","Boston Bruins"],"sport":"hockey","difficulty":"medium"},
{"q":"Who holds the NHL record for most career goals?","a":"Wayne Gretzky","choices":["Wayne Gretzky","Gordie Howe","Jaromir Jagr","Brett Hull"],"sport":"hockey","difficulty":"easy"},
{"q":"What is the diameter of a standard NHL puck in inches?","a":"3 inches","choices":["3 inches","2.5 inches","3.5 inches","4 inches"],"sport":"hockey","difficulty":"hard"},
{"q":"Which goaltender holds the NHL record for most career wins?","a":"Martin Brodeur","choices":["Martin Brodeur","Patrick Roy","Roberto Luongo","Marc-Andre Fleury"],"sport":"hockey","difficulty":"medium"},
{"q":"How wide is an NHL goal in feet?","a":"6 feet","choices":["6 feet","5 feet","7 feet","4 feet"],"sport":"hockey","difficulty":"medium"},
{"q":"Who scored the winning goal for Canada in overtime of the 2010 Olympic gold medal game?","a":"Sidney Crosby","choices":["Sidney Crosby","Jarome Iginla","Joe Thornton","Dany Heatley"],"sport":"hockey","difficulty":"medium"},
{"q":"Which team won the Stanley Cup in 2019?","a":"St. Louis Blues","choices":["St. Louis Blues","Boston Bruins","Tampa Bay Lightning","San Jose Sharks"],"sport":"hockey","difficulty":"medium"},
{"q":"What is Wayne Gretzky's nickname?","a":"The Great One","choices":["The Great One","The Rocket","The Golden Jet","Mr. Hockey"],"sport":"hockey","difficulty":"easy"},
{"q":"Which team does Connor McDavid play for?","a":"Edmonton Oilers","choices":["Edmonton Oilers","Toronto Maple Leafs","Colorado Avalanche","Pittsburgh Penguins"],"sport":"hockey","difficulty":"easy"},
{"q":"How many minutes is a major penalty in the NHL?","a":"5 minutes","choices":["5 minutes","2 minutes","10 minutes","4 minutes"],"sport":"hockey","difficulty":"medium"},
{"q":"Who won the Vezina Trophy (best goaltender) in 2023?","a":"Linus Ullmark","choices":["Linus Ullmark","Ilya Sorokin","Andrei Vasilevskiy","Jake Oettinger"],"sport":"hockey","difficulty":"hard"},
{"q":"Which player was known as 'The Rocket'?","a":"Maurice Richard","choices":["Maurice Richard","Guy Lafleur","Jean Beliveau","Henri Richard"],"sport":"hockey","difficulty":"medium"},
{"q":"What city do the Blackhawks play in?","a":"Chicago","choices":["Chicago","Detroit","Minneapolis","Indianapolis"],"sport":"hockey","difficulty":"easy"},
{"q":"Who won the Hart Trophy (NHL MVP) in 2022?","a":"Auston Matthews","choices":["Auston Matthews","Connor McDavid","Nathan MacKinnon","Leon Draisaitl"],"sport":"hockey","difficulty":"medium"},
{"q":"How many players per team are on the ice at once during regulation play?","a":"6","choices":["6","5","7","4"],"sport":"hockey","difficulty":"easy"},
{"q":"What is the name of the trophy awarded to the NHL playoff MVP?","a":"Conn Smythe Trophy","choices":["Conn Smythe Trophy","Hart Trophy","Vezina Trophy","Art Ross Trophy"],"sport":"hockey","difficulty":"medium"},
{"q":"Which team won the Stanley Cup in 2021?","a":"Tampa Bay Lightning","choices":["Tampa Bay Lightning","Montreal Canadiens","Vegas Golden Knights","New York Islanders"],"sport":"hockey","difficulty":"medium"},
{"q":"Who holds the NHL record for most career points?","a":"Wayne Gretzky","choices":["Wayne Gretzky","Mark Messier","Gordie Howe","Jaromir Jagr"],"sport":"hockey","difficulty":"easy"},
{"q":"What year did the Vegas Golden Knights play their first NHL season?","a":"2017-18","choices":["2017-18","2016-17","2018-19","2015-16"],"sport":"hockey","difficulty":"medium"},
{"q":"Which player was first overall in the 2015 NHL Draft?","a":"Connor McDavid","choices":["Connor McDavid","Jack Eichel","Dylan Strome","Mitch Marner"],"sport":"hockey","difficulty":"medium"},
{"q":"What is the Art Ross Trophy awarded for?","a":"Leading scorer in the regular season","choices":["Leading scorer in the regular season","Best goaltender","Most assists","Playoff scoring leader"],"sport":"hockey","difficulty":"medium"},
{"q":"How long is each period in an NHL game?","a":"20 minutes","choices":["20 minutes","15 minutes","25 minutes","18 minutes"],"sport":"hockey","difficulty":"easy"},
{"q":"Who was the first European-born player to win the Hart Trophy?","a":"Dominik Hasek","choices":["Dominik Hasek","Peter Forsberg","Jaromir Jagr","Nicklas Lidstrom"],"sport":"hockey","difficulty":"hard"},
{"q":"Which NHL team plays at Madison Square Garden?","a":"New York Rangers","choices":["New York Rangers","New York Islanders","New Jersey Devils","New York Americans"],"sport":"hockey","difficulty":"easy"},
{"q":"Who won the Calder Trophy (best rookie) in 2022?","a":"Moritz Seider","choices":["Moritz Seider","Lucas Raymond","Trevor Zegras","Cole Perfetti"],"sport":"hockey","difficulty":"hard"},
{"q":"What is a hat trick in hockey?","a":"Three goals by one player in one game","choices":["Three goals by one player in one game","Three assists in one period","Scoring in three straight games","Three power play goals"],"sport":"hockey","difficulty":"easy"},
{"q":"Which team did Wayne Gretzky play for when he broke most of his records?","a":"Edmonton Oilers","choices":["Edmonton Oilers","Los Angeles Kings","New York Rangers","St. Louis Blues"],"sport":"hockey","difficulty":"easy"},
{"q":"What is icing in hockey?","a":"Shooting the puck from your own half past the opposing goal line without a goal","choices":["Shooting the puck from your own half past the opposing goal line without a goal","A penalty for slashing","A goal scored shorthanded","An illegal check from behind"],"sport":"hockey","difficulty":"medium"},
{"q":"Which team did the Arizona Coyotes relocate to become in 2024?","a":"Utah Hockey Club","choices":["Utah Hockey Club","Houston Aeros","Quebec Nordiques","Hartford Whalers"],"sport":"hockey","difficulty":"hard"},

# ── BASEBALL ──
{"q":"How many strikes does it take to strike out in baseball?","a":"3","choices":["3","4","2","5"],"sport":"baseball","difficulty":"easy"},
{"q":"Which player has the most career home runs in MLB history?","a":"Barry Bonds (762)","choices":["Barry Bonds (762)","Hank Aaron (755)","Babe Ruth (714)","Alex Rodriguez (696)"],"sport":"baseball","difficulty":"medium"},
{"q":"What is the distance from home plate to the pitcher's mound in MLB?","a":"60 feet 6 inches","choices":["60 feet 6 inches","60 feet","65 feet","55 feet"],"sport":"baseball","difficulty":"medium"},
{"q":"Who won the 2022 World Series?","a":"Houston Astros","choices":["Houston Astros","Philadelphia Phillies","New York Yankees","Cleveland Guardians"],"sport":"baseball","difficulty":"medium"},
{"q":"How many innings are in a regulation MLB game?","a":"9","choices":["9","7","11","8"],"sport":"baseball","difficulty":"easy"},
{"q":"Which pitcher holds the MLB record for most career strikeouts?","a":"Nolan Ryan","choices":["Nolan Ryan","Randy Johnson","Roger Clemens","Steve Carlton"],"sport":"baseball","difficulty":"medium"},
{"q":"What team plays at Fenway Park?","a":"Boston Red Sox","choices":["Boston Red Sox","New York Yankees","Baltimore Orioles","Toronto Blue Jays"],"sport":"baseball","difficulty":"easy"},
{"q":"Who hit 70 home runs in the 1998 season?","a":"Mark McGwire","choices":["Mark McGwire","Sammy Sosa","Barry Bonds","Jim Thome"],"sport":"baseball","difficulty":"medium"},
{"q":"What is a perfect game in baseball?","a":"No hits, no walks, no errors, no batters reach base in a complete game","choices":["No hits, no walks, no errors, no batters reach base in a complete game","A shutout with at least 15 strikeouts","Striking out every batter faced","Allowing no runs in 9 innings"],"sport":"baseball","difficulty":"medium"},
{"q":"Which team has won the most World Series titles?","a":"New York Yankees","choices":["New York Yankees","St. Louis Cardinals","Oakland Athletics","Boston Red Sox"],"sport":"baseball","difficulty":"easy"},
{"q":"How many balls does a batter receive before walking in MLB?","a":"4","choices":["4","3","5","6"],"sport":"baseball","difficulty":"easy"},
{"q":"Who was known as 'The Say Hey Kid'?","a":"Willie Mays","choices":["Willie Mays","Mickey Mantle","Duke Snider","Hank Aaron"],"sport":"baseball","difficulty":"medium"},
{"q":"What year did Jackie Robinson break baseball's color barrier?","a":"1947","choices":["1947","1945","1950","1942"],"sport":"baseball","difficulty":"medium"},
{"q":"Which pitcher threw the only perfect game in World Series history?","a":"Don Larsen","choices":["Don Larsen","Sandy Koufax","Bob Gibson","Whitey Ford"],"sport":"baseball","difficulty":"hard"},
{"q":"How many bases are on a baseball diamond?","a":"4","choices":["4","3","5","6"],"sport":"baseball","difficulty":"easy"},
{"q":"Who won the 2023 World Series?","a":"Texas Rangers","choices":["Texas Rangers","Arizona Diamondbacks","Houston Astros","Philadelphia Phillies"],"sport":"baseball","difficulty":"medium"},
{"q":"What is the Golden Glove Award given for in baseball?","a":"Best fielding at each position","choices":["Best fielding at each position","Most home runs","Best batting average","Most wins for a pitcher"],"sport":"baseball","difficulty":"easy"},
{"q":"Which player won the Cy Young Award a record 7 times?","a":"Roger Clemens","choices":["Roger Clemens","Randy Johnson","Greg Maddux","Tom Seaver"],"sport":"baseball","difficulty":"hard"},
{"q":"What MLB team plays home games at Wrigley Field?","a":"Chicago Cubs","choices":["Chicago Cubs","Chicago White Sox","Milwaukee Brewers","Cincinnati Reds"],"sport":"baseball","difficulty":"easy"},
{"q":"Who set the MLB single-season home run record before Barry Bonds in 2001?","a":"Mark McGwire (70 in 1998)","choices":["Mark McGwire (70 in 1998)","Sammy Sosa (66 in 1999)","Roger Maris (61 in 1961)","Babe Ruth (60 in 1927)"],"sport":"baseball","difficulty":"medium"},
{"q":"What city do the Dodgers play in?","a":"Los Angeles","choices":["Los Angeles","Brooklyn","San Diego","Anaheim"],"sport":"baseball","difficulty":"easy"},
{"q":"Who holds the MLB record for most career hits?","a":"Pete Rose","choices":["Pete Rose","Ty Cobb","Hank Aaron","Derek Jeter"],"sport":"baseball","difficulty":"medium"},
{"q":"Which pitcher had a career ERA of 1.82, the lowest in MLB history among pitchers with 300+ wins?","a":"Walter Johnson","choices":["Walter Johnson","Christy Mathewson","Cy Young","Pete Alexander"],"sport":"baseball","difficulty":"hard"},
{"q":"What is the name of the award given to the best hitter in each league?","a":"Silver Slugger Award","choices":["Silver Slugger Award","Hank Aaron Award","Batting Crown","Golden Bat"],"sport":"baseball","difficulty":"medium"},
{"q":"Which team won the 2016 World Series, ending a 108-year drought?","a":"Chicago Cubs","choices":["Chicago Cubs","Cleveland Indians","Chicago White Sox","Boston Red Sox"],"sport":"baseball","difficulty":"medium"},
{"q":"How many players are in the starting lineup in baseball?","a":"9","choices":["9","8","10","7"],"sport":"baseball","difficulty":"easy"},
{"q":"Who was the last player to hit .400 in a MLB season?","a":"Ted Williams (.406 in 1941)","choices":["Ted Williams (.406 in 1941)","Joe DiMaggio (.381 in 1939)","Tony Gwynn (.394 in 1994)","Rod Carew (.388 in 1977)"],"sport":"baseball","difficulty":"hard"},
{"q":"What is a walk-off home run?","a":"A home run that ends the game in the bottom of the last inning","choices":["A home run that ends the game in the bottom of the last inning","A solo home run with 2 outs","A grand slam to take the lead","A pinch-hit home run"],"sport":"baseball","difficulty":"easy"},
{"q":"Which team did Shohei Ohtani join before the 2024 season?","a":"Los Angeles Dodgers","choices":["Los Angeles Dodgers","Los Angeles Angels","New York Yankees","Toronto Blue Jays"],"sport":"baseball","difficulty":"easy"},
{"q":"Who pitched a no-hitter in his final MLB start?","a":"Justin Verlander","choices":["Justin Verlander","Max Scherzer","Clayton Kershaw","Jon Lester"],"sport":"baseball","difficulty":"hard"},

# ── SOCCER ──
{"q":"Which country has won the most FIFA World Cup titles?","a":"Brazil","choices":["Brazil","Germany","Italy","Argentina"],"sport":"soccer","difficulty":"easy"},
{"q":"Who has won the most Ballon d'Or awards in history?","a":"Lionel Messi","choices":["Lionel Messi","Cristiano Ronaldo","Ronaldo Nazario","Johan Cruyff"],"sport":"soccer","difficulty":"easy"},
{"q":"How long is a regulation soccer match?","a":"90 minutes","choices":["90 minutes","80 minutes","100 minutes","120 minutes"],"sport":"soccer","difficulty":"easy"},
{"q":"Which club has won the most UEFA Champions League titles?","a":"Real Madrid","choices":["Real Madrid","AC Milan","Bayern Munich","Barcelona"],"sport":"soccer","difficulty":"medium"},
{"q":"Who scored the winning goal for Argentina in the 2022 World Cup final?","a":"Gonzalo Montiel (penalty)","choices":["Gonzalo Montiel (penalty)","Lionel Messi","Angel Di Maria","Lautaro Martinez"],"sport":"soccer","difficulty":"hard"},
{"q":"What country hosted the 2022 FIFA World Cup?","a":"Qatar","choices":["Qatar","Russia","Brazil","United States"],"sport":"soccer","difficulty":"easy"},
{"q":"Which player is known as 'CR7'?","a":"Cristiano Ronaldo","choices":["Cristiano Ronaldo","Carlos Rexach","Carlo Ancelotti","Claudio Ranieri"],"sport":"soccer","difficulty":"easy"},
{"q":"How many players are on a soccer team on the field at once?","a":"11","choices":["11","10","12","9"],"sport":"soccer","difficulty":"easy"},
{"q":"Which English club plays at Anfield?","a":"Liverpool","choices":["Liverpool","Everton","Manchester City","Manchester United"],"sport":"soccer","difficulty":"easy"},
{"q":"Who won the 2023 UEFA Champions League?","a":"Manchester City","choices":["Manchester City","Inter Milan","Real Madrid","AC Milan"],"sport":"soccer","difficulty":"medium"},
{"q":"What is the maximum number of substitutions allowed in a FIFA World Cup match?","a":"5","choices":["5","3","4","6"],"sport":"soccer","difficulty":"medium"},
{"q":"Which country did Pele play for?","a":"Brazil","choices":["Brazil","Argentina","Portugal","Uruguay"],"sport":"soccer","difficulty":"easy"},
{"q":"Who is the all-time top scorer in FIFA World Cup history?","a":"Miroslav Klose","choices":["Miroslav Klose","Ronaldo Nazario","Gerd Muller","Just Fontaine"],"sport":"soccer","difficulty":"hard"},
{"q":"Which club did Lionel Messi join from Barcelona in 2021?","a":"Paris Saint-Germain","choices":["Paris Saint-Germain","Inter Miami","Manchester City","Juventus"],"sport":"soccer","difficulty":"medium"},
{"q":"What is a brace in soccer?","a":"Two goals scored by the same player in one game","choices":["Two goals scored by the same player in one game","A goal from a free kick","An own goal","Scoring in two consecutive matches"],"sport":"soccer","difficulty":"medium"},
{"q":"Which team won the inaugural Premier League title in 1992-93?","a":"Manchester United","choices":["Manchester United","Arsenal","Blackburn Rovers","Leeds United"],"sport":"soccer","difficulty":"hard"},
{"q":"Who invented the bicycle kick move in soccer?","a":"Leonidas da Silva","choices":["Leonidas da Silva","Pele","Zinedine Zidane","Ramon Unzaga"],"sport":"soccer","difficulty":"hard"},
{"q":"What country won the Euro 2020 (played in 2021) tournament?","a":"Italy","choices":["Italy","England","Spain","Denmark"],"sport":"soccer","difficulty":"medium"},
{"q":"How far is a penalty kick from the goal in soccer?","a":"12 yards","choices":["12 yards","10 yards","15 yards","11 yards"],"sport":"soccer","difficulty":"medium"},
{"q":"Which club has won the most English Premier League titles?","a":"Manchester United","choices":["Manchester United","Arsenal","Chelsea","Manchester City"],"sport":"soccer","difficulty":"medium"},
{"q":"Who is the all-time top scorer in Premier League history?","a":"Alan Shearer","choices":["Alan Shearer","Wayne Rooney","Andrew Cole","Frank Lampard"],"sport":"soccer","difficulty":"hard"},
{"q":"Which nation won the first ever FIFA World Cup in 1930?","a":"Uruguay","choices":["Uruguay","Argentina","Brazil","Italy"],"sport":"soccer","difficulty":"hard"},
{"q":"What does VAR stand for in soccer?","a":"Video Assistant Referee","choices":["Video Assistant Referee","Virtual Assistance Review","Video Analysis Review","Verified Aerial Review"],"sport":"soccer","difficulty":"easy"},
{"q":"Which player scored a hat-trick in the 2018 World Cup final?","a":"Kylian Mbappe","choices":["Kylian Mbappe","Antoine Griezmann","Mario Mandzukic","Paul Pogba"],"sport":"soccer","difficulty":"hard"},
{"q":"In which city is FC Barcelona based?","a":"Barcelona","choices":["Barcelona","Madrid","Valencia","Seville"],"sport":"soccer","difficulty":"easy"},
{"q":"Who won the 2022 FIFA World Cup Golden Boot?","a":"Kylian Mbappe","choices":["Kylian Mbappe","Lionel Messi","Olivier Giroud","Marcus Rashford"],"sport":"soccer","difficulty":"medium"},
{"q":"What is the offside rule in soccer?","a":"A player is offside if they are nearer the opponent's goal line than both the ball and the second-to-last defender when the ball is played","choices":["A player is offside if they are nearer the opponent's goal line than both the ball and the second-to-last defender when the ball is played","A player cannot cross the halfway line before the ball","A player is offside if they are ahead of all defenders","A player must have two feet in the opponent's half"],"sport":"soccer","difficulty":"medium"},

# ── F1 ──
{"q":"Who won the 2023 Formula 1 World Drivers Championship?","a":"Max Verstappen","choices":["Max Verstappen","Lewis Hamilton","Fernando Alonso","Sergio Perez"],"sport":"f1","difficulty":"easy"},
{"q":"Which team has won the most constructors championships in F1 history?","a":"Ferrari","choices":["Ferrari","McLaren","Mercedes","Williams"],"sport":"f1","difficulty":"medium"},
{"q":"How many times did Michael Schumacher win the F1 World Championship?","a":"7","choices":["7","5","6","8"],"sport":"f1","difficulty":"medium"},
{"q":"Which circuit hosts the Monaco Grand Prix?","a":"Circuit de Monaco","choices":["Circuit de Monaco","Spa-Francorchamps","Silverstone","Monza"],"sport":"f1","difficulty":"easy"},
{"q":"Who was the youngest F1 World Champion in history (as of 2023)?","a":"Sebastian Vettel (23 years old in 2010)","choices":["Sebastian Vettel (23 years old in 2010)","Max Verstappen","Fernando Alonso","Mike Hawthorn"],"sport":"f1","difficulty":"hard"},
{"q":"What nationality is Lewis Hamilton?","a":"British","choices":["British","American","Australian","German"],"sport":"f1","difficulty":"easy"},
{"q":"Which Grand Prix is held at Silverstone?","a":"British Grand Prix","choices":["British Grand Prix","European Grand Prix","English Grand Prix","UK Grand Prix"],"sport":"f1","difficulty":"easy"},
{"q":"How many times did Ayrton Senna win the F1 World Championship?","a":"3","choices":["3","4","2","5"],"sport":"f1","difficulty":"medium"},
{"q":"Which team did Max Verstappen drive for when he won his first championship in 2021?","a":"Red Bull Racing","choices":["Red Bull Racing","Toro Rosso","AlphaTauri","Racing Point"],"sport":"f1","difficulty":"easy"},
{"q":"What does DRS stand for in F1?","a":"Drag Reduction System","choices":["Drag Reduction System","Dynamic Racing Speed","Driver Response System","Direct Rear Spoiler"],"sport":"f1","difficulty":"medium"},
{"q":"Which circuit is known as 'The Temple of Speed'?","a":"Monza","choices":["Monza","Spa","Silverstone","Suzuka"],"sport":"f1","difficulty":"medium"},
{"q":"Who won the 2024 F1 World Championship?","a":"Max Verstappen","choices":["Max Verstappen","Lando Norris","Charles Leclerc","Lewis Hamilton"],"sport":"f1","difficulty":"medium"},
{"q":"How many points does an F1 driver get for winning a race?","a":"25","choices":["25","20","30","15"],"sport":"f1","difficulty":"easy"},
{"q":"Which country does Carlos Sainz represent?","a":"Spain","choices":["Spain","Italy","Australia","France"],"sport":"f1","difficulty":"easy"},
{"q":"Who held the record for most F1 race wins before Lewis Hamilton?","a":"Michael Schumacher","choices":["Michael Schumacher","Ayrton Senna","Alain Prost","Nigel Mansell"],"sport":"f1","difficulty":"medium"},

# ── OLYMPICS ──
{"q":"In what year were the first modern Olympic Games held?","a":"1896","choices":["1896","1900","1888","1904"],"sport":"olympics","difficulty":"easy"},
{"q":"Which city hosted the 2020 Summer Olympics (held in 2021)?","a":"Tokyo","choices":["Tokyo","Paris","London","Rio de Janeiro"],"sport":"olympics","difficulty":"easy"},
{"q":"Who won the most Olympic gold medals in history?","a":"Michael Phelps","choices":["Michael Phelps","Larisa Latynina","Usain Bolt","Bjorn Daehlie"],"sport":"olympics","difficulty":"easy"},
{"q":"How often are the Summer Olympics held?","a":"Every 4 years","choices":["Every 4 years","Every 2 years","Every 3 years","Every 5 years"],"sport":"olympics","difficulty":"easy"},
{"q":"Which city will host the 2028 Summer Olympics?","a":"Los Angeles","choices":["Los Angeles","Brisbane","Paris","London"],"sport":"olympics","difficulty":"medium"},
{"q":"Who lit the cauldron at the 1996 Atlanta Olympics?","a":"Muhammad Ali","choices":["Muhammad Ali","Carl Lewis","Michael Jordan","Evander Holyfield"],"sport":"olympics","difficulty":"hard"},
{"q":"How many rings are on the Olympic flag?","a":"5","choices":["5","6","4","7"],"sport":"olympics","difficulty":"easy"},
{"q":"Which country has won the most total Olympic medals in history?","a":"United States","choices":["United States","Soviet Union","China","Great Britain"],"sport":"olympics","difficulty":"easy"},
{"q":"In which city were the 2016 Summer Olympics held?","a":"Rio de Janeiro","choices":["Rio de Janeiro","Sao Paulo","Buenos Aires","Bogota"],"sport":"olympics","difficulty":"easy"},
{"q":"Who won gold in the men's 100m at the 2016 Rio Olympics?","a":"Usain Bolt","choices":["Usain Bolt","Justin Gatlin","Andre De Grasse","Trayvon Bromell"],"sport":"olympics","difficulty":"easy"},
{"q":"What sport did Jesse Owens compete in at the 1936 Berlin Olympics?","a":"Track and field (sprinting/long jump)","choices":["Track and field (sprinting/long jump)","Boxing","Swimming","Gymnastics"],"sport":"olympics","difficulty":"medium"},
{"q":"Which country hosted the 2018 Winter Olympics?","a":"South Korea","choices":["South Korea","Japan","Canada","Norway"],"sport":"olympics","difficulty":"medium"},
{"q":"In which year did women's boxing first appear at the Olympics?","a":"2012","choices":["2012","2008","2016","2004"],"sport":"olympics","difficulty":"hard"},
{"q":"Who won four gold medals at the 1936 Berlin Olympics?","a":"Jesse Owens","choices":["Jesse Owens","Ralph Metcalfe","Luz Long","Mack Robinson"],"sport":"olympics","difficulty":"medium"},
{"q":"Which city hosted the 2024 Summer Olympics?","a":"Paris","choices":["Paris","Los Angeles","Brisbane","Rome"],"sport":"olympics","difficulty":"easy"},
]

with open('questions.json') as f:
    existing = json.load(f)

existing_set = set(q['q'].strip().lower() for q in existing)
added = [q for q in new_questions if q['q'].strip().lower() not in existing_set]
existing.extend(added)

with open('questions.json', 'w') as f:
    json.dump(existing, f, indent=2)

print(f"Added {len(added)} questions. Total now: {len(existing)}")
