import json

new_questions = [
# ── BASKETBALL ──
{"q":"Which franchise won the most consecutive NBA championships?","a":"Boston Celtics (8 from 1959-1966)","choices":["Boston Celtics (8 from 1959-1966)","Los Angeles Lakers (5)","Chicago Bulls (3 twice)","Golden State Warriors (2)"],"sport":"basketball","difficulty":"hard"},
{"q":"Who won the 2020 NBA championship?","a":"Los Angeles Lakers","choices":["Los Angeles Lakers","Miami Heat","Boston Celtics","Denver Nuggets"],"sport":"basketball","difficulty":"medium"},
{"q":"What number did Shaquille O'Neal wear for most of his career?","a":"32","choices":["32","34","33","31"],"sport":"basketball","difficulty":"medium"},
{"q":"Which player won the NBA Most Improved Player award in 2023?","a":"Lauri Markkanen","choices":["Lauri Markkanen","Tyrese Haliburton","Jalen Brunson","Desmond Bane"],"sport":"basketball","difficulty":"hard"},
{"q":"Who is the shortest player to win the NBA MVP award?","a":"Allen Iverson (6 feet tall)","choices":["Allen Iverson (6 feet tall)","Isiah Thomas","Steve Nash","Spud Webb"],"sport":"basketball","difficulty":"hard"},
{"q":"Which team selected Yao Ming first overall in the 2002 NBA Draft?","a":"Houston Rockets","choices":["Houston Rockets","Dallas Mavericks","San Antonio Spurs","Sacramento Kings"],"sport":"basketball","difficulty":"medium"},
{"q":"What is a pick and roll in basketball?","a":"When a player sets a screen for the ball handler then rolls toward the basket","choices":["When a player sets a screen for the ball handler then rolls toward the basket","When a player picks up a loose ball and rolls it to a teammate","A play where two players cross paths to confuse defenders","When a player spins around a defender"],"sport":"basketball","difficulty":"easy"},
{"q":"Which player won the NBA's first Defensive Player of the Year award in 1983?","a":"Sidney Moncrief","choices":["Sidney Moncrief","Dennis Johnson","Michael Cooper","Bobby Jones"],"sport":"basketball","difficulty":"hard"},
{"q":"How many players are inducted into the Hall of Fame from the original Boston Celtics dynasty?","a":"Many - including Bill Russell, Bob Cousy, Sam Jones, Tom Heinsohn","choices":["Many - including Bill Russell, Bob Cousy, Sam Jones, Tom Heinsohn","Only Bill Russell","5 players","2 players"],"sport":"basketball","difficulty":"hard"},
{"q":"Which arena do the Oklahoma City Thunder play in?","a":"Paycom Center","choices":["Paycom Center","Chesapeake Energy Arena","Ford Center","Cox Convention Center"],"sport":"basketball","difficulty":"medium"},
{"q":"Who won the NBA scoring title in 2020?","a":"James Harden","choices":["James Harden","Bradley Beal","Trae Young","LeBron James"],"sport":"basketball","difficulty":"medium"},
{"q":"Which player is known as 'KD'?","a":"Kevin Durant","choices":["Kevin Durant","Kawhi Leonard","Kyle Duncan","Karl-Anthony Towns"],"sport":"basketball","difficulty":"easy"},
{"q":"In what city do the Pistons play?","a":"Detroit","choices":["Detroit","Cleveland","Indianapolis","Columbus"],"sport":"basketball","difficulty":"easy"},
{"q":"Who was the last player to score 70 points in a single NBA game before Donovan Mitchell did it in 2023?","a":"David Thompson scored 73 in 1978","choices":["David Thompson scored 73 in 1978","Michael Jordan scored 69 in 1990","Kobe Bryant scored 81 in 2006","Devin Booker scored 70 in 2017"],"sport":"basketball","difficulty":"hard"},
{"q":"Which team did Paul Pierce play his entire career with before leaving in 2013?","a":"Boston Celtics","choices":["Boston Celtics","Brooklyn Nets","Washington Wizards","Memphis Grizzlies"],"sport":"basketball","difficulty":"medium"},
{"q":"What is the basketball term for passing to a player for an easy score?","a":"Assist","choices":["Assist","Feed","Dish","Setup"],"sport":"basketball","difficulty":"easy"},
{"q":"Who won the NBA Finals MVP in 2020?","a":"LeBron James","choices":["LeBron James","Anthony Davis","Jimmy Butler","Tyler Herro"],"sport":"basketball","difficulty":"medium"},
{"q":"Which player was selected with the 13th pick in the 2005 NBA Draft, considered one of the biggest draft steals?","a":"Andrew Bynum (10th), Danny Granger (17th)","choices":["Andrew Bynum was picked 10th","Manu Ginobili (57th, 1999) is the biggest steal","Andrew Bynum","Deron Williams"],"sport":"basketball","difficulty":"hard"},
{"q":"What year did the ABA merge with the NBA?","a":"1976","choices":["1976","1978","1980","1974"],"sport":"basketball","difficulty":"hard"},
{"q":"Who was the starting point guard for the 2003-04 'Bad Boy' Pistons championship team?","a":"Chauncey Billups","choices":["Chauncey Billups","Richard Hamilton","Lindsey Hunter","Carlos Arroyo"],"sport":"basketball","difficulty":"medium"},
{"q":"Which player holds the record for most consecutive games scoring 10+ points?","a":"Michael Jordan (866 games)","choices":["Michael Jordan (866 games)","LeBron James","Karl Malone","Kareem Abdul-Jabbar"],"sport":"basketball","difficulty":"hard"},
{"q":"What position is primarily responsible for bringing the ball up the court?","a":"Point guard","choices":["Point guard","Shooting guard","Small forward","Center"],"sport":"basketball","difficulty":"easy"},
{"q":"Who won the NBA championship in 2019?","a":"Toronto Raptors","choices":["Toronto Raptors","Golden State Warriors","Milwaukee Bucks","Boston Celtics"],"sport":"basketball","difficulty":"medium"},
{"q":"Which player became the first to score 2,000 points in a rookie season in the modern era?","a":"Wilt Chamberlain","choices":["Wilt Chamberlain","Oscar Robertson","Kareem Abdul-Jabbar","Allen Iverson"],"sport":"basketball","difficulty":"hard"},
{"q":"What city do the Jazz play in?","a":"Salt Lake City","choices":["Salt Lake City","Las Vegas","Denver","Phoenix"],"sport":"basketball","difficulty":"easy"},
{"q":"Who won the NBA MVP in 2020?","a":"Giannis Antetokounmpo","choices":["Giannis Antetokounmpo","LeBron James","James Harden","Kawhi Leonard"],"sport":"basketball","difficulty":"medium"},
{"q":"Which player won the NBA Defensive Player of the Year in 2023?","a":"Brook Lopez","choices":["Brook Lopez","Evan Mobley","Bam Adebayo","Jaren Jackson Jr."],"sport":"basketball","difficulty":"hard"},
{"q":"What is the name of the arena where the Los Angeles Lakers play?","a":"Crypto.com Arena","choices":["Crypto.com Arena","Staples Center","Forum","Inglewood Arena"],"sport":"basketball","difficulty":"medium"},
{"q":"Who was LeBron James's high school team at St. Vincent-St. Mary?","a":"Fighting Irish","choices":["Fighting Irish","Saints","Warriors","Tigers"],"sport":"basketball","difficulty":"hard"},
{"q":"Which player averaged over 50 points per game for an entire NBA season?","a":"Wilt Chamberlain (1961-62, 50.4 ppg)","choices":["Wilt Chamberlain (1961-62, 50.4 ppg)","Michael Jordan","Kobe Bryant","Elgin Baylor"],"sport":"basketball","difficulty":"hard"},

# ── FOOTBALL ──
{"q":"Who was the first pick in the 2018 NFL Draft?","a":"Baker Mayfield","choices":["Baker Mayfield","Saquon Barkley","Bradley Chubb","Quenton Nelson"],"sport":"football","difficulty":"medium"},
{"q":"Which team won Super Bowl XLV?","a":"Green Bay Packers","choices":["Green Bay Packers","Pittsburgh Steelers","New England Patriots","New Orleans Saints"],"sport":"football","difficulty":"medium"},
{"q":"What is a blitz in football?","a":"When defensive backs or linebackers rush the quarterback beyond the normal 4 pass rushers","choices":["When defensive backs or linebackers rush the quarterback beyond the normal 4 pass rushers","A quick screen pass to the outside","A fake punt play","A no-huddle offensive attack"],"sport":"football","difficulty":"easy"},
{"q":"Which NFL player has the most Pro Bowl selections ever?","a":"Tom Brady (15)","choices":["Tom Brady (15)","Peyton Manning (14)","Jerry Rice (13)","Lawrence Taylor (10)"],"sport":"football","difficulty":"hard"},
{"q":"What city do the Eagles play in?","a":"Philadelphia","choices":["Philadelphia","Pittsburgh","Baltimore","Cleveland"],"sport":"football","difficulty":"easy"},
{"q":"Who set the single-season NFL record for rushing yards with 2,105 yards?","a":"Adrian Peterson (2012)","choices":["Adrian Peterson (2012)","Eric Dickerson (1984, 2,105 actually)","Jamal Lewis","Barry Sanders"],"sport":"football","difficulty":"hard"},
{"q":"Which player was nicknamed 'Night Train'?","a":"Dick Lane (Night Train Lane)","choices":["Dick Lane (Night Train Lane)","Deion Sanders","Darrelle Revis","Mel Blount"],"sport":"football","difficulty":"hard"},
{"q":"How many players make up an NFL practice squad?","a":"16 players","choices":["16 players","10 players","12 players","8 players"],"sport":"football","difficulty":"hard"},
{"q":"Who won the 2025 Super Bowl MVP?","a":"Patrick Mahomes","choices":["Patrick Mahomes","Travis Kelce","Xavier Worthy","Mecole Hardman"],"sport":"football","difficulty":"medium"},
{"q":"Which team drafted Aaron Rodgers in the 2005 NFL Draft?","a":"Green Bay Packers","choices":["Green Bay Packers","San Francisco 49ers","San Diego Chargers","Atlanta Falcons"],"sport":"football","difficulty":"medium"},
{"q":"What is the term for a kick that travels through the uprights for 3 points?","a":"Field goal","choices":["Field goal","Gridiron kick","Conversion kick","Power play"],"sport":"football","difficulty":"easy"},
{"q":"Who holds the NFL record for most touchdown passes in a career?","a":"Tom Brady","choices":["Tom Brady","Peyton Manning","Drew Brees","Aaron Rodgers"],"sport":"football","difficulty":"medium"},
{"q":"Which running back holds the NFL record for most yards per carry in a career (minimum 750 carries)?","a":"Jim Brown (5.2 yards per carry)","choices":["Jim Brown (5.2 yards per carry)","Barry Sanders","Adrian Peterson","Gale Sayers"],"sport":"basketball","difficulty":"hard"},
{"q":"In what year was the NFL founded?","a":"1920","choices":["1920","1925","1915","1930"],"sport":"football","difficulty":"medium"},
{"q":"Which team is known as 'America's Team'?","a":"Dallas Cowboys","choices":["Dallas Cowboys","New York Giants","New England Patriots","Green Bay Packers"],"sport":"football","difficulty":"easy"},
{"q":"Who won the Defensive Rookie of the Year award in 2023?","a":"Will Anderson Jr.","choices":["Will Anderson Jr.","Tyree Wilson","Jack Campbell","Devon Witherspoon"],"sport":"football","difficulty":"hard"},
{"q":"What is a fumble in football?","a":"When a player with the ball loses possession before being downed","choices":["When a player with the ball loses possession before being downed","An incomplete pass","An interception by the defense","A backward lateral pass"],"sport":"football","difficulty":"easy"},
{"q":"Which team won Super Bowl LVI?","a":"Los Angeles Rams","choices":["Los Angeles Rams","Cincinnati Bengals","Kansas City Chiefs","Dallas Cowboys"],"sport":"football","difficulty":"medium"},
{"q":"Who was the first running back to win the Heisman Trophy twice?","a":"No running back has won it twice","choices":["No running back has won it twice","Archie Griffin is the only 2-time Heisman winner (QB/RB)","Earl Campbell","Tony Dorsett"],"sport":"football","difficulty":"hard"},
{"q":"What city are the Seahawks from?","a":"Seattle","choices":["Seattle","Portland","Tacoma","Spokane"],"sport":"football","difficulty":"easy"},
{"q":"Which player wore number 80 and was known as 'Hollywood Henderson'?","a":"Thomas Henderson","choices":["Thomas Henderson","Drew Pearson","Tony Hill","Butch Johnson"],"sport":"football","difficulty":"hard"},
{"q":"How many career rushing yards did Walter Payton accumulate?","a":"16,726 yards","choices":["16,726 yards","15,000 yards","18,355 yards","14,500 yards"],"sport":"football","difficulty":"hard"},
{"q":"Who threw the 'Hail Mary' to Roger Staubach in the 1975 playoffs?","a":"Roger Staubach threw it himself to Drew Pearson","choices":["Roger Staubach threw it himself to Drew Pearson","Bob Lilly passed it","Don Meredith","Craig Morton"],"sport":"football","difficulty":"hard"},
{"q":"Which team drafted Odell Beckham Jr. in the 2014 NFL Draft?","a":"New York Giants","choices":["New York Giants","Cleveland Browns","Los Angeles Rams","Baltimore Ravens"],"sport":"football","difficulty":"medium"},
{"q":"What is the NFL term for when the center hikes the ball to the quarterback?","a":"Snap","choices":["Snap","Hike","Center pass","Ball delivery"],"sport":"football","difficulty":"easy"},
{"q":"Who won the 2022 NFL MVP?","a":"Patrick Mahomes","choices":["Patrick Mahomes","Josh Allen","Jalen Hurts","Justin Herbert"],"sport":"football","difficulty":"medium"},
{"q":"Which player was nicknamed 'The Bus'?","a":"Jerome Bettis","choices":["Jerome Bettis","John Riggins","Earl Campbell","Larry Csonka"],"sport":"football","difficulty":"medium"},
{"q":"What team did Brett Favre end his career with?","a":"Minnesota Vikings","choices":["Minnesota Vikings","Green Bay Packers","New York Jets","Atlanta Falcons"],"sport":"football","difficulty":"medium"},
{"q":"How many times did Jim Brown lead the NFL in rushing?","a":"8 times in 9 seasons","choices":["8 times in 9 seasons","9 times","5 times","6 times"],"sport":"football","difficulty":"hard"},
{"q":"Which team plays home games at SoFi Stadium?","a":"Los Angeles Rams and Los Angeles Chargers","choices":["Los Angeles Rams and Los Angeles Chargers","Los Angeles Raiders","Los Angeles Avengers","Los Angeles Chargers only"],"sport":"football","difficulty":"medium"},

# ── HOCKEY ──
{"q":"What does it mean when a goalie records a shutout?","a":"The goalie did not allow any goals in the game","choices":["The goalie did not allow any goals in the game","The goalie made 50+ saves","The goalie stopped a penalty shot","The team won 1-0"],"sport":"hockey","difficulty":"easy"},
{"q":"Who is the only player to score five goals in a Stanley Cup Finals game?","a":"Maurice Richard (1944)","choices":["Maurice Richard (1944)","Wayne Gretzky","Mario Lemieux","Ted Lindsay"],"sport":"hockey","difficulty":"hard"},
{"q":"Which city do the Stars play in?","a":"Dallas","choices":["Dallas","Houston","Denver","Nashville"],"sport":"hockey","difficulty":"easy"},
{"q":"What is a hat trick with three goals scored in a row without any other player scoring called?","a":"A natural hat trick","choices":["A natural hat trick","A perfect hat trick","A pure hat trick","A clean hat trick"],"sport":"hockey","difficulty":"medium"},
{"q":"Which team won the first Stanley Cup in 1893?","a":"Montreal Hockey Club","choices":["Montreal Hockey Club","Ottawa Hockey Club","Toronto Arenas","Quebec Bulldogs"],"sport":"hockey","difficulty":"hard"},
{"q":"Who holds the NHL record for most career playoff goals?","a":"Wayne Gretzky (122)","choices":["Wayne Gretzky (122)","Mark Messier","Claude Lemieux","Jari Kurri"],"sport":"hockey","difficulty":"hard"},
{"q":"What city do the Predators play in?","a":"Nashville","choices":["Nashville","Memphis","Knoxville","Chattanooga"],"sport":"hockey","difficulty":"easy"},
{"q":"Which team was eliminated from the playoffs most years in a row without making it?","a":"Various teams have had long droughts","choices":["Buffalo Sabres at times","Toronto Maple Leafs (had a long drought)","New York Rangers (54-year Cup drought)","San Jose Sharks"],"sport":"hockey","difficulty":"hard"},
{"q":"How many pucks are typically used in one NHL game?","a":"Around 12 pucks","choices":["Around 12 pucks","Just 1","About 30","Exactly 5"],"sport":"hockey","difficulty":"hard"},
{"q":"Which goalie played the most NHL regular season games?","a":"Martin Brodeur (1,266)","choices":["Martin Brodeur (1,266)","Patrick Roy","Roberto Luongo","Marc-Andre Fleury"],"sport":"hockey","difficulty":"hard"},
{"q":"What is the purpose of the red line in hockey?","a":"It is the center line used for two-line pass rules (now mainly icing)","choices":["It is the center line used for two-line pass rules (now mainly icing)","It marks the crease","It is where face-offs occur","It shows where the benches are"],"sport":"hockey","difficulty":"medium"},
{"q":"Who was the first player to score 500 NHL career goals in the fewest games?","a":"Wayne Gretzky","choices":["Wayne Gretzky","Mike Bossy","Brett Hull","Mario Lemieux"],"sport":"hockey","difficulty":"hard"},
{"q":"Which team plays in Scotiabank Arena?","a":"Toronto Maple Leafs","choices":["Toronto Maple Leafs","Ottawa Senators","Montreal Canadiens","Winnipeg Jets"],"sport":"hockey","difficulty":"medium"},
{"q":"What year did the Seattle Kraken play their first NHL season?","a":"2021-22","choices":["2021-22","2020-21","2022-23","2019-20"],"sport":"hockey","difficulty":"medium"},
{"q":"Which player won the Conn Smythe Trophy in 2023?","a":"Adin Hill","choices":["Adin Hill","Mark Stone","Jonathan Marchessault","Alex Pietrangelo"],"sport":"hockey","difficulty":"hard"},
{"q":"What is forechecking in hockey?","a":"Aggressively pursuing the puck in the offensive zone to regain possession","choices":["Aggressively pursuing the puck in the offensive zone to regain possession","Checking an opponent from behind","Blocking shots in front of your own net","A legal hit along the boards"],"sport":"hockey","difficulty":"medium"},
{"q":"Which player is known as 'The Great One' besides Wayne Gretzky?","a":"No one - the nickname belongs exclusively to Wayne Gretzky","choices":["No one - the nickname belongs exclusively to Wayne Gretzky","Mario Lemieux","Gordie Howe","Bobby Orr"],"sport":"hockey","difficulty":"easy"},
{"q":"Who scored the overtime golden goal for Canada at the 2002 Salt Lake City Winter Olympics?","a":"Joe Sakic","choices":["Joe Sakic","Mario Lemieux","Steve Yzerman","Brendan Shanahan"],"sport":"hockey","difficulty":"hard"},
{"q":"What is the term for a goal scored by the same player who was fouled on the penalty shot?","a":"It is just called a penalty shot goal","choices":["It is just called a penalty shot goal","Power play goal","Dagger goal","Mercy goal"],"sport":"hockey","difficulty":"easy"},
{"q":"Which team plays at Bell Centre?","a":"Montreal Canadiens","choices":["Montreal Canadiens","Ottawa Senators","Quebec Nordiques","Montreal Maroons"],"sport":"hockey","difficulty":"medium"},
{"q":"Who holds the record for most shorthanded goals in NHL history?","a":"Wayne Gretzky (73)","choices":["Wayne Gretzky (73)","Mark Messier","Mario Lemieux","Steve Yzerman"],"sport":"hockey","difficulty":"hard"},
{"q":"What is the puck made of in the NHL?","a":"Vulcanized rubber","choices":["Vulcanized rubber","Plastic","Compressed felt","Hard foam"],"sport":"hockey","difficulty":"medium"},
{"q":"Which team is nicknamed the Habs?","a":"Montreal Canadiens","choices":["Montreal Canadiens","Ottawa Senators","Quebec Nordiques","Toronto Maple Leafs"],"sport":"hockey","difficulty":"easy"},
{"q":"Who won the Hart Trophy in 2021?","a":"Connor McDavid","choices":["Connor McDavid","Leon Draisaitl","Auston Matthews","Nathan MacKinnon"],"sport":"hockey","difficulty":"medium"},

# ── BASEBALL ──
{"q":"Which player won back-to-back NL MVP awards in 2021 and 2022?","a":"No player won back-to-back NL MVPs in those years; Bryce Harper won in 2021","choices":["No consecutive NL MVP wins in 2021-22","Bryce Harper","Juan Soto","Paul Goldschmidt"],"sport":"baseball","difficulty":"hard"},
{"q":"What team plays at Minute Maid Park?","a":"Houston Astros","choices":["Houston Astros","Texas Rangers","Kansas City Royals","Minnesota Twins"],"sport":"baseball","difficulty":"medium"},
{"q":"How many balls on the warning track signal the outfield wall is approaching?","a":"The warning track itself is the signal - it's a different texture underfoot","choices":["The warning track itself is the signal - it's a different texture underfoot","There are no balls","A white line","Yellow painted dots"],"sport":"baseball","difficulty":"medium"},
{"q":"Who hit the most home runs in the 1999 season?","a":"Mark McGwire (65)","choices":["Mark McGwire (65)","Sammy Sosa (63)","Barry Bonds (34)","Ken Griffey Jr. (48)"],"sport":"baseball","difficulty":"hard"},
{"q":"What is the term for a baserunner touching all bases and scoring a run?","a":"A run (or run scored)","choices":["A run (or run scored)","A circuit","A full run","A home circuit"],"sport":"baseball","difficulty":"easy"},
{"q":"Which pitcher had the lowest ERA in MLB history (min 200 innings)?","a":"Tim Keefe (0.86 in 1880)","choices":["Tim Keefe (0.86 in 1880)","Dutch Leonard","Mordecai Brown","Walter Johnson"],"sport":"baseball","difficulty":"hard"},
{"q":"What team plays at Globe Life Field?","a":"Texas Rangers","choices":["Texas Rangers","Dallas Cowboys","Houston Astros","Oklahoma City Dodgers"],"sport":"baseball","difficulty":"medium"},
{"q":"Who won the AL Cy Young Award in 2022?","a":"Justin Verlander","choices":["Justin Verlander","Shane McClanahan","Dylan Cease","Gerrit Cole"],"sport":"baseball","difficulty":"medium"},
{"q":"What position is responsible for covering second base on a steal attempt in most situations?","a":"The shortstop or second baseman depending on the situation","choices":["The shortstop or second baseman depending on the situation","Always the shortstop","Always the second baseman","The catcher runs to cover"],"sport":"baseball","difficulty":"medium"},
{"q":"Which player won three consecutive NL MVP awards?","a":"Mike Schmidt (1980, then no consecutive streak)","choices":["No player has won 3 consecutive NL MVPs in the modern era","Barry Bonds won 4 consecutive MVPs 2001-04","Mike Schmidt","Albert Pujols"],"sport":"baseball","difficulty":"hard"},
{"q":"What city do the Mets play in?","a":"New York","choices":["New York","Newark","Brooklyn","Queens standalone"],"sport":"baseball","difficulty":"easy"},
{"q":"Who won the 2015 World Series?","a":"Kansas City Royals","choices":["Kansas City Royals","New York Mets","Toronto Blue Jays","Chicago Cubs"],"sport":"baseball","difficulty":"medium"},
{"q":"Which pitcher is the all-time leader in saves?","a":"Mariano Rivera (652)","choices":["Mariano Rivera (652)","Trevor Hoffman","Lee Smith","Billy Wagner"],"sport":"baseball","difficulty":"medium"},
{"q":"What is the penalty when a pitcher makes an illegal motion with a runner on base?","a":"A balk - each runner advances one base","choices":["A balk - each runner advances one base","The pitch is called a ball","The runner is out","The batter walks"],"sport":"baseball","difficulty":"medium"},
{"q":"How many World Series did the Oakland A's win in a row from 1972-74?","a":"3","choices":["3","2","4","1"],"sport":"baseball","difficulty":"medium"},
{"q":"Who was the first switch-hitter to win the Triple Crown?","a":"Mickey Mantle (1956)","choices":["Mickey Mantle (1956)","Pete Rose","Eddie Murray","Chipper Jones"],"sport":"baseball","difficulty":"hard"},
{"q":"What city do the Tigers play in?","a":"Detroit","choices":["Detroit","Cleveland","Cincinnati","Columbus"],"sport":"baseball","difficulty":"easy"},
{"q":"Which pitcher struck out all 27 batters he faced in an MLB game?","a":"No pitcher has ever struck out all 27 batters in a game","choices":["No pitcher has ever struck out all 27 batters in a game","Nolan Ryan","Kerry Wood","Randy Johnson"],"sport":"baseball","difficulty":"hard"},
{"q":"Who won the 2013 World Series?","a":"Boston Red Sox","choices":["Boston Red Sox","St. Louis Cardinals","Detroit Tigers","Pittsburgh Pirates"],"sport":"baseball","difficulty":"medium"},
{"q":"What is the term for a home run hit with the bases loaded?","a":"Grand slam","choices":["Grand slam","Bases-loaded blast","Power run","Four-run shot"],"sport":"baseball","difficulty":"easy"},
{"q":"Which Yankees outfielder played 2,130 consecutive games to set a then-record?","a":"Lou Gehrig","choices":["Lou Gehrig","Joe DiMaggio","Babe Ruth","Mickey Mantle"],"sport":"baseball","difficulty":"medium"},
{"q":"What year did the Colorado Rockies join the MLB as an expansion team?","a":"1993","choices":["1993","1991","1995","1998"],"sport":"baseball","difficulty":"hard"},
{"q":"Who was the first AL player to hit 400 home runs and steal 400 bases?","a":"Barry Bonds did it in the NL; Alex Rodriguez in AL with 400 HR only","choices":["No AL player has hit 400 HR and stolen 400 bases","Bobby Bonds","Alex Rodriguez","Rickey Henderson"],"sport":"baseball","difficulty":"hard"},
]

with open('questions.json') as f:
    existing = json.load(f)

existing_set = set(q['q'].strip().lower() for q in existing)
added = [q for q in new_questions if q['q'].strip().lower() not in existing_set]
existing.extend(added)

with open('questions.json', 'w') as f:
    json.dump(existing, f, indent=2)

print(f"Added {len(added)} questions. Total now: {len(existing)}")
