#!/usr/bin/env python3
"""Generate 251 hockey + 134 basketball trivia questions and append to questions.json."""

import json
import time
import os
import subprocess

HOCKEY = []
BASKETBALL = []

def h(q, a, c1, c2, c3, diff="medium"):
    HOCKEY.append({"q": q, "a": a, "choices": [a, c1, c2, c3], "sport": "hockey", "difficulty": diff})

def b(q, a, c1, c2, c3, diff="medium"):
    BASKETBALL.append({"q": q, "a": a, "choices": [a, c1, c2, c3], "sport": "basketball", "difficulty": diff})

# ============================================================
# HOCKEY QUESTIONS (251)
# ============================================================

# --- Rules & Basics (1-30) ---
h("What is icing in hockey?", "Shooting the puck from behind center ice past the opposing goal line", "Hitting a player from behind", "Playing with too many men", "Delay of game by flipping puck over glass", "easy")
h("How many players from one team are on the ice during regular play (including the goalie)?", "6", "5", "7", "4", "easy")
h("How long is a standard NHL period?", "20 minutes", "15 minutes", "25 minutes", "30 minutes", "easy")
h("How many periods are in a regulation NHL game?", "3", "2", "4", "5", "easy")
h("What is the diameter of an NHL hockey puck in inches?", "3 inches", "2.5 inches", "3.5 inches", "4 inches", "medium")
h("What is a 'power play' in hockey?", "When one team has more players on ice due to an opponent's penalty", "When a team scores 3 goals in a row", "A special overtime period", "When both goalies are pulled", "easy")
h("What does 'offsides' mean in hockey?", "An attacking player enters the offensive zone before the puck", "A player crosses center ice illegally", "A goalie leaves the crease", "A player uses their hand to pass the puck", "easy")
h("How long is a standard minor penalty in the NHL?", "2 minutes", "5 minutes", "1 minute", "3 minutes", "easy")
h("What is a 'hat trick' in hockey?", "A player scoring 3 goals in one game", "A goalie making 3 consecutive saves", "Winning 3 games in a row", "A player getting 3 assists", "easy")
h("What happens during a shootout in the NHL?", "Each team selects 3 shooters for one-on-one attempts against the goalie", "Teams play 3-on-3 until someone scores", "A coin flip decides the winner", "Teams alternate power plays", "easy")
h("What is a 'Gordie Howe hat trick'?", "A goal, an assist, and a fight in one game", "3 goals in one period", "A hat trick in overtime", "Scoring with a slapshot, wrist shot, and backhand", "medium")
h("In the NHL, how long is overtime during the regular season?", "5 minutes", "10 minutes", "15 minutes", "20 minutes", "easy")
h("How many players per side are on the ice during NHL regular-season overtime?", "3 (plus a goalie)", "4 (plus a goalie)", "5 (plus a goalie)", "2 (plus a goalie)", "medium")
h("What is the standard weight of an NHL puck in ounces?", "6 ounces", "4 ounces", "8 ounces", "10 ounces", "medium")
h("What penalty is assessed for fighting in the NHL?", "5-minute major", "2-minute minor", "10-minute misconduct", "Game misconduct", "medium")
h("What is a 'delayed penalty' in hockey?", "A penalty called but not stopped until the offending team touches the puck", "A penalty served in the next period", "A penalty reviewed by video", "A penalty assessed after the game", "medium")
h("What does 'pulling the goalie' mean?", "Replacing the goalie with an extra skater", "Benching the goalie for poor performance", "The goalie skating past center ice", "A goalie leaving for a line change", "easy")
h("What is the 'crease' in hockey?", "The painted area directly in front of the goal", "The area behind the net", "The center ice circle", "The penalty box", "easy")
h("How wide is an NHL goal in feet?", "6 feet", "5 feet", "7 feet", "4 feet", "medium")
h("How tall is an NHL goal in feet?", "4 feet", "3 feet", "5 feet", "3.5 feet", "medium")
h("What is a 'two-line pass' (formerly illegal in the NHL)?", "A pass from behind one's own blue line that crosses the center red line", "A pass that crosses both blue lines", "A pass from the defensive zone to the offensive zone", "A pass that bounces off two boards", "hard")
h("What year did the NHL eliminate the two-line pass rule?", "2005", "2000", "2010", "1998", "hard")
h("What is 'boarding' in hockey?", "Violently checking a player into the boards", "Standing on the boards during play", "Throwing equipment over the boards", "Tripping a player near the boards", "medium")
h("What is a 'slew foot' in hockey?", "Using your leg to kick an opponent's feet out from behind", "Kicking the puck into the net", "Tripping with a stick", "Skating backward into a player", "medium")
h("In the NHL playoffs, how is overtime handled differently than the regular season?", "Full 20-minute sudden-death periods at 5-on-5", "3-on-3 for 5 minutes then shootout", "10-minute periods at 4-on-4", "Continuous play until someone scores with no stoppages", "medium")
h("What is a 'penalty shot' in hockey?", "A free one-on-one attempt against the goalie after a specific foul", "A shot from center ice", "An extra shot after a power play", "A shot taken during a shootout only", "easy")
h("What does 'five-hole' refer to in hockey?", "The space between a goalie's legs", "The top-right corner of the net", "The fifth faceoff dot", "A five-minute penalty", "medium")
h("What is 'high-sticking' in hockey?", "Hitting an opponent with a stick above the shoulders", "Raising the puck above the glass", "Lifting your stick above the crossbar", "Carrying the puck on your blade above waist height", "easy")
h("What is the trapezoid behind the NHL net used for?", "It restricts where the goalie can play the puck", "It marks the referee's zone", "It indicates the icing line", "It shows the crease extension", "medium")
h("What is a 'wrap-around' in hockey?", "Skating behind the net and attempting to stuff the puck in from the other side", "Passing the puck around the boards", "A hit that sends a player spinning", "A save where the goalie reaches behind", "easy")

# --- Records & Legends (31-70) ---
h("This player holds the NHL record for most career goals with 894. Who is he?", "Wayne Gretzky", "Gordie Howe", "Jaromir Jagr", "Alex Ovechkin", "medium")
h("Who holds the NHL record for most points in a single season with 215?", "Wayne Gretzky", "Mario Lemieux", "Phil Esposito", "Bobby Orr", "medium")
h("Which legendary defenseman scored 'The Goal' while flying through the air in the 1970 Stanley Cup Final?", "Bobby Orr", "Ray Bourque", "Larry Robinson", "Denis Potvin", "medium")
h("Who is the all-time NHL leader in career assists?", "Wayne Gretzky", "Ron Francis", "Mark Messier", "Ray Bourque", "medium")
h("Nicknamed 'Mr. Hockey,' this player played in the NHL across five decades. Who is he?", "Gordie Howe", "Bobby Hull", "Jean Beliveau", "Maurice Richard", "easy")
h("Which goalie holds the record for most career wins in the NHL?", "Martin Brodeur", "Patrick Roy", "Terry Sawchuk", "Ed Belfour", "medium")
h("Who was the first NHL player to score 50 goals in 50 games?", "Maurice 'Rocket' Richard", "Wayne Gretzky", "Mike Bossy", "Bobby Hull", "hard")
h("This Czech-born player is the NHL's all-time leader in points among European-born players. Who is he?", "Jaromir Jagr", "Peter Stastny", "Nicklas Lidstrom", "Alexander Mogilny", "medium")
h("Which player is known as 'The Great One'?", "Wayne Gretzky", "Mario Lemieux", "Bobby Orr", "Gordie Howe", "easy")
h("Who was nicknamed 'Super Mario' in the NHL?", "Mario Lemieux", "Wayne Gretzky", "Patrick Roy", "Steve Yzerman", "easy")
h("Which goalie popularized the butterfly style and won 4 Vezina Trophies?", "Patrick Roy", "Martin Brodeur", "Dominik Hasek", "Grant Fuhr", "medium")
h("Dominik Hasek was known by what nickname?", "The Dominator", "The Wall", "The Cat", "The Mask", "easy")
h("Which Swedish defenseman won 4 Stanley Cups with Detroit and is considered the greatest European-born NHL player?", "Nicklas Lidstrom", "Borje Salming", "Erik Karlsson", "Victor Hedman", "medium")
h("Who scored the 'Golden Goal' for Canada in the 2010 Olympic men's hockey final?", "Sidney Crosby", "Jarome Iginla", "Ryan Getzlaf", "Jonathan Toews", "easy")
h("Which player holds the record for most goals in a single NHL season with 92?", "Wayne Gretzky", "Mario Lemieux", "Brett Hull", "Alexander Ovechkin", "medium")
h("This bruising forward was known as 'The Power Forward' and wore #88 for the Penguins before Lindros. Who captained the 2009-2017 dynasty Penguins?", "Sidney Crosby", "Evgeni Malkin", "Mario Lemieux", "Jaromir Jagr", "easy")
h("Which player was the first overall pick in 2005 and has been called 'Sid the Kid'?", "Sidney Crosby", "Alexander Ovechkin", "Patrick Kane", "Steven Stamkos", "easy")
h("Who holds the NHL record for most career shutouts by a goaltender?", "Martin Brodeur", "Terry Sawchuk", "Patrick Roy", "George Hainsworth", "medium")
h("This Russian winger joined the Capitals in 2005 and became their all-time leading scorer. Who is he?", "Alexander Ovechkin", "Evgeni Malkin", "Ilya Kovalchuk", "Pavel Bure", "easy")
h("Which player was nicknamed 'The Russian Rocket' for his blazing speed?", "Pavel Bure", "Alexander Ovechkin", "Sergei Fedorov", "Ilya Kovalchuk", "medium")
h("Who is the youngest player to reach 500 career NHL goals?", "Wayne Gretzky", "Mario Lemieux", "Mike Bossy", "Jimmy Carson", "hard")
h("Which enforcer-turned-broadcaster was known as 'Tie' and played for the Maple Leafs among other teams?", "Tie Domi", "Bob Probert", "Donald Brashear", "Chris Nilan", "medium")
h("Mark Messier guaranteed a win in Game 6 of the 1994 Eastern Conference Finals, then delivered. Which team did the Rangers beat?", "New Jersey Devils", "Philadelphia Flyers", "Washington Capitals", "Pittsburgh Penguins", "hard")
h("Which player scored the overtime goal to give the Rangers their first Stanley Cup in 54 years in 1994?", "Mark Messier (series) / Stephane Matteau (ECF OT) — the Cup-clincher was Game 7 vs. Vancouver", "Brian Leetch", "Adam Graves", "Mike Richter", "hard")
h("Ray Bourque finally won his only Stanley Cup in 2001 with which team?", "Colorado Avalanche", "Boston Bruins", "Detroit Red Wings", "New Jersey Devils", "medium")
h("Which goaltender was nicknamed 'The King' and spent his entire career with the New York Rangers?", "Henrik Lundqvist", "Mike Richter", "Ed Giacomin", "John Vanbiesbrouck", "easy")
h("Connor McDavid was drafted first overall in 2015 by which team?", "Edmonton Oilers", "Buffalo Sabres", "Toronto Maple Leafs", "Arizona Coyotes", "easy")
h("Which player is known as 'Captain Serious' for his intense demeanor?", "Jonathan Toews", "Sidney Crosby", "Patrice Bergeron", "Anze Kopitar", "medium")
h("This Finnish goalie was known as 'Kipper' and starred for the Calgary Flames. Who is he?", "Miikka Kiprusoff", "Pekka Rinne", "Tuukka Rask", "Kari Lehtonen", "medium")
h("Who was known as 'The Flower' and played for the Penguins and Canadiens?", "Guy Lafleur", "Marc-Andre Fleury", "Mario Lemieux", "Jean Beliveau", "hard")
h("Marc-Andre Fleury also earned the 'Flower' nickname. Which team drafted him first overall in 2003?", "Pittsburgh Penguins", "Montreal Canadiens", "Vegas Golden Knights", "Chicago Blackhawks", "medium")
h("Which defenseman, known for his booming slap shot, held the hardest shot record at the All-Star skills competition for years?", "Zdeno Chara", "Al MacInnis", "Shea Weber", "Al Iafrate", "medium")
h("Who was the first goalie to score a goal by shooting the puck into the opposing net in an NHL game?", "Ron Hextall", "Martin Brodeur", "Patrick Roy", "Billy Smith", "hard")
h("This player was known as 'The Finnish Flash' and starred for the Mighty Ducks of Anaheim. Who is he?", "Teemu Selanne", "Saku Koivu", "Jari Kurri", "Olli Jokinen", "medium")
h("Teemu Selanne set the rookie goal-scoring record with how many goals?", "76", "53", "66", "82", "hard")
h("Which player was called 'The Moose' and was a fan-favorite goalie for the Vancouver Canucks?", "Kirk McLean", "Roberto Luongo", "Ryan Miller", "Eddie Lack", "hard")
h("Who scored 'The Shift' — a legendary 2010 playoff shift where he dominated possession for over a minute — for the Blackhawks?", "Jonathan Toews", "Patrick Kane", "Marian Hossa", "Duncan Keith", "hard")
h("Which Hall of Fame center was known as 'Stevie Y' and captained the Red Wings to 3 Cups?", "Steve Yzerman", "Sergei Fedorov", "Igor Larionov", "Brendan Shanahan", "easy")
h("Who was the first Black player to play in the NHL?", "Willie O'Ree", "Grant Fuhr", "Jarome Iginla", "Tony McKegney", "medium")
h("In what year did Willie O'Ree break the NHL's color barrier?", "1958", "1950", "1962", "1965", "hard")

# --- Teams & Franchises (71-110) ---
h("Which NHL franchise has the most Stanley Cup championships?", "Montreal Canadiens", "Toronto Maple Leafs", "Detroit Red Wings", "Boston Bruins", "easy")
h("How many Stanley Cups have the Montreal Canadiens won?", "24", "22", "20", "26", "medium")
h("Which Original Six team plays at Madison Square Garden?", "New York Rangers", "Boston Bruins", "Chicago Blackhawks", "Detroit Red Wings", "easy")
h("What are the names of all six 'Original Six' NHL teams?", "Canadiens, Maple Leafs, Red Wings, Bruins, Rangers, Blackhawks", "Canadiens, Maple Leafs, Red Wings, Bruins, Rangers, Flyers", "Canadiens, Maple Leafs, Senators, Bruins, Rangers, Blackhawks", "Canadiens, Maple Leafs, Red Wings, Bruins, Islanders, Blackhawks", "medium")
h("The Vegas Golden Knights made the Stanley Cup Final in their inaugural season. What year was that?", "2018", "2017", "2019", "2020", "medium")
h("Which team ended a 49-year Cup drought in 2019?", "St. Louis Blues", "Washington Capitals", "Toronto Maple Leafs", "Vancouver Canucks", "medium")
h("The 'Broad Street Bullies' was the nickname for which team in the 1970s?", "Philadelphia Flyers", "New York Rangers", "Boston Bruins", "Pittsburgh Penguins", "medium")
h("Which team's arena is nicknamed 'The Madhouse on Madison'?", "Chicago Blackhawks (United Center)", "New York Rangers (MSG)", "Detroit Red Wings (LCA)", "Boston Bruins (TD Garden)", "medium")
h("The Edmonton Oilers dynasty of the 1980s won how many Stanley Cups?", "5", "4", "6", "3", "medium")
h("Which team relocated from Hartford to become the Carolina Hurricanes?", "Hartford Whalers", "Quebec Nordiques", "Minnesota North Stars", "Winnipeg Jets", "medium")
h("The Quebec Nordiques relocated in 1995 to become which franchise?", "Colorado Avalanche", "Arizona Coyotes", "Carolina Hurricanes", "Nashville Predators", "medium")
h("Which team's famous fight song includes the lyrics 'Chelsea Dagger'?", "Chicago Blackhawks", "Boston Bruins", "Philadelphia Flyers", "Detroit Red Wings", "easy")
h("What is the name of the Detroit Red Wings' iconic octopus-throwing tradition?", "The Legend of the Octopus", "The Tentacle Toss", "The Eight-Arm Salute", "The Octopi Shower", "medium")
h("Why do Detroit fans throw octopi on the ice?", "The 8 tentacles originally represented the 8 wins needed to win the Cup", "It was a dare from a local fishmonger", "A player once caught an octopus during warmups", "It started as a protest against referees", "hard")
h("Which Canadian team has the longest active Stanley Cup drought among all Canadian franchises?", "Toronto Maple Leafs (since 1967)", "Vancouver Canucks (never won)", "Ottawa Senators (modern era, never won)", "Winnipeg Jets (never won)", "medium")
h("The 'Miracle on Ice' in 1980 saw which country upset the Soviet Union?", "United States", "Canada", "Finland", "Sweden", "easy")
h("Where was the 1980 Miracle on Ice played?", "Lake Placid, New York", "Calgary, Alberta", "Innsbruck, Austria", "Sarajevo, Yugoslavia", "medium")
h("Which team drafted Sidney Crosby with the first overall pick after a lockout-era lottery?", "Pittsburgh Penguins", "Washington Capitals", "Philadelphia Flyers", "Columbus Blue Jackets", "easy")
h("The 'Trade of the Century' in 1988 sent Wayne Gretzky from Edmonton to which team?", "Los Angeles Kings", "New York Rangers", "St. Louis Blues", "Detroit Red Wings", "easy")
h("Which expansion team won the Stanley Cup in their sixth season in 2023?", "Vegas Golden Knights", "Seattle Kraken", "Florida Panthers", "Nashville Predators", "medium")
h("What mascot do the San Jose Sharks have?", "S.J. Sharkie", "Finn", "Jaws", "Chomper", "medium")
h("The Florida Panthers reached the Stanley Cup Final in 1996 in just their third season. Who swept them?", "Colorado Avalanche", "Detroit Red Wings", "New Jersey Devils", "Pittsburgh Penguins", "hard")
h("Which team is famous for their 'Storm Surge' post-win celebrations?", "Carolina Hurricanes", "Tampa Bay Lightning", "Florida Panthers", "Seattle Kraken", "medium")
h("What is the name of the Boston Bruins' bear mascot?", "Blades", "Bruno", "Bruiser", "Benny", "medium")
h("Which team plays home games at Scotiabank Arena?", "Toronto Maple Leafs", "Ottawa Senators", "Montreal Canadiens", "Winnipeg Jets", "easy")
h("The 'Battle of Alberta' is a rivalry between which two teams?", "Edmonton Oilers and Calgary Flames", "Vancouver Canucks and Calgary Flames", "Winnipeg Jets and Edmonton Oilers", "Toronto Maple Leafs and Ottawa Senators", "easy")
h("Which team was known as the 'Legion of Doom' line in the 1990s?", "Philadelphia Flyers", "Detroit Red Wings", "New Jersey Devils", "Pittsburgh Penguins", "hard")
h("The 'Russian Five' — Fedorov, Larionov, Kozlov, Konstantinov, Fetisov — played for which team?", "Detroit Red Wings", "Pittsburgh Penguins", "New York Rangers", "San Jose Sharks", "medium")
h("Which team employed the neutral-zone trap to great success in the mid-1990s?", "New Jersey Devils", "Detroit Red Wings", "Colorado Avalanche", "Dallas Stars", "medium")
h("Jaromir Jagr's iconic mullet was sported while he played primarily for which team?", "Pittsburgh Penguins", "Washington Capitals", "New York Rangers", "Florida Panthers", "easy")
h("What is the name of the annual outdoor NHL game held on New Year's Day?", "Winter Classic", "Heritage Classic", "Stadium Series", "Outdoor Showdown", "easy")
h("Which NHL team has a logo featuring a saber-toothed cat?", "Nashville Predators", "Florida Panthers", "Carolina Hurricanes", "Minnesota Wild", "easy")
h("The Seattle Kraken joined the NHL in which year?", "2021", "2020", "2022", "2019", "medium")
h("Which team's fans are known for doing the 'Whiteout' during playoffs?", "Winnipeg Jets", "Minnesota Wild", "Colorado Avalanche", "Nashville Predators", "medium")
h("What Original Six team plays at TD Garden?", "Boston Bruins", "New York Rangers", "Detroit Red Wings", "Chicago Blackhawks", "easy")
h("Which team drafted Auston Matthews first overall in 2016?", "Toronto Maple Leafs", "Winnipeg Jets", "Edmonton Oilers", "Buffalo Sabres", "easy")
h("The Tampa Bay Lightning won back-to-back Stanley Cups in which years?", "2020 and 2021", "2019 and 2020", "2021 and 2022", "2018 and 2019", "medium")
h("Which arena was known as 'The Joe' before the Red Wings moved to Little Caesars Arena?", "Joe Louis Arena", "Joe Sakic Arena", "Joe DiMaggio Coliseum", "Joe Montana Stadium", "medium")
h("What team does Connor Bedard play for after being drafted first overall in 2023?", "Chicago Blackhawks", "Anaheim Ducks", "Columbus Blue Jackets", "San Jose Sharks", "easy")
h("The 2004 lockout resulted in which team's Stanley Cup win being the last before the lost season?", "Tampa Bay Lightning", "New Jersey Devils", "Calgary Flames", "Detroit Red Wings", "hard")

# --- Famous Moments & Playoff Drama (111-160) ---
h("In 1994, which Rangers captain guaranteed a Game 6 victory in the Eastern Conference Finals and delivered with a hat trick?", "Mark Messier", "Brian Leetch", "Adam Graves", "Mike Richter", "medium")
h("Patrick Roy's famous 'wink' at an opposing coach happened during which playoff series?", "1993 Montreal vs. Los Angeles (Cup Final)", "1996 Colorado vs. Detroit", "2002 Colorado vs. Detroit", "1993 Montreal vs. Quebec", "hard")
h("The 'Easter Epic' — the longest modern NHL playoff game — went how many overtimes in 1987 (Islanders vs. Capitals)?", "4 overtimes", "3 overtimes", "5 overtimes", "6 overtimes", "hard")
h("In the 2010 Stanley Cup Final, Patrick Kane scored a phantom goal that no one initially saw go in. Against which team?", "Philadelphia Flyers", "Detroit Red Wings", "Vancouver Canucks", "Boston Bruins", "medium")
h("Which team blew a 3-0 series lead to the Philadelphia Flyers in the 2010 Eastern Conference Semifinals?", "Boston Bruins", "Pittsburgh Penguins", "New Jersey Devils", "Washington Capitals", "hard")
h("The 'Fog Game' of the 1988 Stanley Cup Final was caused by what unusual condition in the arena?", "Thick fog from warm outside air mixing with ice surface condensation", "A broken smoke machine", "A fire in a nearby building", "Steam from a broken pipe", "hard")
h("In the 1996 Western Conference playoffs, the Detroit Red Wings and Colorado Avalanche ignited a fierce rivalry. Which incident sparked it?", "Claude Lemieux's hit on Kris Draper from behind into the boards", "A line brawl in Game 1", "Patrick Roy's shutout and wink", "A controversial goal review", "hard")
h("Which goalie made a legendary 'the save' on Tomas Holmstrom in the 2009 playoffs, among many iconic saves in his career?", "Marc-Andre Fleury", "Chris Osgood", "Ryan Miller", "Tim Thomas", "hard")
h("Tim Thomas's MVP performance in the 2011 Stanley Cup Final backstopped which team to the Cup?", "Boston Bruins", "Vancouver Canucks", "Tampa Bay Lightning", "Philadelphia Flyers", "medium")
h("The Vancouver Canucks' loss in the 2011 Stanley Cup Final led to what unfortunate event in the city?", "Rioting in downtown Vancouver", "The firing of the entire coaching staff", "A player walkout", "The arena being closed for repairs", "medium")
h("Which player scored the 'Golden Goal' in triple overtime of the 1999 Stanley Cup Final for Dallas?", "Brett Hull", "Mike Modano", "Joe Nieuwendyk", "Ed Belfour", "medium")
h("Brett Hull's 'Golden Goal' in 1999 was controversial because of what?", "His skate was in the crease", "The puck didn't fully cross the line", "There was a missed offside", "Time had expired", "hard")
h("Which team completed the only 3-0 comeback in Stanley Cup Final history (1942)?", "Toronto Maple Leafs", "Detroit Red Wings", "Montreal Canadiens", "Boston Bruins", "hard")
h("The longest game in NHL history (1936 playoff game) went into how many overtimes?", "6 overtimes", "5 overtimes", "4 overtimes", "7 overtimes", "hard")
h("'It was 4-1' refers to a famous 2013 playoff collapse by which team?", "Toronto Maple Leafs", "Boston Bruins", "Vancouver Canucks", "Ottawa Senators", "medium")
h("In the 2013 playoffs, the Maple Leafs blew a 4-1 third-period lead against which team?", "Boston Bruins", "Montreal Canadiens", "New York Rangers", "Tampa Bay Lightning", "medium")
h("Alexander Ovechkin famously scored 'The Goal' — on his back, one-handed — against which team in 2006?", "Phoenix Coyotes", "Montreal Canadiens", "Pittsburgh Penguins", "New York Rangers", "hard")
h("The 'Brawl in Hockeytown' (March 26, 1997) was between which two teams?", "Detroit Red Wings and Colorado Avalanche", "Detroit Red Wings and Chicago Blackhawks", "Colorado Avalanche and Dallas Stars", "Pittsburgh Penguins and Philadelphia Flyers", "medium")
h("In the famous 1997 brawl, which Detroit player fought Claude Lemieux?", "Darren McCarty", "Kris Draper", "Brendan Shanahan", "Steve Yzerman", "hard")
h("The 'Gretzky had it, lost it' call describes a famous 1993 playoff moment. Which team benefited?", "Montreal Canadiens", "Los Angeles Kings", "Toronto Maple Leafs", "Chicago Blackhawks", "hard")
h("Which player scored on a penalty shot in overtime of a 2020 Stanley Cup playoff game — the first in NHL history?", "Nikita Kucherov", "Brayden Point", "Steven Stamkos", "Nathan MacKinnon", "hard")
h("What unusual venue hosted the 2003 Heritage Classic, the first NHL outdoor game?", "Commonwealth Stadium in Edmonton", "McMahon Stadium in Calgary", "Investors Group Field in Winnipeg", "Saputo Stadium in Montreal", "hard")
h("In the 2018 playoffs, the Washington Capitals won their franchise's first Stanley Cup by beating which team in the Final?", "Vegas Golden Knights", "Tampa Bay Lightning", "Pittsburgh Penguins", "Nashville Predators", "medium")
h("The 1998 Stanley Cup Final was a sweep. Which team swept which?", "Detroit Red Wings swept the Washington Capitals", "New Jersey Devils swept the Detroit Red Wings", "Colorado Avalanche swept the Florida Panthers", "Dallas Stars swept the Buffalo Sabres", "hard")
h("Which team won the first-ever NHL game played in an outdoor stadium (2003)?", "Montreal Canadiens", "Edmonton Oilers", "Calgary Flames", "Toronto Maple Leafs", "hard")
h("Wayne Gretzky's emotional press conference after being traded to Los Angeles famously featured what?", "Gretzky in tears", "Gretzky refusing to speak", "Gretzky ripping his Oilers jersey", "Gretzky shaking hands with the Kings owner", "easy")
h("During the 2023 playoffs, which team became the first 8-seed to reach the second round in years by upsetting a top team?", "Florida Panthers (upset Boston Bruins, the record-setting team)", "New York Islanders", "Nashville Predators", "Winnipeg Jets", "medium")
h("The 2022-23 Boston Bruins set a regular-season wins record with how many wins?", "65", "62", "60", "58", "hard")
h("Despite their record-setting season, the 2023 Bruins were eliminated in the first round by which team?", "Florida Panthers", "Toronto Maple Leafs", "Tampa Bay Lightning", "Carolina Hurricanes", "medium")
h("Which goalie recorded a shutout in his very first NHL game in the Stanley Cup Final (2003)?", "Jean-Sebastien Giguere posted legendary numbers, but Martin Brodeur won the Cup — this question refers to no specific instance; the note is Brodeur's dominance", "Martin Brodeur", "Patrick Roy", "Ed Belfour", "hard")

# --- Arenas, Trophies & Culture (161-200) ---
h("The oldest trophy in professional North American sports is which hockey award?", "The Stanley Cup", "The Presidents' Trophy", "The Prince of Wales Trophy", "The Clarence S. Campbell Bowl", "easy")
h("The Stanley Cup is named after whom?", "Lord Stanley of Preston, Governor General of Canada", "James Stanley, a British industrialist", "Henry Stanley, the explorer", "Stanley Park in Vancouver", "medium")
h("What unique tradition surrounds the Stanley Cup that no other major sports trophy shares?", "Each winning player gets to spend a day with the Cup", "It is remade every year", "It is kept in a vault between seasons", "Only the captain may touch it", "easy")
h("What is engraved on the Stanley Cup?", "The names of every player on every winning team", "The scores of every Final game", "The names of every team that competed", "The names of the league commissioners", "easy")
h("The Conn Smythe Trophy is awarded to whom?", "The most valuable player of the NHL playoffs", "The regular-season MVP", "The best defenseman", "The best rookie", "medium")
h("Which trophy is given to the NHL's top defenseman?", "The Norris Trophy", "The Selke Trophy", "The Calder Trophy", "The Vezina Trophy", "medium")
h("The Selke Trophy is given for excellence in what aspect of hockey?", "Defensive forward play", "Goaltending", "Offensive production", "Leadership", "medium")
h("What trophy is awarded to the NHL's best goaltender?", "The Vezina Trophy", "The Jennings Trophy", "The Norris Trophy", "The Hart Trophy", "easy")
h("The Calder Trophy goes to the NHL's best what?", "Rookie", "Captain", "European player", "Comeback player", "easy")
h("What is the Presidents' Trophy awarded for?", "Best regular-season record in the NHL", "Winning the Stanley Cup", "Most improved team", "Best team in the Western Conference", "medium")
h("Which arena is considered one of the loudest and most hostile for visiting teams in the NHL?", "Bell Centre (Montreal)", "Scotiabank Arena (Toronto)", "United Center (Chicago)", "T-Mobile Arena (Las Vegas)", "medium")
h("The 'Octopus Guy' Al Sobotka was a famous figure at which NHL arena?", "Joe Louis Arena (Detroit)", "The Forum (Montreal)", "Boston Garden", "Chicago Stadium", "medium")
h("What is the name of the trophy awarded to the NHL team that finishes with the fewest goals against?", "William M. Jennings Trophy", "Vezina Trophy", "Presidents' Trophy", "Lady Byng Trophy", "medium")
h("The Lady Byng Trophy is awarded for what?", "Sportsmanship and gentlemanly conduct combined with playing ability", "Most penalty minutes", "Best defensive play", "Community service", "medium")
h("Which NHL arena is located inside a casino resort?", "T-Mobile Arena (Las Vegas)", "Crypto.com Arena (Los Angeles)", "Ball Arena (Denver)", "Amalie Arena (Tampa)", "easy")
h("What do fans throw on the ice in Nashville during Predators playoff games?", "Catfish", "Octopi", "Hats", "Rubber ducks", "medium")
h("In Nashville, why do fans throw catfish on the ice?", "As a spin on Detroit's octopus tradition since catfish are local to Tennessee", "To honor a former player nicknamed 'Catfish'", "It's a superstition from the team's first season", "A radio station started the tradition as a contest", "hard")
h("What is the 'Keeper of the Cup' in hockey?", "A Hockey Hall of Fame employee who travels with the Stanley Cup at all times", "The team captain", "The NHL commissioner", "A trophy case in each arena", "medium")
h("The Hockey Hall of Fame is located in which city?", "Toronto", "Montreal", "New York", "Ottawa", "easy")
h("What makes the Stanley Cup unique among major sports trophies in terms of its physical form?", "It grows — new bands are added for winning teams and old ones are retired to the Hall of Fame", "It is made of solid gold", "It is the smallest major sports trophy", "It has never been repaired or modified", "medium")

# --- Modern Era & Strategy (201-251) ---
h("What is 'Corsi' in hockey analytics?", "A shot-attempt differential metric (all shot attempts for vs. against)", "A measure of goalie save percentage", "A penalty differential stat", "A faceoff win percentage", "medium")
h("What does 'expected goals' (xG) measure in hockey?", "The probability that a shot will result in a goal based on shot quality", "The number of goals a team is expected to score per season", "A player's goal-scoring pace projected over 82 games", "The average goals per game in the league", "medium")
h("In modern NHL strategy, what does 'dump and chase' refer to?", "Shooting the puck into the offensive zone and pursuing it", "Dumping a player with a check and chasing the puck", "Clearing the puck out of the defensive zone repeatedly", "A penalty-kill strategy", "easy")
h("What is a 'cycle' in offensive hockey?", "Moving the puck along the boards in the offensive zone to maintain possession", "A line change pattern", "A defensive rotation in the neutral zone", "A power play formation", "medium")
h("What does 'top-six forward' mean?", "One of the team's best six forwards, typically on the first two lines", "A forward who plays on the top power play unit", "A player who scores at least six goals per season", "A draft pick in the top six", "easy")
h("In the modern NHL, what is the 'stretch pass'?", "A long pass from the defensive zone to a player at or beyond center ice", "A pass made while doing the splits", "A pass along the boards in the offensive zone", "A pass from one winger to another across the ice", "medium")
h("What formation do most NHL teams use on the power play?", "1-3-1 or umbrella formation", "2-2-1 box", "3-2 diamond", "4-1 stack", "medium")
h("What is a 'one-timer' in hockey?", "Shooting the puck directly from a pass without stopping it first", "A single shot in a shootout", "Scoring on the first shot of the game", "A one-on-one breakaway", "easy")
h("What does 'forechecking' mean?", "Pressuring the opposing team in their defensive zone to force turnovers", "Checking a player before they receive the puck", "Defending in the neutral zone", "A pre-game scouting technique", "easy")
h("What is a 'neutral zone trap'?", "A defensive system that clogs the neutral zone to prevent clean entries", "A penalty for obstruction at center ice", "An offensive play through the middle of the ice", "A special teams formation", "medium")
h("The 'left-wing lock' is a defensive system that originated with which team?", "Detroit Red Wings", "New Jersey Devils", "Minnesota Wild", "Dallas Stars", "hard")
h("What does 'possession zone time' measure in modern hockey analytics?", "How long a team maintains puck control in the offensive zone", "Total time of puck possession in any zone", "Time spent in the defensive zone", "Power play duration", "medium")
h("Which NHL team pioneered the use of advanced analytics in their front office, often called the 'Moneyball of hockey'?", "Carolina Hurricanes (under Tom Dundon/Eric Tulsky)", "Toronto Maple Leafs (under Kyle Dubas)", "Tampa Bay Lightning", "New Jersey Devils", "hard")
h("What is 'PDO' in hockey analytics?", "The sum of a team's shooting percentage and save percentage (often used as a luck metric)", "Player Defensive Output", "Points Derived from Offense", "Penalty Differential Outcome", "hard")
h("Connor McDavid is often compared to which all-time great for his skating and playmaking?", "Wayne Gretzky", "Mario Lemieux", "Bobby Orr", "Mark Messier", "easy")
h("Which NHL team plays in the southernmost US city?", "Florida Panthers (Sunrise, Florida)", "Tampa Bay Lightning", "Dallas Stars", "Arizona Coyotes", "medium")
h("What is the NHL's salary cap called?", "Hard salary cap", "Soft salary cap", "Luxury tax threshold", "Revenue sharing cap", "medium")
h("What does 'LTIR' stand for in NHL cap management?", "Long-Term Injured Reserve", "Limited-Time Incentive Revenue", "League Trade and Income Regulation", "Long-Term Investment Return", "medium")
h("The NHL Draft Lottery was reformed after which controversial pick?", "Connor McDavid (2015) / The 'Tanking' era leading to reforms", "Sidney Crosby (2005)", "Patrick Kane (2007)", "Nathan MacKinnon (2013)", "hard")
h("What is a 'no-move clause' in an NHL contract?", "The player cannot be traded, sent down, or placed on waivers without consent", "The player cannot be moved to a different position", "The team cannot relocate while the player is under contract", "The player cannot change jersey numbers", "medium")
h("How many teams currently compete in the NHL?", "32", "30", "31", "28", "easy")
h("Which conference do the Winnipeg Jets play in?", "Western Conference", "Eastern Conference", "Central Conference", "Northern Conference", "easy")
h("In the NHL, what is the 'trade deadline'?", "The last date teams can make trades during the regular season", "The deadline to sign drafted players", "The final day of free agency", "The last day to place players on waivers", "easy")
h("What happens at the NHL Expansion Draft?", "New teams select players from existing rosters (each team protects a set number)", "All teams redraft their players", "International players are drafted", "Undrafted free agents are assigned to teams", "medium")
h("What is a 'heritage jersey' or 'reverse retro' in the NHL?", "A special alternate jersey featuring a retro-inspired design with a modern twist", "A jersey worn only in outdoor games", "The team's original inaugural jersey", "A jersey designed by fans through a vote", "easy")
h("In the 2024 Draft, which highly-touted prospect was expected to go first overall?", "Macklin Celebrini", "Connor Bedard", "Adam Fantilli", "Leo Carlsson", "medium")
h("What does 'cap hit' mean in NHL contracts?", "The average annual value of a contract that counts against the salary cap", "The maximum a player can earn in bonuses", "The total value of the contract", "The signing bonus amount", "medium")
h("Which NHL team relocated from Atlanta (for the second time) to become the Winnipeg Jets in 2011?", "Atlanta Thrashers", "Atlanta Flames", "Hartford Whalers", "Minnesota North Stars", "medium")
h("What is the 'waiver wire' in the NHL?", "A system where players must clear waivers (be unclaimed by other teams) before being sent to the minors", "A trading system between teams", "A free agent marketplace", "A disciplinary process", "medium")
h("The NHLPA is what?", "The National Hockey League Players' Association (the players' union)", "The National Hockey League Penalty Authority", "The North American Hockey League Players' Academy", "The NHL Performance Analytics department", "easy")
h("Which goaltender style involves dropping to the knees and spreading the pads?", "Butterfly style", "Stand-up style", "Hybrid style", "Profly style", "easy")
h("What is a 'screen' in front of the net?", "A player standing between the goalie and the shooter to block the goalie's view", "A video review screen", "A glass panel near the bench", "A goalie move to hide the puck", "easy")
h("What is the 'blue paint' in hockey slang?", "The crease area in front of the net", "The blue line", "The ice surface after a Zamboni pass", "The bench area", "easy")
h("Which position is also known as a 'netminder' or 'backstop'?", "Goaltender", "Defenseman", "Center", "Winger", "easy")
h("What does 'bar down' mean in hockey slang?", "A shot that hits the crossbar and goes straight down into the net", "A shot that goes wide and hits the boards", "A save where the goalie uses the bar of the goal", "Lowering the penalty box barrier", "easy")
h("What does 'lettuce' mean in hockey slang?", "Long, flowing hair coming out of a helmet", "A type of jersey", "A weak shot", "An easy goal", "medium")
h("What is a 'dangle' in hockey?", "A skilled stickhandling move to get around a defender", "A hanging decoration in the arena", "A type of pass", "A goalie save technique", "easy")
h("What does 'going top shelf' mean?", "Shooting the puck into the upper part of the net", "Being sent to the press box", "Getting promoted to the first line", "Reaching the top of the standings", "easy")
h("In hockey slang, what is a 'celly'?", "A goal celebration", "A cell phone check by refs", "A type of penalty", "A defensive formation", "easy")
h("What is the 'quiet room' or 'concussion protocol' in the NHL?", "A mandatory evaluation room for players suspected of having a concussion", "A soundproof room for coaches to make calls", "The officials' review room", "A room for meditation before games", "medium")
h("What does 'scratched' mean when a player is 'a healthy scratch'?", "The player is not injured but is left out of the lineup by the coach's decision", "The player has a minor injury", "The player is suspended", "The player is being traded", "easy")

# --- Additional Hockey (50 more) ---
h("What is a 'Zamboni' used for?", "Resurfacing the ice between periods", "Cleaning the glass around the rink", "Measuring ice temperature", "Transporting equipment", "easy")
h("What does 'top cheese' mean in hockey slang?", "A shot into the top corner of the net", "The best player on the team", "A type of celebration", "A goalie save", "easy")
h("Which country has won the most Olympic gold medals in men's ice hockey?", "Canada", "Russia/Soviet Union", "United States", "Sweden", "medium")
h("What is a 'breakaway' in hockey?", "When a skater gets past all defenders for a one-on-one with the goalie", "Breaking a stick on a shot", "A timeout called during a fight", "A fast line change", "easy")
h("What does '10-ply' mean in hockey slang?", "Soft or weak (like thick toilet paper)", "A 10-minute penalty", "A player with 10 seasons experience", "A 10-goal lead", "medium")
h("The 'Michigan' or 'lacrosse goal' involves what move?", "Picking the puck up on the stick blade and tucking it in from behind the net", "A between-the-legs shot", "A diving shot", "A slapshot from the blue line", "medium")
h("Which player popularized the 'Michigan' goal in the NHL?", "Andrei Svechnikov", "Trevor Zegras", "Mike Legg (NCAA) — Svechnikov in the NHL", "Patrick Kane", "hard")
h("What is 'puck luck' in hockey?", "Random bounces and fortunate breaks that lead to goals", "A superstition about kissing the puck", "A type of defensive play", "A statistical metric", "easy")
h("What is the 'iron' in hockey slang?", "The goal post or crossbar", "A type of skate blade", "The penalty box door", "Body armor worn by goalies", "easy")
h("What is a 'goon' in hockey?", "An enforcer whose primary role is fighting and intimidation", "A player who scores garbage goals", "A backup goalie", "A team mascot", "easy")
h("Which country is hockey's birthplace according to the IIHF?", "Canada", "Russia", "England", "Sweden", "easy")
h("What is the 'neutral zone' in hockey?", "The area of ice between the two blue lines", "The area behind each goal", "The penalty box area", "The crease", "easy")
h("What does 'chirping' mean in hockey?", "Trash-talking opponents on the ice", "A sound the puck makes off the post", "Calling for a pass", "Whistling to the referee", "easy")
h("What is a 'barn' in hockey slang?", "An arena or rink", "The team locker room", "A type of defensive formation", "The area behind the net", "easy")
h("In the NHL, what does 'waiver-exempt' mean?", "A player can be sent to the minors without being exposed to other teams claiming them", "A player is exempt from penalties", "A player doesn't count against the salary cap", "A player can't be traded", "medium")
h("What is 'clutch and grab' hockey?", "A style of play focused on holding and hooking opponents to slow them down", "An overtime strategy", "A type of forecheck", "A goalie technique", "medium")
h("The 'dead puck era' of the NHL refers roughly to which period?", "Mid-1990s to 2004 (low-scoring, trap-heavy hockey)", "The 1970s", "The 2010s", "The 1960s", "medium")
h("What change did the NHL make after the 2004-05 lockout to increase scoring?", "Enforced obstruction penalties, removed the two-line pass, and added the shootout", "Made the goals bigger", "Added a fourth period", "Reduced team rosters", "medium")
h("What is a 'coast-to-coast' goal in hockey?", "A player carrying the puck from their own end to the opponent's net and scoring", "A goal scored during an east-west road trip", "Passing the puck from one winger to another", "A goal from center ice", "easy")
h("What is a 'saucer pass'?", "A pass that lifts the puck off the ice and floats it like a flying saucer over sticks or obstacles", "A pass along the boards", "A backward pass", "A pass off the glass", "easy")
h("What does 'dropping the gloves' mean?", "Starting a fight (players remove gloves before fighting)", "Surrendering or giving up", "A celebratory gesture", "A goalie removing their blocker", "easy")
h("What is a 'poke check'?", "Using the stick to poke the puck away from an opponent", "Checking a player into the boards", "A referee's equipment check", "A goalie's blocker save", "easy")
h("Which NHL team's fans are known for the 'C of Red' during playoffs?", "Calgary Flames", "Carolina Hurricanes", "Chicago Blackhawks", "Detroit Red Wings", "medium")
h("What is the 'rover' position that existed in early hockey?", "A sixth skater who could roam freely on the ice without positional restrictions", "A replacement for the goalie", "A referee's assistant", "A reserve player", "hard")
h("Bobby Hull was known by what nickname?", "The Golden Jet", "The Golden Boy", "The Blonde Bomber", "The Flying Finn", "medium")
h("Which team did Patrick Roy demand a trade from after being humiliated in a blowout loss in 1995?", "Montreal Canadiens", "Colorado Avalanche", "Quebec Nordiques", "New York Rangers", "medium")
h("What is 'padding stats' or 'stat padding' concern in hockey related to empty-net goals?", "Players scoring on an empty net to inflate their goal totals when the game is already decided", "Goalies inflating save numbers", "Defensemen blocking easy shots", "Players taking faceoffs they know they'll win", "easy")
h("What is a 'shutdown line' in hockey?", "A defensive-minded forward line tasked with neutralizing the opponent's best players", "A line that never scores", "The last line on the bench", "A line that only plays during penalty kills", "medium")
h("What is 'tendy' in hockey slang?", "A goaltender", "A tender or soft player", "A team trainer", "A minor league player", "easy")
h("What is the 'blue line' in hockey?", "The lines that mark the boundary of the offensive/defensive zones", "The line at center ice", "The goal line", "The line in front of the penalty box", "easy")
h("Who is the only player to have his number retired league-wide by the NHL?", "Wayne Gretzky (#99)", "Bobby Orr (#4)", "Mario Lemieux (#66)", "Gordie Howe (#9)", "easy")
h("What is the 'All-Star break' in the NHL?", "A mid-season pause featuring the All-Star Game and Skills Competition", "A break for players to rest without any events", "A break only for teams not in playoff contention", "The break between regular season and playoffs", "easy")
h("What is a 'game misconduct' penalty?", "An ejection from the game for the remainder of play", "A 10-minute penalty", "A suspension for the next game", "A fine assessed by the league", "medium")
h("In the NHL draft, how many rounds are there?", "7", "5", "10", "3", "medium")
h("What is the 'entry draft' age eligibility in the NHL?", "18 years old by September 15 of the draft year", "17 years old", "19 years old", "20 years old", "medium")
h("What is 'cap circumvention' in the NHL?", "Finding loopholes to get around salary cap restrictions", "Exceeding the salary cap intentionally", "Trading draft picks for cap space", "Signing players to minimum deals only", "medium")
h("Which team was penalized for cap circumvention involving long-term contracts with declining salaries?", "New Jersey Devils (Kovalchuk contract)", "Chicago Blackhawks", "Nashville Predators", "Tampa Bay Lightning", "hard")
h("What is a 'point shot' in hockey?", "A shot taken by a defenseman from the blue line area (the 'point')", "A shot worth extra points", "A shot during a power play only", "A shot aimed at the five-hole", "easy")
h("What does 'finishing check' mean?", "Completing a body check on an opponent even after they've passed the puck", "Scoring a goal to finish a game", "The final hit in a fight", "Checking equipment after the game", "medium")
h("What is a 'face wash' in hockey?", "Rubbing a gloved hand in an opponent's face to agitate them", "Washing the ice surface", "A save where the goalie uses their face mask", "Cleaning blood off after a high stick", "medium")
h("What is the 'code' in hockey regarding fighting?", "Unwritten rules about when fighting is acceptable and who can fight whom", "The official NHL rulebook", "A referee's signal system", "The team's playbook", "medium")
h("What is 'tape-to-tape' in hockey?", "A pass that lands perfectly on a teammate's stick blade", "Wrapping a stick with tape", "A video review process", "A statistical tracking method", "easy")
h("What is a 'greasy goal' in hockey?", "A scrappy, ugly goal scored from close range, often from a scramble", "A clean, highlight-reel goal", "A goal scored by deflection from center ice", "A goal that shouldn't have counted", "easy")
h("Which famous arena was known as 'The Igloo' before being demolished?", "Civic Arena / Mellon Arena (Pittsburgh)", "Joe Louis Arena (Detroit)", "Chicago Stadium", "Boston Garden", "medium")
h("What is a 'two-on-one' rush?", "Two attackers coming down the ice against only one defender (plus the goalie)", "Two players fighting one opponent", "A 2-minute power play", "Two goals scored by one player", "easy")
h("What does 'grocery stick' mean in hockey slang?", "A player who sits between the forwards and defensemen on the bench (like a divider in a grocery cart)", "A broken stick", "A player who brings food for the team", "A cheap stick brand", "hard")
h("What is 'the quiet room' protocol in the NHL?", "A mandatory concussion evaluation area for players showing signs of head injury", "A meditation room for players", "The coaches' office", "The replay review room", "medium")
h("Who coached the most NHL games in history?", "Scotty Bowman", "Joel Quenneville", "Barry Trotz", "Al Arbour", "medium")
h("Scotty Bowman holds the record for most Stanley Cup wins by a coach with how many?", "9", "7", "11", "6", "hard")
h("What is the 'Presidents' Trophy curse' in hockey?", "The belief that the team with the best regular-season record rarely wins the Stanley Cup", "A physical trophy that is unlucky to touch", "A tradition of the president attending the final", "A rule about regular-season champions", "medium")


# ============================================================
# BASKETBALL QUESTIONS (134)
# ============================================================

# --- Rules & Basics (1-25) ---
b("How long does a team have to advance the ball past half-court in the NBA?", "8 seconds", "10 seconds", "5 seconds", "12 seconds", "easy")
b("How many players from each team are on the court during play?", "5", "6", "4", "7", "easy")
b("What is a 'double dribble' in basketball?", "Dribbling the ball, stopping, and then dribbling again", "Bouncing two balls at once", "Dribbling with both hands simultaneously", "Passing the ball twice in a row", "easy")
b("How many seconds does an NBA team have on the shot clock?", "24 seconds", "30 seconds", "20 seconds", "35 seconds", "easy")
b("What is the distance of the NBA three-point line from the basket at the top of the arc?", "23 feet 9 inches", "22 feet", "25 feet", "21 feet 6 inches", "medium")
b("What is a 'flagrant foul' in the NBA?", "Unnecessary or excessive contact against an opponent", "Any foul committed in the final 2 minutes", "A foul while shooting a three-pointer", "A technical foul on a coach", "medium")
b("How many personal fouls before an NBA player fouls out?", "6", "5", "7", "4", "easy")
b("What is a 'technical foul' commonly given for?", "Unsportsmanlike conduct such as arguing with referees", "A hard foul on a fast break", "A foul while the ball is dead", "Traveling violations", "easy")
b("In the NBA, what is 'goaltending'?", "Touching the ball on its downward arc toward the basket or while on/above the rim", "Guarding the basket by standing under it", "Blocking a shot at its highest point", "Tipping in a rebound", "medium")
b("What does a 'clear path' foul result in?", "Two free throws and possession for the fouled team", "One free throw and an inbound", "A technical foul and ejection", "Three free throws", "medium")
b("What is the 'restricted area' arc under the basket?", "A semicircle where defenders cannot draw a charging foul", "An area where only the center can stand", "The free throw lane", "A no-dunk zone", "medium")
b("How long are NBA quarters?", "12 minutes", "10 minutes", "15 minutes", "8 minutes", "easy")
b("How long is halftime in an NBA game?", "15 minutes", "20 minutes", "10 minutes", "12 minutes", "medium")
b("What is the 'bonus' in basketball?", "When a team has committed enough fouls that every subsequent foul results in free throws", "A bonus point for half-court shots", "Extra time after regulation", "A reward for not committing fouls", "easy")
b("What is an 'and-one' in basketball?", "Making a shot while being fouled and getting a free throw attempt", "Scoring a field goal plus a bonus point", "A one-on-one play", "An assist that leads to a three-pointer", "easy")
b("What is 'traveling' in basketball?", "Taking more than two steps without dribbling the ball", "Running with the ball across half-court", "Stepping out of bounds while dribbling", "Moving screens", "easy")
b("In the NBA, how long can a player stand in the paint on offense?", "3 seconds", "5 seconds", "10 seconds", "No limit", "easy")
b("What is a 'hack-a-Shaq' strategy?", "Intentionally fouling a poor free throw shooter to send them to the line", "Using Shaq as a screen on every play", "Double-teaming the opposing center", "A post-up move invented by Shaq", "medium")
b("What is the NBA's 'take foul' rule (implemented in 2022)?", "A transition foul where the fouled team gets one free throw plus possession", "A foul that automatically results in ejection", "A foul during a fast break that gives three free throws", "A foul that resets the shot clock to 14", "hard")
b("What is an 'isolation play' (ISO)?", "A play where one player takes on their defender one-on-one while teammates clear out", "A defensive scheme where each player guards a zone", "A play run only in the fourth quarter", "A set play from an inbounds pass", "easy")
b("What is a 'pick and roll' in basketball?", "An offensive play where a player sets a screen and then rolls to the basket", "A defensive rotation", "A rebounding technique", "A dribble move to get past a defender", "easy")
b("What happens if an NBA game is tied after regulation?", "5-minute overtime periods until there's a winner", "A sudden-death overtime", "A free throw shootout", "The game ends in a tie", "easy")
b("What is a 'loose ball foul'?", "A foul committed when neither team has possession of the ball", "A foul on a lazy pass", "A foul during a timeout", "A foul on an uncontested rebound", "medium")
b("What is a 'Flagrant 2' foul in the NBA?", "Unnecessary and excessive contact resulting in automatic ejection", "Two flagrant fouls in one game", "A flagrant foul in the second half", "A hard foul on a layup attempt", "medium")
b("How far is the NBA free throw line from the basket?", "15 feet", "12 feet", "18 feet", "14 feet", "easy")

# --- Records & Legends (26-65) ---
b("Which player holds the NBA record for most points in a single game with 100?", "Wilt Chamberlain", "Michael Jordan", "Kobe Bryant", "LeBron James", "easy")
b("Who holds the record for most career points in NBA history?", "LeBron James", "Kareem Abdul-Jabbar", "Karl Malone", "Michael Jordan", "easy")
b("Kareem Abdul-Jabbar is famous for which signature shot?", "The skyhook", "The fadeaway", "The finger roll", "The hook shot", "easy")
b("Which player scored 81 points in a single game in 2006 — the second-highest in NBA history?", "Kobe Bryant", "Tracy McGrady", "Allen Iverson", "LeBron James", "easy")
b("Who is the NBA's all-time leader in assists?", "John Stockton", "Jason Kidd", "Magic Johnson", "Steve Nash", "medium")
b("John Stockton also holds the NBA record for career what?", "Steals", "Free throw percentage", "Games played", "Minutes played", "medium")
b("Which player earned the nickname 'The Answer' and famously crossed over Michael Jordan as a rookie?", "Allen Iverson", "Stephon Marbury", "Baron Davis", "Penny Hardaway", "easy")
b("Who hit 'The Shot' over Craig Ehlo in the 1989 playoffs?", "Michael Jordan", "Larry Bird", "Dominique Wilkins", "Isiah Thomas", "medium")
b("Which player is known as 'The Big Fundamental'?", "Tim Duncan", "David Robinson", "Hakeem Olajuwon", "Patrick Ewing", "easy")
b("Tim Duncan won all five of his championships with which team?", "San Antonio Spurs", "Dallas Mavericks", "Houston Rockets", "Los Angeles Lakers", "easy")
b("Magic Johnson's real first name is what?", "Earvin", "Marcus", "Maurice", "Earl", "medium")
b("Larry Bird and Magic Johnson's rivalry defined which decade of NBA basketball?", "The 1980s", "The 1970s", "The 1990s", "The 2000s", "easy")
b("Which center was known as 'The Dream' for his extraordinary footwork and post moves?", "Hakeem Olajuwon", "Patrick Ewing", "David Robinson", "Alonzo Mourning", "medium")
b("Hakeem Olajuwon won back-to-back championships in 1994-95 with which team?", "Houston Rockets", "San Antonio Spurs", "Orlando Magic", "New York Knicks", "medium")
b("Who is the NBA's all-time leader in career three-pointers made?", "Stephen Curry", "Ray Allen", "Reggie Miller", "James Harden", "easy")
b("Stephen Curry broke Ray Allen's all-time three-point record in a game against which team?", "New York Knicks", "Cleveland Cavaliers", "Boston Celtics", "Los Angeles Lakers", "hard")
b("Which player was nicknamed 'The Mailman' because he always delivered?", "Karl Malone", "John Stockton", "Charles Barkley", "Patrick Ewing", "easy")
b("Who was known as 'Sir Charles' and 'The Round Mound of Rebound'?", "Charles Barkley", "Karl Malone", "Shaquille O'Neal", "Moses Malone", "easy")
b("Which player earned the nickname 'The Iceman'?", "George Gervin", "Julius Erving", "Walt Frazier", "David Thompson", "medium")
b("Dr. J — Julius Erving — was famous for popularizing what type of play?", "Above-the-rim dunking and showmanship", "The three-point shot", "The no-look pass", "The euro step", "medium")
b("Which player won 6 NBA championships and 6 Finals MVPs, never losing in the Finals?", "Michael Jordan", "Bill Russell", "LeBron James", "Magic Johnson", "easy")
b("Bill Russell won how many NBA championships with the Boston Celtics?", "11", "8", "9", "13", "medium")
b("Which player is the NBA's all-time leader in rebounds?", "Wilt Chamberlain", "Bill Russell", "Kareem Abdul-Jabbar", "Moses Malone", "medium")
b("Who was called 'The Logo' because his silhouette is believed to be the basis for the NBA logo?", "Jerry West", "Oscar Robertson", "Bill Russell", "Wilt Chamberlain", "medium")
b("Shaquille O'Neal was so dominant that a strategy was named after him. He won his first three titles with which team?", "Los Angeles Lakers", "Orlando Magic", "Miami Heat", "Phoenix Suns", "easy")
b("Which guard was known as 'White Chocolate' for his flashy passing?", "Jason Williams", "Steve Nash", "John Stockton", "Mike Bibby", "medium")
b("Who holds the record for most triple-doubles in NBA history?", "Russell Westbrook", "Oscar Robertson", "Magic Johnson", "LeBron James", "easy")
b("Oscar Robertson famously averaged a triple-double for an entire season. In which season did he accomplish this?", "1961-62", "1964-65", "1959-60", "1967-68", "hard")
b("Which player, at 7'1\", was known as 'The Unicorn' for his unprecedented shooting ability at his size?", "Kristaps Porzingis", "Kevin Durant", "Dirk Nowitzki", "Giannis Antetokounmpo", "medium")
b("Dirk Nowitzki revolutionized the game for big men with which signature move?", "His one-legged fadeaway jumper", "The dream shake", "The skyhook", "The up-and-under", "medium")
b("Dirk led which franchise to its only NBA championship in 2011?", "Dallas Mavericks", "San Antonio Spurs", "Houston Rockets", "Phoenix Suns", "easy")
b("Who is the youngest player to score 10,000 career NBA points?", "LeBron James", "Kobe Bryant", "Kevin Durant", "Luka Doncic", "medium")
b("Which undrafted player became a two-time NBA MVP?", "Nikola Jokic was drafted 41st — the answer is actually: no player has done this. The correct framing: Which second-round pick became a multiple-time MVP?", "Nikola Jokic", "Ben Wallace", "Giannis Antetokounmpo", "hard")
b("Nikola Jokic was selected with which pick in the 2014 NBA Draft?", "41st overall", "35th overall", "52nd overall", "28th overall", "hard")
b("Which player was drafted 13th overall in 2013 and became 'The Greek Freak'?", "Giannis Antetokounmpo", "Victor Oladipo", "CJ McCollum", "Rudy Gobert", "easy")
b("Giannis Antetokounmpo led which team to the 2021 NBA championship?", "Milwaukee Bucks", "Brooklyn Nets", "Phoenix Suns", "Atlanta Hawks", "easy")
b("Who scored 70 points in a game in 2024, joining rare company?", "Devin Booker (scored 70 in 2017) — but in 2024, no one hit 70", "Karl-Anthony Towns", "Luka Doncic", "Joel Embiid", "hard")
b("Which player is known for his 'Shimmy' celebration after hitting three-pointers?", "Stephen Curry", "James Harden", "Damian Lillard", "Kyrie Irving", "easy")
b("Damian Lillard hit a series-ending 37-foot three-pointer against which team in the 2019 playoffs, waving goodbye to them?", "Oklahoma City Thunder", "Golden State Warriors", "Denver Nuggets", "San Antonio Spurs", "medium")
b("Who hit 'The Shot' — a buzzer-beating three over Joel Embiid — in the 2019 Eastern Conference Semifinals?", "Kawhi Leonard", "Pascal Siakam", "Kyle Lowry", "Jimmy Butler", "medium")

# --- Teams & Culture (66-95) ---
b("Which NBA franchise has won the most championships?", "Boston Celtics", "Los Angeles Lakers", "Chicago Bulls", "Golden State Warriors", "easy")
b("How many championships have the Boston Celtics won (through 2024)?", "18", "17", "16", "19", "medium")
b("The 'Showtime' Lakers of the 1980s were led by which point guard?", "Magic Johnson", "Kareem Abdul-Jabbar", "James Worthy", "Byron Scott", "easy")
b("Which arena is known as 'The Mecca of Basketball'?", "Madison Square Garden", "Staples Center", "The Forum", "Boston Garden", "easy")
b("The 1995-96 Chicago Bulls set a regular-season record with how many wins?", "72", "70", "69", "74", "medium")
b("Which team broke the Bulls' 72-win record in 2015-16 with 73 wins?", "Golden State Warriors", "San Antonio Spurs", "Cleveland Cavaliers", "Miami Heat", "easy")
b("Despite winning 73 games, the 2015-16 Warriors lost the Finals to which team?", "Cleveland Cavaliers", "Oklahoma City Thunder", "San Antonio Spurs", "Toronto Raptors", "easy")
b("LeBron James led a historic 3-1 comeback in the 2016 Finals. His chase-down block on Andre Iguodala is iconic. In which game did it happen?", "Game 7", "Game 6", "Game 5", "Game 4", "medium")
b("The 'Big Three' of the 2008 champion Celtics consisted of Paul Pierce, Kevin Garnett, and whom?", "Ray Allen", "Rajon Rondo", "Kendrick Perkins", "James Posey", "easy")
b("Which team is known for the 'Hack-a-Shaq' era and for drafting Shaquille O'Neal?", "Orlando Magic", "Los Angeles Lakers", "Miami Heat", "Boston Celtics", "medium")
b("The phrase 'Ball don't lie' is associated with which outspoken NBA player?", "Rasheed Wallace", "Dennis Rodman", "Charles Barkley", "Gary Payton", "medium")
b("What is the NBA's 'G League'?", "The NBA's official minor league developmental system", "A summer league for rookies", "A global basketball league", "A gaming/esports league", "easy")
b("'Malice at the Palace' was a notorious brawl in 2004 between which two teams?", "Indiana Pacers and Detroit Pistons", "Chicago Bulls and New York Knicks", "Los Angeles Lakers and Sacramento Kings", "Miami Heat and New York Knicks", "medium")
b("The Malice at the Palace started when a fan threw what at Ron Artest (Metta World Peace)?", "A cup of beer/drink", "A basketball", "A chair", "Food", "medium")
b("Which NBA team moved from Seattle to Oklahoma City in 2008?", "SuperSonics became the Thunder", "Grizzlies moved from Vancouver", "Nets moved from New Jersey", "Kings almost moved from Sacramento", "easy")
b("What year did the Toronto Raptors join the NBA?", "1995", "1998", "1993", "2001", "medium")
b("The 'We Believe' Warriors of 2007 pulled off a historic upset by beating which top seed?", "Dallas Mavericks (1-seed)", "Phoenix Suns", "San Antonio Spurs", "Houston Rockets", "medium")
b("Which NBA team plays at Chase Center in San Francisco?", "Golden State Warriors", "Sacramento Kings", "Los Angeles Clippers", "Portland Trail Blazers", "easy")
b("The 'Lob City' Clippers featured Chris Paul throwing alley-oops to which high-flying big man?", "Blake Griffin (and DeAndre Jordan)", "DeAndre Jordan", "Tobias Harris", "Montrezl Harrell", "easy")
b("Which NBA team has the longest active playoff drought (as of the 2023-24 season)?", "Charlotte Hornets", "Detroit Pistons", "San Antonio Spurs", "Portland Trail Blazers", "hard")
b("What is the 'Sixth Man' in basketball?", "The best player who comes off the bench", "The team's sixth starter in case of injury", "A referee", "A honorary fan position", "easy")
b("The 'Point God' is a nickname for which NBA player?", "Chris Paul", "Magic Johnson", "John Stockton", "Jason Kidd", "easy")
b("What is 'Dub Nation' a reference to?", "Golden State Warriors fans (W = 'dub')", "A celebration dance", "The Washington Wizards fanbase", "The Denver Nuggets' home crowd", "easy")
b("The Sacramento Kings hold the record for the longest playoff drought in NBA history. How long was it before they returned in 2023?", "16 years", "14 years", "18 years", "12 years", "hard")
b("The Miami Heat's culture under Pat Riley emphasizes what?", "Toughness, discipline, and hard work ('Heat Culture')", "High-scoring offense", "Run-and-gun fast breaks", "Tall rosters above all else", "medium")
b("Who coined the phrase 'Not 1, not 2, not 3...' at a Miami Heat introductory event?", "LeBron James", "Dwyane Wade", "Chris Bosh", "Pat Riley", "medium")
b("The 'Trust the Process' era was associated with which NBA franchise?", "Philadelphia 76ers", "Oklahoma City Thunder", "Dallas Mavericks", "Detroit Pistons", "easy")
b("Which coach has won the most NBA championships?", "Phil Jackson (11)", "Red Auerbach (9)", "Gregg Popovich (5)", "Pat Riley (5)", "medium")
b("Phil Jackson was known for using which philosophical coaching approach?", "The Triangle Offense combined with Zen Buddhism principles", "Motion offense with military discipline", "Run-and-gun with sports psychology", "Isolation-heavy sets with meditation", "medium")
b("What is the 'Triangle Offense'?", "A motion-based offensive system built on spacing, ball movement, and reading the defense", "A play where three players form a triangle near the basket", "A fast-break system using three lanes", "A zone defense formation", "medium")

# --- Modern Era & Strategy (96-134) ---
b("What is a 'pace and space' offense?", "A fast-paced system emphasizing three-point shooting and floor spacing", "A slow-paced half-court offense", "A defensive strategy focusing on controlling pace", "A transition defense scheme", "medium")
b("What is 'small ball' in basketball?", "Playing with smaller, faster lineups, often without a traditional center", "Using only guards", "A game played on a smaller court", "A strategy for shorter teams", "easy")
b("The 'Death Lineup' of the Golden State Warriors typically featured which five players?", "Curry, Thompson, Iguodala, Barnes/Durant, and Green", "Curry, Thompson, Green, Livingston, Barnes", "Curry, Thompson, Green, Durant, Cousins", "Curry, Thompson, Green, Wiggins, Poole", "hard")
b("What is 'load management' in the modern NBA?", "Resting healthy star players during regular season games to prevent injuries", "Managing the weight of the basketball", "Reducing practice intensity", "Limiting a player's shot attempts per game", "easy")
b("What does 'true shooting percentage' (TS%) measure?", "Shooting efficiency accounting for field goals, three-pointers, and free throws", "Only field goal percentage", "Three-point percentage adjusted for volume", "Free throw percentage alone", "medium")
b("What is a 'player efficiency rating' (PER)?", "An all-in-one stat measuring a player's per-minute production", "A rating of a player's effort level", "A defensive-only metric", "A measure of a player's contract value", "medium")
b("In modern NBA analytics, what is 'net rating'?", "The difference between a team's offensive and defensive rating per 100 possessions", "A player's plus/minus stat", "The ratio of wins to losses", "A measure of clutch performance", "medium")
b("What NBA rule change (2001) was seen as limiting physical defense and opening up offense?", "Eliminating illegal defense rules (allowing zone defense)", "Moving the three-point line back", "Banning hand-checking", "Adding the shot clock", "hard")
b("The 2004 rule changes that banned hand-checking were designed to benefit what?", "Perimeter players and offensive freedom", "Defensive strategies", "Post-up play", "Rebounding", "medium")
b("What is a 'stretch four' or 'stretch five'?", "A power forward or center who can shoot three-pointers", "A player who plays both the 4 and 5 positions", "A tall player who handles the ball", "A big man who leads the fast break", "medium")
b("Which European player is credited with pioneering the stretch-four role in the NBA?", "Dirk Nowitzki", "Peja Stojakovic", "Andrea Bargnani", "Pau Gasol", "easy")
b("What does 'positionless basketball' refer to?", "A style where players are versatile enough to play multiple positions", "A game without set positions on defense", "Only playing small ball lineups", "Removing the center position entirely", "medium")
b("Victor Wembanyama was the first overall pick in the 2023 NBA Draft. What is he known for?", "His 7'4\" frame combined with guard-like skills and shot-blocking", "Being the tallest player ever drafted", "His three-point shooting only", "His dunking ability", "easy")
b("The 'In-Season Tournament' (now called the NBA Cup) was introduced in which season?", "2023-24", "2022-23", "2024-25", "2021-22", "medium")
b("What is the 'mid-range' shot and why has it fallen out of favor in analytics?", "A shot from inside the three-point line but outside the paint — it's considered inefficient compared to threes or layups", "A shot from half-court", "Any shot not a dunk or three", "A shot from the free throw line", "easy")
b("Who popularized the 'step-back three' as an offensive weapon?", "James Harden", "Stephen Curry", "Luka Doncic", "Damian Lillard", "medium")
b("What is a 'switch-everything' defense?", "A defensive scheme where players switch all screens rather than fighting through them", "A zone defense that changes every possession", "Switching between man and zone each quarter", "A full-court press that switches coverage", "medium")
b("In the modern NBA, what is 'transition offense' valued for?", "Generating easy baskets before the defense can set up", "Wearing down the opposing team", "Running the shot clock down", "Creating isolation opportunities", "easy")
b("What is a 'two-way contract' in the NBA?", "A contract allowing a player to split time between the NBA and G League", "A contract where a player plays both offense and defense roles", "A two-year guaranteed deal", "A contract with two different salary tiers", "medium")
b("Which NBA team was the first to widely use three-point shooting as a primary offensive weapon in the modern era?", "Golden State Warriors (under Steve Kerr)", "Houston Rockets (under Mike D'Antoni)", "Dallas Mavericks (under Don Nelson)", "Phoenix Suns (under Mike D'Antoni)", "medium")
b("Mike D'Antoni's '7 Seconds or Less' offense was run by which team?", "Phoenix Suns", "Houston Rockets", "Golden State Warriors", "Dallas Mavericks", "medium")
b("The '7 Seconds or Less' Suns were led by which point guard?", "Steve Nash", "Jason Kidd", "Stephon Marbury", "Chris Paul", "easy")
b("What is a 'box-and-one' defense?", "Four players play zone while one player guards a specific opponent man-to-man", "A standard box zone defense", "Five players in a box formation", "A press defense from a box set", "medium")
b("The box-and-one gained attention in the 2019 Finals when which coach used it against Stephen Curry?", "Nick Nurse (Toronto Raptors)", "Gregg Popovich", "Erik Spoelstra", "Brad Stevens", "hard")
b("What does 'pace' measure in NBA statistics?", "The number of possessions a team uses per 48 minutes", "How fast players run up the court", "The time between timeouts", "Shot clock usage efficiency", "medium")
b("Who is credited with creating the 'Euro step' move that is now widely used in the NBA?", "Manu Ginobili (popularized it in the NBA)", "Dirk Nowitzki", "Tony Parker", "Hedo Turkoglu", "medium")
b("What is 'garbage time' in basketball?", "The final minutes of a game when the outcome is already decided and bench players are in", "Time spent cleaning the court", "A timeout for cleaning up", "Overtime periods", "easy")
b("What is a 'stretch run' in the NBA season?", "The final weeks of the regular season when playoff positioning is determined", "An extra period after regulation", "A fast break that stretches the defense", "A preseason conditioning drill", "easy")
b("In the 2024 NBA Draft, which French teenager was selected second overall by the Washington Wizards?", "Alex Sarr", "Zaccharie Risacher", "Tidjane Salaun", "Nikola Topic", "hard")
b("Which team won the 2024 NBA championship?", "Boston Celtics", "Dallas Mavericks", "Denver Nuggets", "Miami Heat", "easy")
b("The NBA's play-in tournament determines which seeds?", "The 7th through 10th seeds compete for the final two playoff spots in each conference", "The 8th and 9th seeds only", "The bottom four teams in each conference", "The 6th through 10th seeds", "medium")
b("What is 'cap space' in the NBA?", "The amount of money a team has available under the salary cap to sign players", "The maximum number of roster spots", "A physical space reserved for the team captain", "The space between the court and the stands", "easy")
b("What is a 'sign-and-trade' in the NBA?", "A team signs a free agent and immediately trades them to another team", "Trading a player and signing a replacement", "A trade where both teams sign the traded players to new deals", "Signing an undrafted player from a trade partner", "medium")
b("Who is the tallest player in NBA history?", "Gheorghe Muresan (7'7\")", "Yao Ming", "Manute Bol", "Shawn Bradley", "hard")
b("Which coach is known for saying 'Players play, tough players win'?", "Tom Thibodeau", "Pat Riley", "Gregg Popovich", "Jeff Van Gundy", "hard")
b("The 'Hack-a-Shaq' rule changes limit intentional fouling in which situation?", "The last two minutes of a quarter on off-ball players", "Any time during the game", "Only during overtime", "Only in the fourth quarter", "hard")
b("What does 'boards' mean in basketball statistics?", "Rebounds", "Blocked shots", "Assists", "Steals", "easy")
b("Which player was nicknamed 'The Claw' for his enormous hands and elite defense?", "Kawhi Leonard", "Jimmy Butler", "Paul George", "Draymond Green", "easy")
b("What is a 'Euro step' in basketball?", "A two-step move where the player changes direction laterally to avoid a defender while driving to the basket", "A step-back three-pointer", "A spin move in the post", "A crossover dribble from Europe", "easy")

def main():
    print(f"Generated {len(HOCKEY)} hockey questions")
    print(f"Generated {len(BASKETBALL)} basketball questions")
    print(f"Total: {len(HOCKEY) + len(BASKETBALL)}")

    assert len(HOCKEY) == 251, f"Expected 251 hockey, got {len(HOCKEY)}"
    assert len(BASKETBALL) == 134, f"Expected 134 basketball, got {len(BASKETBALL)}"

    # Wait 3 minutes for other process to finish
    print("Waiting 3 minutes before reading questions.json...")
    time.sleep(180)
    print("Wait complete. Reading questions.json...")

    qpath = os.path.join(os.path.dirname(os.path.abspath(__file__)), "questions.json")
    with open(qpath, "r") as f:
        existing = json.load(f)

    print(f"Existing questions: {len(existing)}")

    new_questions = HOCKEY + BASKETBALL
    # Shuffle choices for each question so answer isn't always first
    import random
    random.seed(42)
    for q in new_questions:
        random.shuffle(q["choices"])

    existing.extend(new_questions)
    print(f"New total: {len(existing)}")

    with open(qpath, "w") as f:
        json.dump(existing, f, indent=2)

    print("questions.json updated successfully!")

    # Send openclaw system event
    try:
        subprocess.run(
            ["openclaw", "system", "event", "--text", "Batch 2 done: 385 hockey+basketball questions added.", "--mode", "now"],
            check=True
        )
        print("System event sent.")
    except Exception as e:
        print(f"Failed to send system event: {e}")

if __name__ == "__main__":
    main()
