#!/usr/bin/env python3
"""
Replace 1,409 repetitive award/year questions with unique trivia questions.
Maintains total count of 10,000 and deduplicates against existing_questions.txt.
"""
import json, re, sys

QUESTIONS_FILE = "questions.json"
EXISTING_FILE = "existing_questions.txt"

# Patterns that identify repetitive award/year questions
PATTERNS = [
    r"who won the.{0,40}(trophy|award|title|cup|championship|open|grand prix).{0,20}(in |for )?(the )?\d{4}",
    r"who won (wimbledon|the masters|the open|us open|french open|australian open).{0,30}\d{4}",
    r"who won the.{0,20}(mvp|cy young|norris|hart|vezina|conn smythe|calder|art ross|rocket richard).{0,20}\d{4}",
    r"which constructor won.{0,30}\d{4}",
    r"who won the.{0,20}formula 1.{0,30}\d{4}",
    r"who led (the nfl|the nba|the nhl|the mlb|the al|the nl).{0,20}(in |for )?\d{4}",
    r"who was the super bowl mvp in",
    r"who was the first overall pick in the \d{4}",
    r"which team (selected|drafted).{0,30}(first overall|1st overall).{0,20}\d{4}",
    r"who won the (norris|hart|vezina|conn smythe|calder|art ross|rocket richard) trophy.{0,20}(for |in )?\d{4}",
]

def load_replacements():
    """Load all replacement questions from generated files, inline data."""
    replacements = {}  # sport -> list of questions

    # Football - from file
    with open("football_388_final.json") as f:
        replacements["football"] = json.load(f)

    # Hockey - from file
    with open("new_hockey_replace.json") as f:
        replacements["hockey"] = json.load(f)

    # Tennis - inline from agent (need to parse)
    # F1 - inline from agent
    # Basketball - inline from agent
    # Golf + Baseball - inline from agent

    # Load from the new_*.json files that were generated by previous batch scripts
    # We'll use the agent-generated ones saved during this session
    for sport in ["tennis", "f1", "basketball", "golf", "baseball"]:
        fn = f"replace_{sport}.json"
        try:
            with open(fn) as f:
                data = json.load(f)
                if sport in replacements:
                    replacements[sport].extend(data)
                else:
                    replacements[sport] = data
        except FileNotFoundError:
            if sport not in replacements:
                replacements[sport] = []

    return replacements


def main():
    # Load current questions
    with open(QUESTIONS_FILE) as f:
        questions = json.load(f)
    print(f"Loaded {len(questions)} questions")

    # Find indices to replace
    to_replace = []
    for i, x in enumerate(questions):
        q_lower = x["q"].lower()
        if any(re.search(p, q_lower) for p in PATTERNS):
            to_replace.append(i)
    print(f"Found {len(to_replace)} repetitive questions to replace")

    # Group by sport
    from collections import Counter
    sport_counts = Counter()
    sport_indices = {}
    for i in to_replace:
        sport = questions[i].get("sport", "unknown")
        sport_counts[sport] += 1
        sport_indices.setdefault(sport, []).append(i)
    print(f"By sport: {dict(sport_counts)}")

    # Load replacements
    replacements = load_replacements()
    for sport, qs in replacements.items():
        print(f"  Replacement pool for {sport}: {len(qs)}")

    # Load existing questions for dedup
    with open(EXISTING_FILE) as f:
        existing = set(line.strip().lower() for line in f if line.strip())

    # Also collect all non-replaced question texts for dedup
    replace_set = set(to_replace)
    for i, x in enumerate(questions):
        if i not in replace_set:
            existing.add(x["q"].lower().strip())

    # Replace questions sport-by-sport
    total_replaced = 0
    for sport, indices in sport_indices.items():
        pool = replacements.get(sport, [])
        if not pool:
            print(f"  WARNING: No replacements for {sport}, skipping {len(indices)} questions")
            continue

        # Filter pool for uniqueness against existing
        unique_pool = []
        for q in pool:
            q_lower = q["q"].lower().strip()
            if q_lower not in existing:
                # Also check no em dashes
                if "\u2014" in q["q"] or "\u2013" in q["q"]:
                    q["q"] = q["q"].replace("\u2014", "-").replace("\u2013", "-")
                # Ensure has required fields
                if all(k in q for k in ("q", "a", "choices", "sport")):
                    if "difficulty" not in q:
                        q["difficulty"] = "medium"
                    unique_pool.append(q)
                    existing.add(q_lower)

        needed = len(indices)
        available = len(unique_pool)
        use_count = min(needed, available)

        if available < needed:
            print(f"  WARNING: {sport} needs {needed} but only {available} unique replacements available")

        for j in range(use_count):
            idx = indices[j]
            questions[idx] = unique_pool[j]
            total_replaced += 1

        print(f"  {sport}: replaced {use_count}/{needed}")

    print(f"\nTotal replaced: {total_replaced}")
    print(f"Final count: {len(questions)}")

    if len(questions) != 10000:
        print(f"ERROR: Expected 10000, got {len(questions)}")
        sys.exit(1)

    # Save
    with open(QUESTIONS_FILE, "w") as f:
        json.dump(questions, f, indent=2, ensure_ascii=False)

    # Update existing_questions.txt
    with open(EXISTING_FILE, "w") as f:
        for q in questions:
            f.write(q["q"].lower().strip() + "\n")

    print(f"Saved {len(questions)} questions to {QUESTIONS_FILE}")
    print(f"Updated {EXISTING_FILE}")


if __name__ == "__main__":
    main()
